<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Decode and KV Cache – Advanced LLM Performance Engineering</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch-m4-c10.html" rel="next">
<link href="../chapters/ch-m4-c08.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5c9691461893454a086f8fd2bcb3ff91.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
  <style id="book-image-preview-style">
    img[data-book-image-preview] {
      cursor: zoom-in;
    }
    img[data-book-image-preview]:focus {
      outline: 3px solid rgba(15, 107, 120, 0.36);
      outline-offset: 4px;
    }
    body.book-image-preview-open {
      overflow: hidden;
    }
    .book-image-preview-overlay[hidden] {
      display: none !important;
    }
    .book-image-preview-overlay {
      position: fixed;
      inset: 0;
      z-index: 10000;
      display: grid;
      place-items: center;
      padding: 24px;
    }
    .book-image-preview-backdrop {
      position: absolute;
      inset: 0;
      border: 0;
      background: rgba(18, 28, 40, 0.76);
      cursor: zoom-out;
    }
    .book-image-preview-dialog {
      position: relative;
      width: min(94vw, 1100px);
      max-height: 94vh;
      padding: 16px;
      border: 1px solid rgba(255, 255, 255, 0.36);
      border-radius: 8px;
      background: #ffffff;
      box-shadow: 0 24px 70px rgba(18, 28, 40, 0.34);
    }
    .book-image-preview-close {
      display: block;
      margin: 0 0 12px auto;
      padding: 7px 12px;
      border: 1px solid #d7e2e8;
      border-radius: 6px;
      background: #f5f8fa;
      color: #1f2f44;
      font: inherit;
      font-weight: 700;
      cursor: pointer;
    }
    .book-image-preview-image {
      display: block;
      width: 100%;
      max-height: calc(94vh - 74px);
      object-fit: contain;
      border-radius: 6px;
      background: #eef6f7;
    }
  </style>
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-ii.html">Part II: Training and Inference Workloads</a></li><li class="breadcrumb-item"><a href="../chapters/ch-m4-c09.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Decode and KV Cache</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Advanced LLM Performance Engineering</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Advanced LLM Performance Engineering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/ch-m4-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction and Learning Path</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part I: Fundamentals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">LLM Workloads and Performance Limits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">GPU Hardware and Memory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Software to CUDA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Triton and Custom Kernels</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Performance Models and Profiling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Compilation and Runtime</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part II: Training and Inference Workloads</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Training and Precision</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference Workloads</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c09.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Decode and KV Cache</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Serving Engines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Performance Experiments</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part III: Communication and Distributed Systems</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">GPU Communication</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Distributed Training and Serving</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/ch-m4-app-a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Reference Material</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/ch-m4-app-c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-m4-c09-s01" id="toc-sec-m4-c09-s01" class="nav-link active" data-scroll-target="#sec-m4-c09-s01"><span class="header-section-number">9.1</span> Decode loop anatomy</a></li>
  <li><a href="#sec-m4-c09-s02" id="toc-sec-m4-c09-s02" class="nav-link" data-scroll-target="#sec-m4-c09-s02"><span class="header-section-number">9.2</span> Recompute and cache reuse</a></li>
  <li><a href="#sec-m4-c09-s03" id="toc-sec-m4-c09-s03" class="nav-link" data-scroll-target="#sec-m4-c09-s03"><span class="header-section-number">9.3</span> GEMV-like behavior in decode</a></li>
  <li><a href="#sec-m4-c09-s04" id="toc-sec-m4-c09-s04" class="nav-link" data-scroll-target="#sec-m4-c09-s04"><span class="header-section-number">9.4</span> Key-value cache layout</a></li>
  <li><a href="#sec-m4-c09-s05" id="toc-sec-m4-c09-s05" class="nav-link" data-scroll-target="#sec-m4-c09-s05"><span class="header-section-number">9.5</span> PagedAttention</a></li>
  <li><a href="#sec-m4-c09-s06" id="toc-sec-m4-c09-s06" class="nav-link" data-scroll-target="#sec-m4-c09-s06"><span class="header-section-number">9.6</span> Hybrid attention and SSM-style serving state</a></li>
  <li><a href="#sec-m4-c09-s08" id="toc-sec-m4-c09-s08" class="nav-link" data-scroll-target="#sec-m4-c09-s08"><span class="header-section-number">9.7</span> Long-context attention variants</a></li>
  <li><a href="#sec-m4-c09-s07" id="toc-sec-m4-c09-s07" class="nav-link" data-scroll-target="#sec-m4-c09-s07"><span class="header-section-number">9.8</span> Worked decode reasoning path</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-ii.html">Part II: Training and Inference Workloads</a></li><li class="breadcrumb-item"><a href="../chapters/ch-m4-c09.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Decode and KV Cache</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-ch-m4-c09" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Decode and KV Cache</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="publisher-purpose">
<p>Explain why decode performance depends on cache growth, memory layout, batching, and kernel shape, then connect those mechanisms to measured throughput and latency.</p>
</div>
<p>Decode optimization focuses on the repeated one-token step. A small inefficiency in one step becomes large when repeated for thousands of generated tokens across many active requests. Decode is therefore a scheduling, memory-layout, and cache-management problem as much as a model-forward problem.</p>
<p>The key-value cache avoids recomputing the full prefix, but it also becomes the largest dynamic memory object in long-context serving. Cache layout determines whether decode kernels read memory efficiently. Allocation policy determines how many requests can be admitted without waste.</p>
<p>A useful diagnostic path compares naive recomputation with cached decode, inspects weight and KV traffic, and then tests launch, layout, paging, or batching changes against the measured limit. A more elaborate path is not automatically faster: metadata, indirection, compilation, and scheduling overhead can outweigh its benefit for small workloads.</p>
<p>The figure below compares how a cache can be allocated as requests grow.</p>
<div id="fig-m4-c09-f01" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Full-prefix recomputation is contrasted with cached decode, followed by small-batch weight reads, contiguous KV allocation and fragmentation, block-table paging, and fixed recurrent state as a different architecture. Section labels identify chapter 9 section map: 9.1 - Decode loop anatomy; 9.2 - Recompute and cache reuse; 9.3 - GEMV-like behavior in decode; 9.4 - Key-value cache layout; 9.5 - PagedAttention; 9.6 - Hybrid attention and SSM-style serving state; 9.7 - Long-context attention variants; 9.8 - Worked decode reasoning path.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m4-c09-f01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m4-c09-f01.png" class="img-fluid figure-img" style="width:6.25in" alt="Full-prefix recomputation is contrasted with cached decode, followed by small-batch weight reads, contiguous KV allocation and fragmentation, block-table paging, and fixed recurrent state as a different architecture. Section labels identify chapter 9 section map: 9.1 - Decode loop anatomy; 9.2 - Recompute and cache reuse; 9.3 - GEMV-like behavior in decode; 9.4 - Key-value cache layout; 9.5 - PagedAttention; 9.6 - Hybrid attention and SSM-style serving state; 9.7 - Long-context attention variants; 9.8 - Worked decode reasoning path." data-book-image-preview tabindex="0" role="button">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m4-c09-f01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Decode reuses projected key and value state but still reads a growing attention history.
</figcaption>
</figure>
</div>
<p>The allocation panels separate logical token order from physical placement. Contiguous reservation can waste free space between requests. A block table can map logical blocks to non-contiguous physical blocks, trading less over-reservation for metadata, indirection, and final-block waste. Fixed recurrent state is a different model design, not another KV layout.</p>
<p>The levers this chapter develops, in the vocabulary of <a href="ch-m4-c01.html#sec-m4-c01-s10">Section 1.6.1</a>, are do less work, because the KV cache removes the recomputation of earlier tokens, move fewer bytes, because layout decides what each decode step reads, and fit in memory, because paging decides how many requests stay resident.</p>
<section id="sec-m4-c09-s01" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="sec-m4-c09-s01"><span class="header-section-number">9.1</span> Decode loop anatomy</h2>
<p>Autoregressive generation uses prefill to predict the first output token, then decode steps to predict later tokens. A naive loop may rerun the model over the growing prefix. Let the prompt contain <span class="math inline">\(P\)</span> tokens and let the model generate <span class="math inline">\(G\)</span> new tokens without a cache. The first generation pass processes <span class="math inline">\(P\)</span> tokens. Later passes process every prefix length from <span class="math inline">\(P+1\)</span> through <span class="math inline">\(P+G-1\)</span>. Across all <span class="math inline">\(G\)</span> outputs, projection and other per-token layer work therefore processes</p>
<p><span class="math display">\[ \sum_{j=0}^{G-1}(P+j)=GP+\frac{G(G-1)}{2} \]</span></p>
<p>token positions. Dense full-prefix attention accumulates work proportional to</p>
<p><span class="math display">\[ \sum_{j=0}^{G-1}(P+j)^2=GP^2+PG(G-1)+\frac{G(G-1)(2G-1)}{6}. \]</span></p>
<p>This becomes cubic in <span class="math inline">\(G\)</span> only when generated length grows large relative to the fixed prompt. Caching avoids repeating the old key and value projections, but each new query still attends to a growing history. After prefill, the <span class="math inline">\(j\)</span>th single-token decode call attends to <span class="math inline">\(P+j\)</span> positions, including its current input token.</p>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: Cached decode loop</strong></p>
<p>This runnable example takes a loaded model, input token IDs, and a requested new-token count as input. It returns concatenated generated token IDs for a fixed-length greedy decode decision. It assumes unpadded, equal-length prompts and a compatible Hugging Face Transformers model in evaluation mode (<code>model.eval()</code>) whose <code>forward</code> method accepts <code>past_key_values</code> and infers positions from the growing cache. Padded batches and models with explicit cache-position APIs need additional masks and position arguments. This is not a universal generation wrapper. A zero-token request returns an empty output without running the model. Otherwise, prefill predicts the first output token and creates the cache. Each later call consumes the previous token, reads the cache, and predicts the next token. The loop generates a fixed number of tokens without early stopping at an end-of-sequence token.</p>
</div>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: Cached decode loop</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m4-c09-c01"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m4-c09-c01-1"><a href="#lst-m4-c09-c01-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="lst-m4-c09-c01-2"><a href="#lst-m4-c09-c01-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m4-c09-c01-3"><a href="#lst-m4-c09-c01-3" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.inference_mode</span>()</span>
<span id="lst-m4-c09-c01-4"><a href="#lst-m4-c09-c01-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cached_decode(model, input_ids, max_new_tokens):</span>
<span id="lst-m4-c09-c01-5"><a href="#lst-m4-c09-c01-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> max_new_tokens <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="lst-m4-c09-c01-6"><a href="#lst-m4-c09-c01-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> torch.empty((input_ids.size(<span class="dv">0</span>), <span class="dv">0</span>), dtype<span class="op">=</span>input_ids.dtype, device<span class="op">=</span>input_ids.device)</span>
<span id="lst-m4-c09-c01-7"><a href="#lst-m4-c09-c01-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="lst-m4-c09-c01-8"><a href="#lst-m4-c09-c01-8" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> model(input_ids, use_cache<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m4-c09-c01-9"><a href="#lst-m4-c09-c01-9" aria-hidden="true" tabindex="-1"></a>    past <span class="op">=</span> out.past_key_values</span>
<span id="lst-m4-c09-c01-10"><a href="#lst-m4-c09-c01-10" aria-hidden="true" tabindex="-1"></a>    token <span class="op">=</span> out.logits[:, <span class="op">-</span><span class="dv">1</span>].argmax(dim<span class="op">=-</span><span class="dv">1</span>, keepdim<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m4-c09-c01-11"><a href="#lst-m4-c09-c01-11" aria-hidden="true" tabindex="-1"></a>    generated <span class="op">=</span> [token]</span>
<span id="lst-m4-c09-c01-12"><a href="#lst-m4-c09-c01-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m4-c09-c01-13"><a href="#lst-m4-c09-c01-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(max_new_tokens <span class="op">-</span> <span class="dv">1</span>):</span>
<span id="lst-m4-c09-c01-14"><a href="#lst-m4-c09-c01-14" aria-hidden="true" tabindex="-1"></a>        out <span class="op">=</span> model(token, past_key_values<span class="op">=</span>past, use_cache<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m4-c09-c01-15"><a href="#lst-m4-c09-c01-15" aria-hidden="true" tabindex="-1"></a>        past <span class="op">=</span> out.past_key_values</span>
<span id="lst-m4-c09-c01-16"><a href="#lst-m4-c09-c01-16" aria-hidden="true" tabindex="-1"></a>        token <span class="op">=</span> out.logits[:, <span class="op">-</span><span class="dv">1</span>].argmax(dim<span class="op">=-</span><span class="dv">1</span>, keepdim<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m4-c09-c01-17"><a href="#lst-m4-c09-c01-17" aria-hidden="true" tabindex="-1"></a>        generated.append(token)</span>
<span id="lst-m4-c09-c01-18"><a href="#lst-m4-c09-c01-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m4-c09-c01-19"><a href="#lst-m4-c09-c01-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.cat(generated, dim<span class="op">=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The return value contains only generated token IDs, not the original prompt. Attention still reads a cache that grows with context length, so removing prefix recomputation does not make each step constant-cost. The remaining work is often sensitive to memory bandwidth and per-step launch overhead.</p>
</section>
<section id="sec-m4-c09-s02" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="sec-m4-c09-s02"><span class="header-section-number">9.2</span> Recompute and cache reuse</h2>
<p>Decode implementations trade one cost for another. The three variants below move from recomputation to persistent state and then to runtime-managed execution, but their ranking depends on request size, batch, cache pressure, and implementation overhead.</p>
<ul>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Naive decode:</strong></span> Every new token recomputes attention over the whole prefix from scratch. It is simple but quickly becomes wasteful because history is processed repeatedly.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Cached decode:</strong></span> The model stores key and value tensors from previous tokens. Each new step processes only the newest token and attends to cached history, trading recomputation for persistent memory reads.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Optimized decode:</strong></span> The serving stack reduces launch overhead, improves batching, lays out cache reads efficiently, pages KV memory, and avoids allocator churn.</li>
<li><strong>Main trade-off:</strong> Caching reduces compute but creates a large dynamic memory object. Optimizing decode is therefore both a kernel problem and a memory-management problem.</li>
</ul>
<p>This progression explains why a cached loop can be much faster than naive recomputation while still performing poorly in production. Once recomputation is gone, decode is often limited by reading weights and KV cache, maintaining enough active sequences, and launching repeated small steps without CPU gaps.</p>
</section>
<section id="sec-m4-c09-s03" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="sec-m4-c09-s03"><span class="header-section-number">9.3</span> GEMV-like behavior in decode</h2>
<p>A model can have high theoretical FLOP/s during prefill and still produce slow tokens during decode because workload shape and model size determine whether decode maps to a compute-rich matrix-matrix multiply (GEMM) or to a bandwidth-sensitive path that behaves like a matrix-vector multiply (GEMV).</p>
<p><a href="ch-m4-c03.html#sec-m4-c03-s11">Section 3.7</a> defined GEMM and GEMV, and <a href="ch-m4-c02.html#sec-m4-c02-s08">Section 2.8</a> showed why their arithmetic intensity differs. The distinction matters because matrix-matrix work reuses loaded weights across many output columns, while matrix-vector work often reads many weights for only one or a few token vectors.</p>
<ul>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>GEMV-like decode:</strong></span> A small-batch decode step multiplies large projection matrices by one or a few token vectors. Weight reuse is low, so arithmetic intensity is low.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>GEMM-like prefill:</strong></span> Prompt processing uses many token positions at once, so the same weights can be reused across a larger matrix of activations. This is usually better for tensor-core utilization.</li>
<li><strong>Bandwidth implication:</strong> Small-batch decode may be dominated by reading model weights and KV cache rather than by raw arithmetic throughput.</li>
<li><strong>Batching implication:</strong> Continuous batching and grouped requests can make the decode step less vector-like by increasing useful work per launch, but they are constrained by latency and KV-cache capacity.</li>
</ul>
<p>The whole decode step follows the reasoning of <a href="ch-m4-c02.html#sec-m4-c02-s08">Section 2.8</a>. For a dense model whose weights must be fetched from HBM each step, an ideal batch-size-one pass reads each required weight once to produce one token, so the time per token cannot be shorter than the weight bytes divided by the HBM bandwidth. The KV cache adds its own bytes, and those bytes are normally separate for each sequence unless the engine reuses shared-prefix blocks.</p>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: The decode-step floor for an 8B model</strong></p>
<p><strong>Inputs:</strong> A Llama 3 8B-class model (<a href="ch-m4-c01.html#sec-m4-c01-s09">Section 1.1</a>) holds <span class="math inline">\(8\times10^9\)</span> BF16 parameters, or 16 GB, and its KV cache takes 131,072 bytes per retained token (<a href="ch-m4-c01.html#sec-m4-c01-s02">Section 1.3</a>). An H100 SXM reads HBM at 3.35 TB/s. The estimate ignores activations and assumes that every byte is read once at full bandwidth, so real steps are slower.</p>
<div id="tbl-m4-c09-t02" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c09-t02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.1: Decode step-time floor for different numbers of sequences and tokens each.
</figcaption>
<div aria-describedby="tbl-m4-c09-t02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Sequences <span class="math inline">\(B\)</span></th>
<th>Tokens each <span class="math inline">\(T\)</span></th>
<th>Weight bytes</th>
<th>KV bytes</th>
<th>Step-time floor</th>
<th>Ideal tokens/s ceiling, all sequences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>8,192</td>
<td>16.0 GB</td>
<td>1.07 GB</td>
<td>5.1 ms</td>
<td>196</td>
</tr>
<tr class="even">
<td>32</td>
<td>2,048</td>
<td>16.0 GB</td>
<td>8.6 GB</td>
<td>7.3 ms</td>
<td>4,360</td>
</tr>
<tr class="odd">
<td>32</td>
<td>8,192</td>
<td>16.0 GB</td>
<td>34.4 GB</td>
<td>15.0 ms</td>
<td>2,129</td>
</tr>
<tr class="even">
<td>345</td>
<td>2,048</td>
<td>16.0 GB</td>
<td>92.6 GB</td>
<td>Not admitted on 80 GB</td>
<td>Not admitted on 80 GB</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Arithmetic check:</strong> At <span class="math inline">\(B=32\)</span> the weight multiplications need <span class="math inline">\(2\times8\times10^9\times32\approx5.1\times10^{11}\)</span> FLOPs, about 0.52 ms at the 989 TFLOP/s peak. The step floor is 7.3 to 15.0 ms, so memory traffic sets the larger ideal floor in this model. A measured run can still be limited by launch overhead, inefficient kernels, or scheduling.</p>
<p><strong>Conclusion:</strong> In this ideal model, batching shares one read of the weights among all sequences. The tabulated time floors give throughput ceilings: their ratios are about 11 to 22, while each request’s modeled token interval rises from 5.1 ms to 7.3 or 15.0 ms. Actual batching gains require measurements. The weight multiplications would reach the ridge point only near 345 sequences (<a href="ch-m4-c02.html#sec-m4-c02-s08">Section 2.8</a>), but 345 sequences of 2,048 tokens need 92.6 GB of cache, more than one 80 GB GPU holds. For these model shapes and retained lengths, KV-cache capacity can limit the decode batch before the arithmetic units become the limit.</p>
</div>
<p>Attention does not improve with batching the way the weight multiplications do. For each cached token, the 32 query heads of a Llama 3 8B layer perform <span class="math inline">\(4\times32\times128\)</span> FLOPs (a score and a weighted sum per query head) on <span class="math inline">\(2\times8\times128\times2\)</span> bytes of keys and values. That is 4 FLOP per byte whatever the batch size, far below the ridge point. Long-context decode therefore stays memory-bound in attention. The levers are fewer or smaller cache entries: grouped-query attention (<a href="ch-m4-c08.html#sec-m4-c08-s09">Section 8.6</a>), KV-cache quantization (<a href="ch-m4-c08.html#sec-m4-c07-s05">Section 8.7.1</a>), and the long-context variants of <a href="#sec-m4-c09-s08">Section 9.7</a>.</p>
</section>
<section id="sec-m4-c09-s04" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="sec-m4-c09-s04"><span class="header-section-number">9.4</span> Key-value cache layout</h2>
<p>Long-context decode streams a growing key-value cache, so layout decides both whether attention kernels read efficiently and how many requests fit in memory.</p>
<p><span class="definition-term" data-custom-style="Definition Term"><strong>Key-value cache layout</strong></span> is the physical organization of cached key and value tensors in GPU High Bandwidth Memory (HBM). It specifies how layers, sequences, token positions, heads, and head dimensions are ordered, and how the serving engine finds the cache blocks for each active request during attention.</p>
<ul>
<li><strong>Layer dimension:</strong> Each transformer layer stores its own key and value tensors because attention state is layer-specific.</li>
<li><strong>Sequence and token dimensions:</strong> The cache must preserve token order for each request, even when physical blocks are not contiguous.</li>
<li><strong>Head and head-dimension layout:</strong> The arrangement of KV heads and per-head vector elements affects whether attention kernels can read contiguous addresses.</li>
<li><strong>Append path:</strong> Each token processed by a cached model call adds new keys and values. Selecting the next token alone does not append it. The layout must make this write path cheap enough for repeated decode steps.</li>
<li><strong>Read path:</strong> Every decode step rereads prior keys and values for attention. This read path is often more important than append cost for long contexts.</li>
<li><strong>Block table:</strong> Paged layouts add metadata mapping logical token blocks to physical cache blocks, trading lookup indirection for lower memory waste.</li>
</ul>
<p>A cache layout should support coalesced reads by attention kernels, efficient append of new keys and values, and fast lookup for each active sequence. Grouped-query attention reduces the number of key-value heads and therefore cache size. Quantizing the cache can reduce bandwidth, but only if the attention path supports the format efficiently.</p>
<div class="publisher-clarification-note" data-custom-style="Clarification Note">
<p><strong>One word, four meanings: cache</strong></p>
<p><strong>Hardware cache:</strong> the L1 and L2 storage between the SMs and HBM (<a href="ch-m4-c02.html#sec-m4-c02-s03">Section 2.3</a>). Software influences it through access patterns and supported cache hints or persistence controls, while hardware still manages cache-line placement and eviction<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p><strong>KV cache:</strong> the keys and values kept in HBM so that a decode step does not recompute the whole prefix (<a href="#sec-m4-c09-s01">Section 9.1</a>). The serving engine decides what stays there, which is why layout, block size, and paging policy are optimization objects at all.</p>
<p><strong>Prefix cache:</strong> KV blocks kept after a request finishes so that a later request with the same opening tokens can reuse them (<a href="ch-m4-c10.html#sec-m4-c10-s07">Section 10.5</a>).</p>
<p><strong>External KV cache layer:</strong> KV blocks moved out of GPU memory into host memory or storage, to be fetched back when needed (<a href="ch-m4-c10.html#sec-m4-c10-s10">Section 10.5.3</a>).</p>
<p>Only the first is hardware-managed. The other three are engine policy, and they are where the decisions in this chapter and the next are made.</p>
</div>
<p>KV blocks usually live in HBM and are reread by attention kernels at every decode step. The L2 cache may help when accesses are nearby or repeated, but long-context decode can stream through more KV data than the hardware cache holds, so the reliable objects to change are KV layout, block size, paging policy, attention-kernel tiling, and request locality.</p>
</section>
<section id="sec-m4-c09-s05" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="sec-m4-c09-s05"><span class="header-section-number">9.5</span> PagedAttention</h2>
<p><span class="definition-term" data-custom-style="Definition Term"><strong>PagedAttention</strong></span> is a KV-cache management technique that maps logical token blocks in a sequence to reusable physical KV-cache blocks in GPU memory<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. The idea is similar to virtual memory: a request has an ordered logical sequence, while the engine is free to place the underlying physical blocks wherever capacity is available.</p>
<p>The problem is variable sequence length. If an engine reserves one large contiguous KV region for the maximum possible output length of every request, short completions leave unused space and long-running service can fragment memory. Paging reduces this waste by allocating fixed-size blocks on demand.</p>
<div id="fig-m4-c09-f02" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The empty regions represent capacity wasted by a naive policy that reserves a maximum-length contiguous KV region for each request. Other contiguous allocators may reserve less and have different waste patterns. Paging allocates reusable physical blocks on demand and reduces fragmentation and tail waste. It does not remove all waste: partially filled final blocks, block tables, metadata work, and indirect kernel addressing remain.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m4-c09-f02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m4-c09-f02.png" class="img-fluid figure-img" style="width:6.1in" alt="The empty regions represent capacity wasted by a naive policy that reserves a maximum-length contiguous KV region for each request. Other contiguous allocators may reserve less and have different waste patterns. Paging allocates reusable physical blocks on demand and reduces fragmentation and tail waste. It does not remove all waste: partially filled final blocks, block tables, metadata work, and indirect kernel addressing remain." data-book-image-preview tabindex="0" role="button">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m4-c09-f02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Contiguous key-value allocation can waste memory
</figcaption>
</figure>
</div>
<p>In Figure 9.2, the empty regions represent capacity wasted by a naive policy that reserves a maximum-length contiguous KV region for each request. Other contiguous allocators may reserve less and have different waste patterns.</p>
<p>Paging allocates reusable physical blocks on demand and reduces fragmentation and tail waste<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. It does not remove all waste: partially filled final blocks, block tables, metadata work, and indirect kernel addressing remain.</p>
<p>The block table is the central mechanism. Each request has a logical sequence of KV blocks: block 0, block 1, block 2, and so on. The engine maps those logical blocks to physical blocks in GPU memory. For example, request A may map logical blocks [0, 1, 2] to physical blocks [7, 2, 15]. Attention kernels use this mapping to gather the right keys and values even though the physical allocation is non-contiguous.</p>
<p>Blocks are allocated on demand as tokens are generated. This reduces waste because the engine does not need to reserve the maximum possible output length for every request at admission time. In the ideal case, all full blocks are packed and only the final block of an active sequence is partially empty. The trade-off is indirection: every request needs block-table metadata, and kernels or scheduler code must resolve logical positions to physical blocks.</p>
<div id="tbl-m4-c09-t01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c09-t01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.2: Contiguous key-value allocation versus paged allocation.
</figcaption>
<div aria-describedby="tbl-m4-c09-t01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>Contiguous allocation</th>
<th>PagedAttention-style allocation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Memory reservation</td>
<td>Often reserves for maximum or estimated length</td>
<td>Allocates fixed-size blocks as needed</td>
</tr>
<tr class="even">
<td>Fragmentation</td>
<td>Can waste space for short outputs</td>
<td>Reduces waste through block reuse</td>
</tr>
<tr class="odd">
<td>Lookup</td>
<td>Simple pointer arithmetic</td>
<td>Block-table indirection</td>
</tr>
<tr class="even">
<td>Scheduler complexity</td>
<td>Lower</td>
<td>Higher, because block assignment must be tracked</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Paged allocation is most useful when variable request lengths make contiguous reservation waste enough HBM to limit admission. It changes cache allocation and lookup, not the attention formula, so kernel efficiency, scheduler fairness, and prefix-cache correctness remain separate measurements.</p>
<p>Paging also allows the engine to run out of free blocks while requests are still generating, because each running request keeps requesting new blocks. The engine must then stop some running requests and release their blocks, a step called <span class="definition-term" data-custom-style="Definition Term"><strong>preemption</strong></span>. <span class="definition-term" data-custom-style="Definition Term"><strong>vLLM</strong></span> 0.6.4 (an open-source serving engine, <a href="ch-m4-c10.html#sec-m4-c10-s01">Section 10.1</a>) recomputes a preempted request’s KV cache once space becomes available again and warns that preemption can affect latency. Its documentation suggests more cache memory (<code>gpu_memory_utilization</code>), fewer concurrent sequences or batched tokens (<code>max_num_seqs</code>, <code>max_num_batched_tokens</code>), or more tensor parallelism.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> The PagedAttention design also describes <span class="definition-term" data-custom-style="Definition Term"><strong>swapping</strong></span>, which copies the evicted blocks to CPU memory and back, trading PCIe traffic for recomputation. Recomputation can take less time than the original generation, because the prompt and the tokens generated so far are processed together as one prefill.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> Either way, preemption appears as latency spikes for the affected requests, so its rate belongs on the serving dashboard (<a href="ch-m4-c10.html#sec-m4-c10-s15">Section 10.8</a>).</p>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: PagedAttention block lookup</strong></p>
<p>This pseudocode shows the mapping idea without tying it to a particular engine implementation. The request grows in logical token order, but physical KV blocks do not need to be contiguous. The attention path pays an indirection cost to reduce allocation waste. Paging improves memory management, not the arithmetic complexity of attention. The key point is that logical sequence positions are resolved through a block table before the attention kernel reads KV memory.</p>
</div>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: PagedAttention block lookup</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m4-c09-c02"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m4-c09-c02-1"><a href="#lst-m4-c09-c02-1" aria-hidden="true" tabindex="-1"></a>block_size <span class="op">=</span> <span class="dv">16</span></span>
<span id="lst-m4-c09-c02-2"><a href="#lst-m4-c09-c02-2" aria-hidden="true" tabindex="-1"></a><span class="co"># request A: logical block -&gt; physical KV block</span></span>
<span id="lst-m4-c09-c02-3"><a href="#lst-m4-c09-c02-3" aria-hidden="true" tabindex="-1"></a>block_table <span class="op">=</span> {<span class="dv">0</span>: <span class="dv">7</span>, <span class="dv">1</span>: <span class="dv">2</span>, <span class="dv">2</span>: <span class="dv">15</span>}</span>
<span id="lst-m4-c09-c02-4"><a href="#lst-m4-c09-c02-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m4-c09-c02-5"><a href="#lst-m4-c09-c02-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> physical_location(token_index):</span>
<span id="lst-m4-c09-c02-6"><a href="#lst-m4-c09-c02-6" aria-hidden="true" tabindex="-1"></a>    logical_block <span class="op">=</span> token_index <span class="op">//</span> block_size</span>
<span id="lst-m4-c09-c02-7"><a href="#lst-m4-c09-c02-7" aria-hidden="true" tabindex="-1"></a>    offset <span class="op">=</span> token_index <span class="op">%</span> block_size</span>
<span id="lst-m4-c09-c02-8"><a href="#lst-m4-c09-c02-8" aria-hidden="true" tabindex="-1"></a>    physical_block <span class="op">=</span> block_table[logical_block]</span>
<span id="lst-m4-c09-c02-9"><a href="#lst-m4-c09-c02-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> physical_block, offset</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The pseudocode implements only metadata translation from a logical token position to a physical block and offset. A complete implementation also accounts for layer, KV head, vector dimension, append writes, vectorized reads, and the attention kernel that consumes the resolved addresses. <strong>Conclusion:</strong> Block lookup trades indirection for less reserved capacity. Admission and latency measurements show whether that trade-off helps the workload.</p>
</section>
<section id="sec-m4-c09-s06" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="sec-m4-c09-s06"><span class="header-section-number">9.6</span> Hybrid attention and SSM-style serving state</h2>
<p>In a hybrid model that mixes attention layers with state-space or recurrent layers, attention layers still store one key and value record per retained token, so their state and read traffic grow with context length. The state-space or recurrent layers instead update a fixed-size hidden state for each sequence. In this architecture family, replacing some attention layers with recurrent layers can therefore reduce long-context KV capacity and bandwidth, but it changes the work rather than removing it. These objects are architecture-specific: the model and runtime documentation defines their scan or recurrent-update kernels, state layout, chunking, invalidation, and prefix rules. The recurrent state is a compressed summary, not an addressable record of every past token.</p>
<p>For a recurrent layer, the current token’s input features and the previous hidden state determine a new state and an output for the next layer. The worker reads the old state, computes the update, and retains the new state in its place. A <span class="definition-term" data-custom-style="Definition Term"><strong>state-space model (SSM)</strong></span> uses a structured state update and an output mapping. Selective SSMs such as Mamba allow parts of those mappings to depend on the current input<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>. The following fixed-coefficient recurrence isolates the storage behavior. It is not a complete Mamba block, a token predictor, or a model-quality comparison.</p>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: Two tokens and a fixed state</strong></p>
<p><strong>Inputs and task:</strong> In inference mode, let <span class="math inline">\(x_t\)</span> be one scalar feature of token <span class="math inline">\(t\)</span>, rather than its vocabulary ID. The old state is a two-element vector <span class="math inline">\(h_{t-1}\)</span>, initially <span class="math inline">\(h_0=(0,0)\)</span>. Use fixed update rules <span class="math inline">\(h_{t,1}=0.5h_{t-1,1}+x_t\)</span> and <span class="math inline">\(h_{t,2}=0.25h_{t-1,2}+2x_t\)</span>. The layer output is the scalar <span class="math inline">\(y_t=h_{t,1}+h_{t,2}\)</span>. The question is what must remain stored after processing features <span class="math inline">\(x_1=2\)</span> and <span class="math inline">\(x_2=1\)</span>.</p>
<ol type="1">
<li>At token 1, the retained contribution from <span class="math inline">\(h_0\)</span> is <span class="math inline">\((0,0)\)</span> and the input contributes <span class="math inline">\((2,4)\)</span>. The new state is <span class="math inline">\(h_1=(2,4)\)</span> and the output is <span class="math inline">\(y_1=6\)</span>.</li>
<li>At token 2, the old state contributes <span class="math inline">\((0.5(2),0.25(4))=(1,1)\)</span> and the new input contributes <span class="math inline">\((1,2)\)</span>. The new state is <span class="math inline">\(h_2=(2,3)\)</span> and the output is <span class="math inline">\(y_2=5\)</span>. It replaces <span class="math inline">\(h_1\)</span> for subsequent recurrent execution.</li>
</ol>
<p><strong>Conclusion:</strong> The state still has two elements, but both contain contributions from earlier input. The worker retains <span class="math inline">\(h_2\)</span>, not a list of <span class="math inline">\(h_0,h_1,h_2\)</span>. An attention layer retaining these two token positions instead adds two KV records, <span class="math inline">\((k_1,v_1)\)</span> and <span class="math inline">\((k_2,v_2)\)</span>, to its history. Fixed state shape limits recurrent storage growth but does not preserve separately addressable token records or establish equivalent model quality.</p>
</div>
<p>Prompt processing has all prompt inputs available. A <span class="definition-term" data-custom-style="Definition Term"><strong>scan</strong></span> computes the sequence of states obtained by applying the update through each input prefix. Suitable affine updates can be composed and evaluated with a parallel scan while preserving those dependencies. Single-token decode has only the newest input and carried state, so it performs one recurrent update. Chunked prompt execution passes the final state of one chunk into the next<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p>
<p>Mamba-style serving therefore shifts attention toward scan kernels, recurrent updates, chunking, and state layout. Fixed recurrent state describes retained inference state per sequence and layer. It does not mean prompt outputs, temporary workspaces, or training activations take constant total memory. Hybrid models still retain growing KV history in their attention layers, and actual runtimes may also keep other architecture-specific state.</p>
</section>
<section id="sec-m4-c09-s08" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="sec-m4-c09-s08"><span class="header-section-number">9.7</span> Long-context attention variants</h2>
<p>The worked example in <a href="#sec-m4-c09-s03">Section 9.3</a> showed that, at long contexts, the KV cache can outweigh the weights in both capacity and bytes read per step. Standard attention stores and rereads a key and a value for every retained token in every layer. Several design families reduce that state. They differ in whether they change the model, which must then be trained or adapted for them, and in what the model can no longer recall.</p>
<ul>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Sliding-window attention</strong></span>: each layer attends only to the most recent <span class="math inline">\(W\)</span> positions. Information from further back can still propagate through stacked layers. Mistral 7B uses <span class="math inline">\(W=4{,}096\)</span>, giving a theoretical attention span of about 131,000 tokens at the last layer, and its fixed-size rolling cache reduces cache memory by 8 times at 32,000 tokens without reported quality loss.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> The window is part of the model and is set during training.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Attention sinks</strong></span> and KV eviction: an engine keeps the cache entries of the first few tokens plus a recent window and discards the rest. StreamingLLM observed that plain window attention fails once text exceeds the cache, and that keeping the initial tokens recovers performance. This let models trained with a finite window process streams of up to 4 million tokens without fine-tuning, with up to 22.2 times the speed of recomputing a sliding window.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> Evicted tokens cannot be recalled, so details from the middle of a long input may be lost.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Latent KV compression</strong></span>: the model stores a compressed low-rank vector per token instead of full keys and values, and reconstructs what attention needs. DeepSeek-V2 uses Multi-head Latent Attention (MLA) for this compression. The complete DeepSeek-V2 model reduced KV cache by 93.3 percent and reached 5.76 times the maximum generation throughput of DeepSeek 67B. That comparison also includes other architectural changes.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> This also requires a model trained or adapted for the architecture.</li>
<li>Fewer or narrower entries within standard attention: grouped-query attention (<a href="ch-m4-c08.html#sec-m4-c08-s09">Section 8.6</a>) and KV-cache quantization (<a href="ch-m4-c08.html#sec-m4-c07-s05">Section 8.7.1</a>).</li>
<li>Spreading the context across GPUs: <strong>context parallelism</strong> divides one long sequence among several devices at the cost of communication (<a href="ch-m4-c13.html#sec-m4-c13-s14">Section 13.5.4</a>).</li>
</ul>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: One 128k-token sequence</strong></p>
<p><strong>Inputs:</strong> Llama 3 8B-like shapes: 32 layers and head dimension 128. The sequence retains 131,072 tokens, and the cache is BF16 (2 bytes) unless stated otherwise. The KV bytes per sequence are <span class="math inline">\(2\times T\times L\times H_{\mathrm{kv}}\times d_h\times b\)</span> (<a href="ch-m4-c08.html#sec-m4-c08-s09">Section 8.6</a>). These are raw payload sizes before scale metadata, block rounding, and other runtime overhead.</p>
<div id="tbl-m4-c09-t03" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c09-t03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.3: KV-cache size of one long sequence under different attention designs.
</figcaption>
<div aria-describedby="tbl-m4-c09-t03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Attention design</th>
<th>Tokens stored</th>
<th>KV heads</th>
<th>Bytes per element</th>
<th>KV cache for the sequence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Full multi-head attention</td>
<td>131,072</td>
<td>32</td>
<td>2</td>
<td>64 GiB</td>
</tr>
<tr class="even">
<td>Grouped-query attention</td>
<td>131,072</td>
<td>8</td>
<td>2</td>
<td>16 GiB</td>
</tr>
<tr class="odd">
<td>Grouped-query attention, FP8 cache</td>
<td>131,072</td>
<td>8</td>
<td>1</td>
<td>8 GiB</td>
</tr>
<tr class="even">
<td>Grouped-query, 4,096-token window</td>
<td>4,096</td>
<td>8</td>
<td>2</td>
<td>0.5 GiB</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Conclusion:</strong> At this length the attention design sets the memory budget: the same model shape needs between 0.5 and 64 GiB for one sequence. The smaller designs are not free. Grouped-query attention and windows require a model trained or adapted for those designs, quantization adds rounding error, and eviction forgets tokens, so each needs a quality check on long-context tasks (<a href="ch-m4-c08.html#sec-m4-c07-s08">Section 8.7.4</a>).</p>
</div>
</section>
<section id="sec-m4-c09-s07" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="sec-m4-c09-s07"><span class="header-section-number">9.8</span> Worked decode reasoning path</h2>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked reasoning path: Decode bottleneck</strong></p>
<p>A decode bottleneck is assessed through the one-token path in a fixed order. The comparison begins with cached and uncached decode, then uses timeline and memory counters to determine whether repeated computation, GPU idle gaps, HBM traffic, or KV capacity currently limits the service metric.</p>
<ul>
<li><strong>Step 1: naive and cached decode:</strong> A small caching benefit can reflect short prefixes, an already optimized baseline, cache-management overhead, incorrect cache use, or a limit outside prefix recomputation.</li>
<li><strong>Step 2: per-token trace:</strong> GPU gaps suggest launch overhead, Python scheduling, or engine control-plane cost. A large HBM byte count with busy kernels makes bandwidth limitation a hypothesis. For the same kernel region, compare bytes divided by elapsed time with the applicable sustained HBM bandwidth, and compare achieved FLOP/s with the compute and arithmetic-intensity-based bandwidth ceilings from <a href="ch-m4-c05.html#sec-m4-c05-s01">Section 5.1</a>. Near-ceiling memory throughput with low math utilization supports the hypothesis. The counters and follow-up measurements in <a href="ch-m4-c05.html#sec-m4-c05-s09">Section 5.4.3</a> distinguish it from launch, occupancy, or access-pattern limits. A controlled reduction in transferred bytes that lowers decode time at fixed workload and acceptable quality provides further evidence. Paging alone may improve admission without reducing the bytes read for an already-admitted request.</li>
<li><strong>Step 3: stable single-worker loop:</strong> Compilation or CUDA Graph replay applies when shapes and memory addresses are stable and profiler traces show launch-bound behavior.</li>
<li><strong>Step 4: useful batch size:</strong> Continuous batching can recover utilization while time to first token (TTFT), time per output token (TPOT), and cache capacity remain within the service target.</li>
<li><strong>Step 5: cache-memory pressure:</strong> PagedAttention, prefix reuse, grouped-query attention, or KV-cache quantization become relevant when cache allocation or HBM bandwidth limits admission or latency.</li>
</ul>
</div>
<p>The resulting optimization sequence is workload-specific. A short-output chatbot, a long-context retrieval system, and a high-throughput batch generator can expose different decode bottlenecks even with the same model.</p>
<p>These changes still operate inside one worker’s decode and cache path. Chapter 10 adds the serving-engine policies that decide which requests advance together, which prefixes are reused, and how prefill, decode, and speculative verification share GPU time.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>NVIDIA. (n.d.). <em>CUDA Programming Guide</em>, L2 Cache Control. Retrieved September 28, 2026, from <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/04-special-topics/l2-cache-control.html">L2 Cache Control</a>. Describes streaming and persisting access preferences and the L2 set-aside controls. These controls influence retention where supported; they do not guarantee that every requested cache line remains resident.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Kwon, W., et al.&nbsp;(2023). <em>Efficient Memory Management for Large Language Model Serving with PagedAttention</em>. In SOSP 2023. arXiv:2309.06180. <a href="https://arxiv.org/abs/2309.06180">https://arxiv.org/abs/2309.06180</a>. Supports partitioning KV cache into fixed size blocks mapped non-contiguously through a block table, cutting fragmentation and bounding waste to the final partial block plus metadata. Limit: block tables, metadata and indirection remain, and prefix sharing correctness still needs separate checks.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Kwon, W., et al.&nbsp;(2023). <em>Efficient Memory Management for Large Language Model Serving with PagedAttention</em>. In SOSP 2023. arXiv:2309.06180. <a href="https://arxiv.org/abs/2309.06180">https://arxiv.org/abs/2309.06180</a>. Supports partitioning KV cache into fixed size blocks mapped non-contiguously through a block table, cutting fragmentation and bounding waste to the final partial block plus metadata. Limit: block tables, metadata and indirection remain, and prefix sharing correctness still needs separate checks.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>vLLM contributors. (n.d.). <em>Performance and Tuning</em>, Preemption (v0.6.4.post1 documentation). <a href="https://docs.vllm.ai/en/v0.6.4.post1/models/performance.html">https://docs.vllm.ai/en/v0.6.4.post1/models/performance.html</a>. Supports that requests are preempted when KV cache space is insufficient, that preempted requests are recomputed when space becomes available, and the three suggested mitigations. Limit: later releases can change the default policy and settings.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Kwon, W., et al.&nbsp;(2023). <em>Efficient Memory Management for Large Language Model Serving with PagedAttention</em>. In SOSP 2023. arXiv:2309.06180. <a href="https://arxiv.org/abs/2309.06180">https://arxiv.org/abs/2309.06180</a>. Supports partitioning KV cache into fixed size blocks mapped non-contiguously through a block table, cutting fragmentation and bounding waste to the final partial block plus metadata. Limit: block tables, metadata and indirection remain, and prefix sharing correctness still needs separate checks.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Gu, A., &amp; Dao, T. (2023). <em>Mamba: Linear-Time Sequence Modeling with Selective State Spaces</em>. arXiv:2312.00752. <a href="https://arxiv.org/abs/2312.00752">https://arxiv.org/abs/2312.00752</a>. Supports input dependent selective SSMs with a hardware aware recurrent scan that keeps state fixed size, scales linearly in length, and avoids per-step KV growth. Limit: the recurrent state is a compressed summary rather than addressable history, and scan kernels, chunking and layout are architecture and runtime specific.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Gu, A., &amp; Dao, T. (2023). <em>Mamba: Linear-Time Sequence Modeling with Selective State Spaces</em>. arXiv:2312.00752. <a href="https://arxiv.org/abs/2312.00752">https://arxiv.org/abs/2312.00752</a>. Supports input dependent selective SSMs with a hardware aware recurrent scan that keeps state fixed size, scales linearly in length, and avoids per-step KV growth. Limit: the recurrent state is a compressed summary rather than addressable history, and scan kernels, chunking and layout are architecture and runtime specific.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Jiang, A. Q., et al.&nbsp;(2023). <em>Mistral 7B</em>. <a href="https://arxiv.org/abs/2310.06825">arXiv:2310.06825</a>. Supports sliding-window attention with W = 4,096, a theoretical attention span of about 131K tokens at the last layer, and a rolling buffer cache that reduces cache memory by 8x on 32k-token sequences without impacting model quality in the paper’s tests. Limit: the quality statement applies to the paper’s evaluations.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Xiao, G., Tian, Y., Chen, B., Han, S., &amp; Lewis, M. (2024). <em>Efficient Streaming Language Models with Attention Sinks</em>. ICLR 2024. <a href="https://arxiv.org/abs/2309.17453">arXiv:2309.17453</a>. Supports the attention-sink observation, that keeping the KV of initial tokens recovers window-attention performance, streaming to 4 million tokens without fine-tuning, and up to 22.2x speedup over sliding-window recomputation. Limit: evicted tokens are not available to later attention.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>DeepSeek-AI. (2024). <em>DeepSeek-V2: A Strong, Economical, and Efficient Mixture-of-Experts Language Model</em>. <a href="https://arxiv.org/abs/2405.04434">arXiv:2405.04434</a>. Supports Multi-head Latent Attention with low-rank key-value joint compression, a 93.3 percent KV-cache reduction and 5.76x maximum generation throughput relative to DeepSeek 67B. Limit: the comparison is between two specific models and also reflects other architectural changes.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch-m4-c08.html" class="pagination-link" aria-label="Inference Workloads">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference Workloads</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch-m4-c10.html" class="pagination-link" aria-label="Serving Engines">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Serving Engines</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




  <div class="book-image-preview-overlay" data-book-image-overlay hidden>
    <button class="book-image-preview-backdrop" type="button" data-book-image-close aria-label="Close image preview"></button>
    <div class="book-image-preview-dialog" role="dialog" aria-modal="true" aria-label="Image preview">
      <button class="book-image-preview-close" type="button" data-book-image-close>Close</button>
      <img class="book-image-preview-image" data-book-image-preview-img alt="">
    </div>
  </div>
  <script id="book-image-preview-script">
    (() => {
      if (window.__bookImagePreviewReady) {
        return;
      }
      window.__bookImagePreviewReady = true;

      const overlay = document.querySelector("[data-book-image-overlay]");
      const preview = document.querySelector("[data-book-image-preview-img]");
      const closeButtons = document.querySelectorAll("[data-book-image-close]");
      const closeButton = overlay ? overlay.querySelector(".book-image-preview-close") : null;
      let restoreFocus = null;

      if (!overlay || !preview) {
        return;
      }

      function openPreview(image) {
        restoreFocus = image;
        preview.src = image.currentSrc || image.src;
        preview.alt = image.alt || "";
        overlay.hidden = false;
        document.body.classList.add("book-image-preview-open");
        if (closeButton) {
          closeButton.focus();
        }
      }

      function closePreview() {
        if (overlay.hidden) {
          return;
        }
        overlay.hidden = true;
        preview.removeAttribute("src");
        preview.alt = "";
        document.body.classList.remove("book-image-preview-open");
        if (restoreFocus) {
          restoreFocus.focus();
        }
      }

      document.querySelectorAll("img[data-book-image-preview]").forEach((image) => {
        image.addEventListener("click", () => openPreview(image));
        image.addEventListener("keydown", (event) => {
          if (event.key === "Enter" || event.key === " ") {
            event.preventDefault();
            openPreview(image);
          }
        });
      });
      closeButtons.forEach((button) => {
        button.addEventListener("click", closePreview);
      });
      document.addEventListener("keydown", (event) => {
        if (!overlay.hidden && event.key === "Escape") {
          closePreview();
        }
      });
    })();
  </script>
</body></html>