<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>13&nbsp; Distributed Training and Serving – Advanced LLM Performance Engineering</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../appendices/ch-m4-app-a.html" rel="next">
<link href="../chapters/ch-m4-c12.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5c9691461893454a086f8fd2bcb3ff91.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iii.html">Part III: Communication and Distributed Systems</a></li><li class="breadcrumb-item"><a href="../chapters/ch-m4-c13.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Distributed Training and Serving</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Advanced LLM Performance Engineering</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Advanced LLM Performance Engineering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/ch-m4-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction and Learning Path</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part I: Fundamentals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">LLM Workloads and Performance Limits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">GPU Hardware and Memory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Software to CUDA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Triton and Custom Kernels</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Performance Models and Profiling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Compilation and Runtime</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part II: Training and Inference Workloads</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Training and Precision</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference Workloads</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Decode and KV Cache</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Serving Engines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Performance Experiments</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part III: Communication and Distributed Systems</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">GPU Communication</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c13.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Distributed Training and Serving</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/ch-m4-app-a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Reference Material</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/ch-m4-app-c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-m4-c13-s01" id="toc-sec-m4-c13-s01" class="nav-link active" data-scroll-target="#sec-m4-c13-s01"><span class="header-section-number">13.1</span> Work and state beyond one GPU</a></li>
  <li><a href="#sec-m4-c13-s02" id="toc-sec-m4-c13-s02" class="nav-link" data-scroll-target="#sec-m4-c13-s02"><span class="header-section-number">13.2</span> DDP and gradient all-reduce</a>
  <ul class="collapse">
  <li><a href="#sec-m4-c13-s03" id="toc-sec-m4-c13-s03" class="nav-link" data-scroll-target="#sec-m4-c13-s03"><span class="header-section-number">13.2.1</span> torch.distributed and DDP execution</a></li>
  </ul></li>
  <li><a href="#sec-m4-c13-s04" id="toc-sec-m4-c13-s04" class="nav-link" data-scroll-target="#sec-m4-c13-s04"><span class="header-section-number">13.3</span> DDP bucket timing and overlap</a></li>
  <li><a href="#sec-m4-c13-s05" id="toc-sec-m4-c13-s05" class="nav-link" data-scroll-target="#sec-m4-c13-s05"><span class="header-section-number">13.4</span> Sharding model state</a>
  <ul class="collapse">
  <li><a href="#sec-m4-c13-s06" id="toc-sec-m4-c13-s06" class="nav-link" data-scroll-target="#sec-m4-c13-s06"><span class="header-section-number">13.4.1</span> DeepSpeed and ZeRO implementations</a></li>
  </ul></li>
  <li><a href="#sec-m4-c13-s07" id="toc-sec-m4-c13-s07" class="nav-link" data-scroll-target="#sec-m4-c13-s07"><span class="header-section-number">13.5</span> Model-parallel strategies</a>
  <ul class="collapse">
  <li><a href="#sec-m4-c13-s08" id="toc-sec-m4-c13-s08" class="nav-link" data-scroll-target="#sec-m4-c13-s08"><span class="header-section-number">13.5.1</span> Model-parallel execution and Megatron-LM</a></li>
  <li><a href="#sec-m4-c13-s09" id="toc-sec-m4-c13-s09" class="nav-link" data-scroll-target="#sec-m4-c13-s09"><span class="header-section-number">13.5.2</span> Activation-memory derivation for GPT-style training</a></li>
  <li><a href="#sec-m4-c13-s10" id="toc-sec-m4-c13-s10" class="nav-link" data-scroll-target="#sec-m4-c13-s10"><span class="header-section-number">13.5.3</span> Column-wise and row-wise tensor-parallel communication</a></li>
  <li><a href="#sec-m4-c13-s14" id="toc-sec-m4-c13-s14" class="nav-link" data-scroll-target="#sec-m4-c13-s14"><span class="header-section-number">13.5.4</span> Sequence and context parallelism for long contexts</a></li>
  </ul></li>
  <li><a href="#sec-m4-c13-s15" id="toc-sec-m4-c13-s15" class="nav-link" data-scroll-target="#sec-m4-c13-s15"><span class="header-section-number">13.6</span> Combining and sizing parallelism</a></li>
  <li><a href="#sec-m4-c13-s11" id="toc-sec-m4-c13-s11" class="nav-link" data-scroll-target="#sec-m4-c13-s11"><span class="header-section-number">13.7</span> Distributed inference and serving</a>
  <ul class="collapse">
  <li><a href="#sec-m4-c13-s12" id="toc-sec-m4-c13-s12" class="nav-link" data-scroll-target="#sec-m4-c13-s12"><span class="header-section-number">13.7.1</span> Distributed serving frameworks</a></li>
  <li><a href="#sec-m4-c13-s16" id="toc-sec-m4-c13-s16" class="nav-link" data-scroll-target="#sec-m4-c13-s16"><span class="header-section-number">13.7.2</span> Serving mixture-of-experts models</a></li>
  </ul></li>
  <li><a href="#sec-m4-c13-s13" id="toc-sec-m4-c13-s13" class="nav-link" data-scroll-target="#sec-m4-c13-s13"><span class="header-section-number">13.8</span> KV-cache locality in distributed serving</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iii.html">Part III: Communication and Distributed Systems</a></li><li class="breadcrumb-item"><a href="../chapters/ch-m4-c13.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Distributed Training and Serving</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-ch-m4-c13" class="quarto-section-identifier"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Distributed Training and Serving</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="publisher-purpose">
<p>Compare distributed training and serving strategies by the object each divides, the communication each adds, and the memory, topology, and user-metric limits each must satisfy.</p>
</div>
<p>Distributed training changes the problem from one GPU executing one copy of the workload to many GPUs coordinating state and computation. The central design question is what is replicated, what is sharded, and what must be communicated every step.</p>
<p>The scaling axis follows the object that prevents one device from meeting the target. Data parallelism splits examples or requests, sharded data parallelism splits model state, tensor and pipeline parallelism split model computation, and expert parallelism splits expert modules and routes token representations to them. Each split creates its own collectives, cache-placement rules, and waiting points, so it must fit the topology and the user-facing metric. Distributed serving may instead divide requests across worker groups or shard one model within a group.</p>
<div id="fig-m4-c13-f01" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Distributed training plans divide data, model state, layers, stages, or experts. Distributed serving routes each request to one worker group and keeps that request's KV cache with the selected group. Section labels identify chapter 13 section map: 13.1 - Work and state beyond one GPU; 13.2 - DDP and gradient all-reduce; 13.3 - DDP bucket timing and overlap; 13.4 - Sharding model state; 13.5 - Model-parallel strategies; 13.6 - Combining and sizing parallelism; 13.7 - Distributed inference and serving; 13.8 - KV-cache locality in distributed serving.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m4-c13-f01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m4-c13-f01.png" class="img-fluid figure-img" style="width:6.25in" alt="Distributed training plans divide data, model state, layers, stages, or experts. Distributed serving routes each request to one worker group and keeps that request's KV cache with the selected group. Section labels identify chapter 13 section map: 13.1 - Work and state beyond one GPU; 13.2 - DDP and gradient all-reduce; 13.3 - DDP bucket timing and overlap; 13.4 - Sharding model state; 13.5 - Model-parallel strategies; 13.6 - Combining and sizing parallelism; 13.7 - Distributed inference and serving; 13.8 - KV-cache locality in distributed serving.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m4-c13-f01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.1: Distributed strategies divide different work or state and therefore require different communication.
</figcaption>
</figure>
</div>
<p>Each training strategy is tied to the object it divides and the collective or point-to-point transfer it needs. In serving, a router selects one worker group and the request’s KV cache stays with that group unless an explicit migration policy pays the transfer or recomputation cost.</p>
<p>The levers this chapter develops, in the vocabulary of <a href="ch-m4-c01.html#sec-m4-c01-s10">Section 1.6.1</a>, are scale out, because each parallelism strategy buys capacity with communication, and fit in memory, because sharding places state that no longer fits on one GPU.</p>
<section id="sec-m4-c13-s01" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="sec-m4-c13-s01"><span class="header-section-number">13.1</span> Work and state beyond one GPU</h2>
<p>Scaling beyond one GPU means deciding which object is too large or too slow on one device. The answer determines the distributed strategy.</p>
<ul>
<li><strong>Data:</strong> The training examples or serving requests. Splitting data can increase throughput when each replica can fit the full model, enough work is available, and communication does not dominate.</li>
<li><strong>Model state:</strong> Parameters, gradients, and optimizer state. Sharding state reduces per-GPU memory but introduces communication to gather or reduce the pieces that each step needs.</li>
<li><strong>Layer computation:</strong> Matrix multiplications and attention inside a layer. Tensor parallelism splits this work, but then partial results must be combined frequently.</li>
<li><strong>Layer sequence:</strong> The ordered stack of transformer layers. Pipeline parallelism places different layer ranges on different devices and moves activations between stages.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Experts:</strong></span> Specialized modules in a Mixture-of-Experts model. Expert parallelism routes token representations to the devices where selected experts are placed.</li>
</ul>
<p>Replication is simple but duplicates memory. Sharding saves memory or increases parallel compute, but it creates communication that must fit the topology. Distributed strategies are applications of collective communication and physical fabric constraints, not replacements for them.</p>
<p>The object being split determines the communication obligation: replicated models synchronize gradients, while split model work exchanges activations or partial results. The next question is how Distributed Data Parallel (DDP) turns replicated parameters and different local mini-batches into synchronized updates.</p>
</section>
<section id="sec-m4-c13-s02" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="sec-m4-c13-s02"><span class="header-section-number">13.2</span> DDP and gradient all-reduce</h2>
<p>Distributed Data Parallel (DDP) is the baseline multi-GPU training strategy when the full model fits on every GPU. Each process holds one model replica and computes local gradients on its assigned mini-batch shard, then synchronizes gradients before the optimizer step. DDP itself does not shard the input. The application assigns per-rank shards, for example with a distributed sampler.</p>
<section id="sec-m4-c13-s03" class="level3" data-number="13.2.1">
<h3 data-number="13.2.1" class="anchored" data-anchor-id="sec-m4-c13-s03"><span class="header-section-number">13.2.1</span> torch.distributed and DDP execution</h3>
<p>PyTorch DDP is a training strategy implemented above <code>torch.distributed</code>. The wrapper registers gradient hooks and groups gradients into buckets with a configurable <code>bucket_cap_mb</code>, following the <a href="https://docs.pytorch.org/docs/2.14/notes/ddp.html">Distributed Data Parallel design note</a><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. The process group and its backend execute the all-reduces required to keep replicas synchronized.</p>
<ul>
<li><strong>Rank:</strong> The integer identity of a participating process within its process group, as defined in <a href="ch-m4-c02.html#sec-m4-c02-s05">Section 2.5</a>. A common setup uses one process per GPU.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Replica:</strong></span> A full copy of the model parameters on one rank. DDP keeps replicas numerically synchronized by all-reducing gradients.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Local mini-batch:</strong></span> The data shard processed by one rank.</li>
<li><strong>Global batch:</strong> The effective batch across all ranks, usually local mini-batch size multiplied by number of data-parallel ranks and gradient-accumulation steps.</li>
<li><strong>Gradient all-reduce:</strong> Each rank contributes gradients, the gradients are reduced, and every rank receives the same synchronized result.</li>
</ul>
<p>DDP works well when the model fits on each GPU and each step has enough computation to amortize synchronization. It does not reduce parameter memory because every rank stores a full replica. When model state is the memory wall, FSDP or another sharding strategy is needed.</p>
<p>The important DDP state relationship is replication: model state is copied on every rank, while the application partitions the data stream across ranks and each rank processes its assigned shard.</p>
<div id="fig-m4-c13-f02" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The important DDP state relationship is replication: model state is copied on every rank, while the data stream is partitioned across ranks. Replicas begin from compatible parameters. Backward hooks reduce gradient buckets, and every rank applies an equivalent optimizer update after the required synchronization. Framework policy determines whether the reduced result is represented as a sum or average.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m4-c13-f02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m4-c13-f02.jpg" class="img-fluid figure-img" style="width:6.1in" alt="The important DDP state relationship is replication: model state is copied on every rank, while the data stream is partitioned across ranks. Replicas begin from compatible parameters. Backward hooks reduce gradient buckets, and every rank applies an equivalent optimizer update after the required synchronization. Framework policy determines whether the reduced result is represented as a sum or average.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m4-c13-f02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.2: Distributed data parallel training
</figcaption>
</figure>
</div>
<p>DDP’s default initialization synchronizes replicas from rank 0. Backward hooks reduce gradient buckets, and every rank applies an equivalent optimizer update after the required synchronization. With the default reduction, DDP averages gradients across ranks. Custom communication hooks can change that reduction, so the loss normalization and reduction rule must agree.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>In Figure 13.2, “simultaneously” refers to the same logical training step, not synchronized wall-clock updates. “UPDATED MODEL SYNC” describes replicas agreeing after compatible local optimizer updates. Default DDP synchronizes gradients during backward. It does not add a weight-synchronization collective after each optimizer step.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>The implementation pattern is one process per GPU: initialize the process group, map <code>LOCAL_RANK</code> to the local CUDA device, wrap the model with Distributed Data Parallel, shard the data stream with a distributed sampler, and let backward hooks launch gradient all-reduces. The code template follows the bucket-timing explanation so every line can be mapped to the mechanism.</p>
</section>
</section>
<section id="sec-m4-c13-s04" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="sec-m4-c13-s04"><span class="header-section-number">13.3</span> DDP bucket timing and overlap</h2>
<p><a href="ch-m4-c12.html#sec-m4-c12-s09">Section 12.9</a> gives the general overlap rule. In DDP, communication/computation overlap uses the order of backward propagation. Gradients for later layers become ready while earlier layers are still computing backward, so DDP can start all-reducing ready gradient buckets before the full backward pass completes.</p>
<ul>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Gradient bucket:</strong></span> A group of parameter gradients packed together so DDP can launch fewer, larger all-reduces instead of one collective per tensor.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Ready time:</strong></span> The moment all gradients in a bucket have been produced by backward propagation.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Hidden communication:</strong></span> Communication that completes while independent backward computation is still running, so it does not extend step time.</li>
<li><strong>Exposed tail:</strong> The communication left after the last useful computation has finished (<a href="ch-m4-c07.html#sec-m4-c07-s01">Section 7.1</a>). Here it is the part of the gradient all-reduce that no backward work covers.</li>
</ul>
<p>Overlap has a cost. Small buckets may start earlier while reducing bandwidth efficiency because there are more collectives. Large buckets may use bandwidth better while starting later and leaving a larger exposed tail. The useful measurement is whether reducing collective time would still reduce the end-to-end training step.</p>
<p>The DDP reducer turns many parameter gradients into bucket-level communication. A bucket becomes ready when all its gradients are available, but reductions must launch in the same bucket order on every rank. A ready bucket can therefore wait for an earlier bucket. Once that ordering condition is met, its reduction can run while earlier layers in the backward pass are still computing.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>A bucket passes through four ordered steps:</p>
<ol type="1">
<li><strong>Form the buckets:</strong> Group parameter gradients using a configured limit such as <code>bucket_cap_mb</code>. Smaller buckets can start earlier. Larger buckets usually use bandwidth more efficiently.</li>
<li><strong>Mark gradients ready:</strong> Autograd hooks mark each parameter gradient as backward propagation produces it. Parameter order and graph structure determine when every gradient in a bucket is available.</li>
<li><strong>All-reduce launch:</strong> A ready bucket is reduced in the shared bucket order across the data-parallel ranks, usually through NCCL on NVIDIA GPUs. The communication overlaps only while independent backward computation continues.</li>
<li><strong>Exposed tail:</strong> Communication remaining after backward computation finishes directly lengthens the training step.</li>
</ol>
<p>The DDP implementation extends the Section 1.5 supervised loop with three distributed additions: each process owns a rank and its assigned GPU, the data stream is partitioned by rank, and backward propagation triggers gradient communication.</p>
<p>A slow DDP step can still come from local causes such as data loading, forward kernels, backward memory pressure, or optimizer state. Distributed causes add rank skew, all-reduce bandwidth, bucket timing, and topology placement.</p>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: DDP training template</strong></p>
<p>This synthetic template requires a CUDA/NCCL-enabled PyTorch installation and one available GPU per worker. It shows process roles, rank-to-device mapping, sampler behavior, optimizer flow, backward synchronization, and cleanup. The launch command is <code>torchrun --standalone --nproc-per-node=&lt;gpu_count&gt; script.py</code>. A successful run performs two training epochs without printing a loss report. The synthetic dataset and linear model establish the distributed control path. This one-layer model does not demonstrate overlap between multiple gradient buckets. If the dataset length is not divisible by the rank count, the sampler’s default padding repeats some examples to give ranks equal-length streams.</p>
</div>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: DDP training template</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m4-c13-c01"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m4-c13-c01-1"><a href="#lst-m4-c13-c01-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="lst-m4-c13-c01-2"><a href="#lst-m4-c13-c01-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="lst-m4-c13-c01-3"><a href="#lst-m4-c13-c01-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.distributed <span class="im">as</span> dist</span>
<span id="lst-m4-c13-c01-4"><a href="#lst-m4-c13-c01-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="lst-m4-c13-c01-5"><a href="#lst-m4-c13-c01-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch.utils.data <span class="im">import</span> DataLoader, DistributedSampler, TensorDataset</span>
<span id="lst-m4-c13-c01-6"><a href="#lst-m4-c13-c01-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch.nn.parallel <span class="im">import</span> DistributedDataParallel <span class="im">as</span> DDP</span>
<span id="lst-m4-c13-c01-7"><a href="#lst-m4-c13-c01-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m4-c13-c01-8"><a href="#lst-m4-c13-c01-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_one_rank():</span>
<span id="lst-m4-c13-c01-9"><a href="#lst-m4-c13-c01-9" aria-hidden="true" tabindex="-1"></a>    dist.init_process_group(<span class="st">"nccl"</span>)</span>
<span id="lst-m4-c13-c01-10"><a href="#lst-m4-c13-c01-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="lst-m4-c13-c01-11"><a href="#lst-m4-c13-c01-11" aria-hidden="true" tabindex="-1"></a>        local_rank <span class="op">=</span> <span class="bu">int</span>(os.environ[<span class="st">"LOCAL_RANK"</span>])</span>
<span id="lst-m4-c13-c01-12"><a href="#lst-m4-c13-c01-12" aria-hidden="true" tabindex="-1"></a>        torch.cuda.set_device(local_rank)</span>
<span id="lst-m4-c13-c01-13"><a href="#lst-m4-c13-c01-13" aria-hidden="true" tabindex="-1"></a>        device <span class="op">=</span> torch.device(<span class="st">"cuda"</span>, local_rank)</span>
<span id="lst-m4-c13-c01-14"><a href="#lst-m4-c13-c01-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m4-c13-c01-15"><a href="#lst-m4-c13-c01-15" aria-hidden="true" tabindex="-1"></a>        feature_count <span class="op">=</span> <span class="dv">1024</span></span>
<span id="lst-m4-c13-c01-16"><a href="#lst-m4-c13-c01-16" aria-hidden="true" tabindex="-1"></a>        class_count <span class="op">=</span> <span class="dv">100</span></span>
<span id="lst-m4-c13-c01-17"><a href="#lst-m4-c13-c01-17" aria-hidden="true" tabindex="-1"></a>        num_epochs <span class="op">=</span> <span class="dv">2</span></span>
<span id="lst-m4-c13-c01-18"><a href="#lst-m4-c13-c01-18" aria-hidden="true" tabindex="-1"></a>        generator <span class="op">=</span> torch.Generator().manual_seed(<span class="dv">0</span>)</span>
<span id="lst-m4-c13-c01-19"><a href="#lst-m4-c13-c01-19" aria-hidden="true" tabindex="-1"></a>        dataset <span class="op">=</span> TensorDataset(</span>
<span id="lst-m4-c13-c01-20"><a href="#lst-m4-c13-c01-20" aria-hidden="true" tabindex="-1"></a>            torch.randn(<span class="dv">4096</span>, feature_count, generator<span class="op">=</span>generator),</span>
<span id="lst-m4-c13-c01-21"><a href="#lst-m4-c13-c01-21" aria-hidden="true" tabindex="-1"></a>            torch.randint(class_count, (<span class="dv">4096</span>,), generator<span class="op">=</span>generator),</span>
<span id="lst-m4-c13-c01-22"><a href="#lst-m4-c13-c01-22" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="lst-m4-c13-c01-23"><a href="#lst-m4-c13-c01-23" aria-hidden="true" tabindex="-1"></a>        sampler <span class="op">=</span> DistributedSampler(dataset, shuffle<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m4-c13-c01-24"><a href="#lst-m4-c13-c01-24" aria-hidden="true" tabindex="-1"></a>        loader <span class="op">=</span> DataLoader(</span>
<span id="lst-m4-c13-c01-25"><a href="#lst-m4-c13-c01-25" aria-hidden="true" tabindex="-1"></a>            dataset, batch_size<span class="op">=</span><span class="dv">8</span>, sampler<span class="op">=</span>sampler, num_workers<span class="op">=</span><span class="dv">4</span>, pin_memory<span class="op">=</span><span class="va">True</span></span>
<span id="lst-m4-c13-c01-26"><a href="#lst-m4-c13-c01-26" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="lst-m4-c13-c01-27"><a href="#lst-m4-c13-c01-27" aria-hidden="true" tabindex="-1"></a>        model <span class="op">=</span> DDP(nn.Linear(feature_count, class_count).to(device), device_ids<span class="op">=</span>[local_rank])</span>
<span id="lst-m4-c13-c01-28"><a href="#lst-m4-c13-c01-28" aria-hidden="true" tabindex="-1"></a>        loss_fn <span class="op">=</span> nn.CrossEntropyLoss()</span>
<span id="lst-m4-c13-c01-29"><a href="#lst-m4-c13-c01-29" aria-hidden="true" tabindex="-1"></a>        optimizer <span class="op">=</span> torch.optim.AdamW(model.parameters(), lr<span class="op">=</span><span class="fl">3e-4</span>)</span>
<span id="lst-m4-c13-c01-30"><a href="#lst-m4-c13-c01-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m4-c13-c01-31"><a href="#lst-m4-c13-c01-31" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(num_epochs):</span>
<span id="lst-m4-c13-c01-32"><a href="#lst-m4-c13-c01-32" aria-hidden="true" tabindex="-1"></a>            sampler.set_epoch(epoch)</span>
<span id="lst-m4-c13-c01-33"><a href="#lst-m4-c13-c01-33" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> features, labels <span class="kw">in</span> loader:</span>
<span id="lst-m4-c13-c01-34"><a href="#lst-m4-c13-c01-34" aria-hidden="true" tabindex="-1"></a>                features <span class="op">=</span> features.to(device, non_blocking<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m4-c13-c01-35"><a href="#lst-m4-c13-c01-35" aria-hidden="true" tabindex="-1"></a>                labels <span class="op">=</span> labels.to(device, non_blocking<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m4-c13-c01-36"><a href="#lst-m4-c13-c01-36" aria-hidden="true" tabindex="-1"></a>                loss <span class="op">=</span> loss_fn(model(features), labels)</span>
<span id="lst-m4-c13-c01-37"><a href="#lst-m4-c13-c01-37" aria-hidden="true" tabindex="-1"></a>                loss.backward()</span>
<span id="lst-m4-c13-c01-38"><a href="#lst-m4-c13-c01-38" aria-hidden="true" tabindex="-1"></a>                optimizer.step()</span>
<span id="lst-m4-c13-c01-39"><a href="#lst-m4-c13-c01-39" aria-hidden="true" tabindex="-1"></a>                optimizer.zero_grad(set_to_none<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m4-c13-c01-40"><a href="#lst-m4-c13-c01-40" aria-hidden="true" tabindex="-1"></a>    <span class="cf">finally</span>:</span>
<span id="lst-m4-c13-c01-41"><a href="#lst-m4-c13-c01-41" aria-hidden="true" tabindex="-1"></a>        dist.destroy_process_group()</span>
<span id="lst-m4-c13-c01-42"><a href="#lst-m4-c13-c01-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m4-c13-c01-43"><a href="#lst-m4-c13-c01-43" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">"__main__"</span>:</span>
<span id="lst-m4-c13-c01-44"><a href="#lst-m4-c13-c01-44" aria-hidden="true" tabindex="-1"></a>    train_one_rank()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Backward propagation is the key distributed boundary in this template: DDP hooks mark gradient buckets ready and submit their reductions while other backward work may still run. Measure bucket timing, the exposed communication tail, and the slowest rank before changing bucket sizes, rank placement, or the communication backend.</p>
</section>
<section id="sec-m4-c13-s05" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="sec-m4-c13-s05"><span class="header-section-number">13.4</span> Sharding model state</h2>
<p>Fully Sharded Data Parallel (FSDP) supports several sharding strategies. Under <code>FULL_SHARD</code>, parameters, gradients, and optimizer state are sharded across ranks outside their materialized use windows, following the <a href="https://docs.pytorch.org/docs/2.14/fsdp.html">FullyShardedDataParallel documentation</a><a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. Other strategies replicate or retain more state. Full sharding reduces per-GPU memory but introduces parameter all-gather and gradient reduce-scatter around layer execution.</p>
<p>In PyTorch 2.14’s <code>FullyShardedDataParallel</code> API, <code>FULL_SHARD</code> gathers a wrapped unit’s parameters before forward, reshards afterward, gathers again for backward, and reshards after backward. <code>SHARD_GRAD_OP</code> gathers before forward but keeps those full parameters through backward, then reshards them. Both keep optimizer state partitioned and reduce-scatter gradients on synchronized steps. Retaining full parameters removes the second gather but lengthens their memory lifetime. FSDP’s <span class="definition-term" data-custom-style="Definition Term"><strong><code>no_sync()</code> context</strong></span> defers gradient synchronization during accumulation. The first forward-backward pass after leaving the context synchronizes the accumulated gradients. Inside this context, <code>SHARD_GRAD_OP</code> also retains full parameters after backward. These windows refer to the cited <code>ShardingStrategy</code> API, not every API called FSDP.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<section id="sec-m4-c13-s06" class="level3" data-number="13.4.1">
<h3 data-number="13.4.1" class="anchored" data-anchor-id="sec-m4-c13-s06"><span class="header-section-number">13.4.1</span> DeepSpeed and ZeRO implementations</h3>
<p>Zero Redundancy Optimizer (ZeRO) names the staged sharding strategy, following <em>ZeRO: Memory Optimizations Toward Training Trillion Parameter Models</em><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>, while DeepSpeed is a distributed-training framework that implements ZeRO-family state placement together with optimizer, pipeline, and runtime integrations. PyTorch FSDP is a separate framework with selectable sharding strategies. Its <code>FULL_SHARD</code> mode partitions parameters, gradients, and optimizer state.</p>
<p>Framework selection follows the required state placement and collective schedule. Configuration names differ, but memory savings and communication costs follow the same parameters, gradients, optimizer state, all-gather, and reduce-scatter objects.</p>
<p>PyTorch FSDP and DeepSpeed ZeRO Stage 3 are related full-sharding approaches with similar state-placement goals, but they are distinct APIs and implementations with different policies and scheduling behavior. The comparison below therefore follows the parameter, gradient, and optimizer-state lifecycle instead of treating the framework names as interchangeable.</p>
<p>The ZeRO family names three progressively broader state-sharding choices:</p>
<ul>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>ZeRO-1:</strong></span> Shards optimizer state while parameters and gradients remain replicated. The 16 bytes per parameter of <a href="ch-m4-c01.html#sec-m4-c01-s02">Section 1.3</a> become <span class="math inline">\(4+12/N_d\)</span> bytes per rank, where <span class="math inline">\(N_d\)</span> is the number of data-parallel ranks and 12 bytes are the optimizer’s FP32 master copy and two Adam moments.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>ZeRO-2:</strong></span> Also shards gradients, leaving <span class="math inline">\(2+14/N_d\)</span> bytes per parameter per rank. Reduce-scatter timing follows bucket readiness, hooks, overlap, and implementation policy rather than an unconditional immediate layer-by-layer rule.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>ZeRO-3:</strong></span> Also shards parameters outside their materialized use windows, leaving <span class="math inline">\(16/N_d\)</span> bytes per parameter per rank. Implementations may reshard or retain gathered parameters. Temporary full parameters and communication buffers still consume memory.</li>
</ul>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: Model-state memory per GPU under ZeRO</strong></p>
<p><strong>Inputs:</strong> The ZeRO paper’s example model has <span class="math inline">\(7.5\times10^9\)</span> parameters trained with mixed-precision Adam on <span class="math inline">\(N_d=64\)</span> data-parallel GPUs.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> Activations, workspaces, and buffers are excluded.</p>
<div id="tbl-m4-c13-t05" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c13-t05-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.1: Model-state memory per GPU under each ZeRO stage.
</figcaption>
<div aria-describedby="tbl-m4-c13-t05-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Bytes per parameter per GPU</th>
<th>Model state per GPU</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Plain data parallelism</td>
<td>16</td>
<td>120 GB</td>
</tr>
<tr class="even">
<td>ZeRO-1</td>
<td><span class="math inline">\(4+12/64\approx4.19\)</span></td>
<td>31.4 GB</td>
</tr>
<tr class="odd">
<td>ZeRO-2</td>
<td><span class="math inline">\(2+14/64\approx2.22\)</span></td>
<td>16.6 GB</td>
</tr>
<tr class="even">
<td>ZeRO-3</td>
<td><span class="math inline">\(16/64=0.25\)</span></td>
<td>1.9 GB</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Conclusion:</strong> Most of the saving comes from the optimizer state, which is 12 of the 16 bytes. At 64 ranks, sharding the gradients as well reduces 31.4 GB to 16.6 GB, nearly halving what remains. Sharding the parameters makes this persistent model-state estimate fall in proportion to the number of GPUs. The price is communication: ZeRO-3 gathers parameters before they are used, which the paper puts at about 1.5 times the communication volume of plain data parallelism under its communication model.</p>
</div>
<p>The comparison below holds the data-parallel goal fixed and shows which model-state objects remain replicated or become sharded. The final column identifies the communication phase introduced by each broader sharding choice.</p>
<div id="tbl-m4-c13-t01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c13-t01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.2: DDP, ZeRO, and FSDP state placement comparison.
</figcaption>
<div aria-describedby="tbl-m4-c13-t01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Strategy</th>
<th>Parameters</th>
<th>Gradients</th>
<th>Optimizer state</th>
<th>Main timing cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DDP</td>
<td>Replicated</td>
<td>All-reduced and replicated</td>
<td>Replicated</td>
<td>Gradient all-reduce after buckets become ready</td>
</tr>
<tr class="even">
<td>ZeRO-1</td>
<td>Replicated</td>
<td>Replicated</td>
<td>Sharded</td>
<td>Gradient synchronization, local partition update, then distribution of updated parameter partitions to all replicas</td>
</tr>
<tr class="odd">
<td>ZeRO-2</td>
<td>Replicated</td>
<td>Reduce-scattered or sharded</td>
<td>Sharded</td>
<td>Gradient reduce-scatter, local partition update, then distribution of updated parameter partitions to all replicas</td>
</tr>
<tr class="even">
<td>ZeRO-3 / FSDP FULL_SHARD</td>
<td>Sharded outside layer execution</td>
<td>Reduce-scattered and sharded</td>
<td>Sharded</td>
<td>Parameter all-gather before forward/backward layer use plus reduce-scatter after gradients</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Full sharding has separate forward and backward communication phases. Parameters are all-gathered before forward computation and may be resharded afterward. If forward released the full parameters, they are gathered again before backward computation. As gradients become ready, reduce-scatter combines them and leaves each rank with its local shard. Prefetch settings can overlap a future gather with current computation, but they may raise peak memory by materializing parameters earlier.</p>
<p>One full-shard layer follows this communication sequence:</p>
<ol type="1">
<li><strong>Gather before forward:</strong> All-gather parameter shards so the layer can compute. Prefetching too early increases peak memory.</li>
<li><strong>Reshard after forward:</strong> Release or reshard the full parameters according to the selected strategy. Keeping them improves reuse but reduces memory savings.</li>
<li><strong>Gather before backward:</strong> All-gather parameters again when forward released them. Backward prefetch can overlap this transfer with compute while increasing live memory.</li>
<li><strong>Reduce after gradients are ready:</strong> Reduce-scatter gradients and retain each rank’s local shard. Communication that remains after compute becomes the exposed tail.</li>
<li><strong>Update the local parameter shard:</strong> Once the step’s required backward, accumulation, and synchronization are complete, each rank’s optimizer uses its reduced gradient shard and matching optimizer-state shard to update the same parameter indices. This is one step update, not a separate update each time a layer finishes backward.</li>
<li><strong>Gather updated values at next use:</strong> Full sharding keeps the updated parameter partitions on their ranks. The next forward gathers those new partitions when the wrapped unit is needed. Optimizer buffers remain local.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></li>
</ol>
<p>A concrete optimizer update makes the final stage of the sharded cycle visible. <span class="definition-term" data-custom-style="Definition Term"><strong>Stochastic gradient descent (SGD) with momentum</strong></span> is an optimizer that keeps a decaying sum of past gradients and moves parameters against that accumulated direction. Its <strong>momentum buffer</strong> stores that history for each parameter between steps. The example uses this shorter update rule to expose how parameter, gradient, and optimizer-state shards stay aligned.</p>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: From gradient shards to updated parameters</strong></p>
<p>Consider one four-parameter unit in a training step after momentum buffers have already been initialized. Rank 0 stores parameters <span class="math inline">\([1,2]\)</span> and momentum <span class="math inline">\([0.5,-0.5]\)</span> for indices 0 and 1. Rank 1 stores parameters <span class="math inline">\([3,4]\)</span> and momentum <span class="math inline">\([1,-1]\)</span> for indices 2 and 3. A forward all-gather temporarily supplies <span class="math inline">\([1,2,3,4]\)</span> on both ranks. If full parameters are released after forward, a second gather reconstructs the same values for backward. Parameters stay unchanged until the step update.</p>
<p>Suppose backward on equally weighted local data shards produces gradient contributions [1, 2, 3, 4] and [3, 6, 9, 12]. SUM reduce-scatter followed by division by two leaves rank 0 with mean-gradient shard [2, 4] and rank 1 with [6, 8]. The division expresses this example’s mean-loss convention, not an implicit property of SUM.</p>
<p>The momentum SGD update is <span class="math inline">\(v' = 0.9v + g\)</span> followed by <span class="math inline">\(p' = p - 0.1v'\)</span>, where <span class="math inline">\(p\)</span> is a parameter shard, <span class="math inline">\(g\)</span> its mean-gradient shard, and <span class="math inline">\(v\)</span> its existing momentum buffer. The prime denotes the new value. The factor 0.9 retains part of the previous buffer, and the learning rate 0.1 sets the parameter change per unit of new momentum. This omits weight decay, dampening, and Nesterov momentum.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
<div id="tbl-m4-c13-t06" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c13-t06-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.3: New momentum and parameters on each rank.
</figcaption>
<div aria-describedby="tbl-m4-c13-t06-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Rank</th>
<th>New momentum, 0.9v + g</th>
<th>New parameters, p - 0.1v’</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\([0.45+2,-0.45+4]=[2.45,3.55]\)</span></td>
<td><span class="math inline">\([1-0.245,2-0.355]=[0.755,1.645]\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\([0.9+6,-0.9+8]=[6.9,7.1]\)</span></td>
<td><span class="math inline">\([3-0.69,4-0.71]=[2.31,3.29]\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The next forward all-gather supplies [0.755, 1.645, 2.31, 3.29] on both ranks. Each rank retains only its own updated parameter and momentum partitions between full-shard use windows. Adam would retain two moment buffers per parameter and use a different update rule, but the matching of local parameter, gradient, and optimizer-state indices is the same.</p>
<p><strong>Conclusion:</strong> Gradient reduction is followed by a local update and later parameter materialization. Persistent shards and temporary full tensors occupy different storage windows. The values here illustrate that cycle, not measured convergence or runtime performance.</p>
</div>
<p>ZeRO-1 and ZeRO-2 also let each rank update its assigned parameter partition using local optimizer state. They then distribute the updated partitions, for example by all-gather, to restore the full parameter replicas before the next forward. In the example, each replica must receive both [0.755, 1.645] and [2.31, 3.29]. ZeRO-1 keeps the synchronized gradients replicated, whereas ZeRO-2 partitions them as well. Full sharding instead leaves parameters partitioned between their next-use gathers.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
<p>When even sharded model state does not fit, selected state can move to host memory. <span class="definition-term" data-custom-style="Definition Term"><strong>Offload</strong></span> stores that state on the CPU and transfers the values needed by GPU computation. ZeRO-Offload runs optimizer computation on the CPU. The paper also describes an optional one-step delayed update that overlaps CPU optimizer work with GPU computation. This changes which step’s gradients supply the update. In its tested V100 setup, the authors report training models with over 13 billion parameters on one GPU, about ten times their PyTorch baseline, without model changes.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> PyTorch FSDP’s <code>CPUOffload</code> option keeps parameters on the CPU when they are not in use, which also moves the gradients to the CPU and runs the optimizer step there.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a> Offload trades GPU memory for PCIe traffic (<a href="ch-m4-c02.html#sec-m4-c02-s05">Section 2.5</a>) and CPU optimizer time. It is useful when the capacity gain outweighs those costs for the workload.</p>
<p>Full sharding reduces persistent per-rank model state by adding timed parameter gathers and gradient reduce-scatters. Its benefit depends on peak-memory relief compared with exposed communication and temporary materialization. The next question is whether splitting layer computation or the layer sequence is a better fit when state sharding alone cannot meet the target.</p>
</section>
</section>
<section id="sec-m4-c13-s07" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="sec-m4-c13-s07"><span class="header-section-number">13.5</span> Model-parallel strategies</h2>
<p>Model parallelism is an option when replicated or state-sharded training cannot meet the memory, throughput, or model-size target on one GPU group. The selection question is which model object to split and how often ranks must exchange the resulting partial state. The following subsections first establish the execution layouts, then quantify activation memory, locate the collectives created by a tensor-parallel linear layer, and finally divide the sequence dimension for long contexts.</p>
<section id="sec-m4-c13-s08" class="level3" data-number="13.5.1">
<h3 data-number="13.5.1" class="anchored" data-anchor-id="sec-m4-c13-s08"><span class="header-section-number">13.5.1</span> Model-parallel execution and Megatron-LM</h3>
<p>Model parallelism splits one model execution across ranks. Tensor parallelism divides work inside a layer, as in <em>Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism</em><a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a>. Pipeline parallelism assigns layer ranges to stages, as in <em>GPipe: Easy Scaling with Micro-Batch Pipeline Parallelism</em><a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a>. Expert parallelism routes token representations to specific expert ranks, as in <em>GShard: Scaling Giant Models with Conditional Computation and Automatic Sharding</em><a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a>. The performance question is where each layout forces ranks to exchange partial results.</p>
<p>Two common forward-path partitions show where collective communication appears:</p>
<ul>
<li>MLP block sharding: In the three-matrix gated MLP counted in <a href="ch-m4-c08.html#sec-m4-c08-s07">Section 8.4</a>, matching columns of the gate and up projections belong to the same rank. That rank applies the activation and elementwise gate locally before its row-parallel down projection. The trace below defines the intermediate and the final sum.</li>
<li>Self-Attention Block Sharding: The Query, Key, and Value projections are sharded column-parallel, keeping attention head computations local to each GPU. The attention Output projection is sharded row-parallel, requiring a single All-Reduce before the residual connection.</li>
</ul>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: A gated MLP across two ranks</strong></p>
<p>The goal is to reproduce a full MLP forward output while dividing its intermediate channels. This example uses a bias-free <strong>SwiGLU feed-forward layer</strong>, a gated MLP whose Swish-1 activation and three-matrix operation are defined in <em>GLU Variants Improve Transformer</em>.<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a> The partition below applies the column/row split to that operation. It is a forward-only mathematical trace, not a complete training program or a claim that the original Megatron-LM paper used SwiGLU.</p>
<p>Both ranks receive the same <span class="math inline">\(X\)</span> of shape <span class="math inline">\([n,d]\)</span>, with <span class="math inline">\(n\)</span> token rows and <span class="math inline">\(d\)</span> hidden features. Let <span class="math inline">\(h\)</span> be an even intermediate width and <span class="math inline">\(i\)</span> be rank 0 or 1. Each rank holds gate and up matrices <span class="math inline">\(W_{g,i}\)</span> and <span class="math inline">\(W_{u,i}\)</span>, each shaped <span class="math inline">\([d,h/2]\)</span>, with matching intermediate-channel indices. Its down-projection shard <span class="math inline">\(V_i\)</span> has shape <span class="math inline">\([h/2,d]\)</span>.</p>
<p>The local projections are <span class="math inline">\(G_i=XW_{g,i}\)</span> and <span class="math inline">\(U_i=XW_{u,i}\)</span>, both shaped <span class="math inline">\([n,h/2]\)</span>. The <span class="definition-term" data-custom-style="Definition Term"><strong>sigmoid linear unit (SiLU)</strong></span>, also called Swish-1, applies <span class="math inline">\(\operatorname{SiLU}(a)=a/(1+e^{-a})\)</span> to each scalar element. The gated intermediate is <span class="math inline">\(Y_i=\operatorname{SiLU}(G_i)\odot U_i\)</span>, where <span class="math inline">\(\odot\)</span> multiplies matching elements, so <span class="math inline">\(Y_i\)</span> also has shape <span class="math inline">\([n,h/2]\)</span>. Each rank then computes <span class="math inline">\(Z_i=Y_iV_i\)</span> of shape <span class="math inline">\([n,d]\)</span>. SUM all-reduce returns <span class="math inline">\(Z=Z_0+Z_1\)</span> with shape <span class="math inline">\([n,d]\)</span> on both ranks. Because the gate acts independently on matching local channels, no intermediate gather is needed for this layout.</p>
<p>For a numerical trace, let <span class="math inline">\(n=1\)</span>, <span class="math inline">\(d=2\)</span>, <span class="math inline">\(h=4\)</span>, and <span class="math inline">\(X=[1,0]\)</span>. These small dimensions illustrate the operation, not a production expansion ratio. The matrices below list rows in brackets:</p>
<div id="tbl-m4-c13-t07" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c13-t07-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.4: Sharded MLP matrices held by each rank.
</figcaption>
<div aria-describedby="tbl-m4-c13-t07-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Gate matrix</th>
<th>Up matrix</th>
<th>Down matrix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\([[1,-1],[0,0]]\)</span></td>
<td><span class="math inline">\([[2,3],[0,0]]\)</span></td>
<td><span class="math inline">\([[1,0],[0,1]]\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\([[0,2],[0,0]]\)</span></td>
<td><span class="math inline">\([[4,1],[0,0]]\)</span></td>
<td><span class="math inline">\([[1,1],[1,-1]]\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Rank 0 obtains <span class="math inline">\(G_0=[1,-1]\)</span> and <span class="math inline">\(U_0=[2,3]\)</span>. Applying SiLU gives approximately <span class="math inline">\([0.731059,-0.268941]\)</span>, so <span class="math inline">\(Y_0=[1.462117,-0.806824]\)</span> and <span class="math inline">\(Z_0=Y_0\)</span>. Rank 1 obtains <span class="math inline">\(G_1=[0,2]\)</span> and <span class="math inline">\(U_1=[4,1]\)</span>, giving <span class="math inline">\(Y_1=[0,1.761594]\)</span> and <span class="math inline">\(Z_1=[1.761594,-1.761594]\)</span>. The all-reduce returns approximately <span class="math inline">\(Z=[3.223711,-2.568418]\)</span> to each rank. The unsharded calculation concatenates the gate/up columns and stacks the down-matrix rows, producing the same sum apart from floating-point rounding.</p>
<p><strong>Conclusion:</strong> The gate is a nonlinear, elementwise step between projections. Its output can stay local because both branches use the same channel partition. The down projection produces partial hidden vectors that must be added before the residual path uses them. This trace assumes replicated input, equal channel shards, and no sequence parallelism (<a href="#sec-m4-c13-s14">Section 13.5.4</a>). Backward has additional gradient dependencies, and other layouts can change the collective choice.</p>
</div>
<p>The key performance fact is where the collective is placed. Tensor parallelism tries to keep intermediate slices local through several operations, then synchronizes only when the full hidden vector is needed by the residual path, normalization, or the next block.</p>
<div id="tbl-m4-c13-t02" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c13-t02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.5: Forward tensor-parallel all-reduce placement with replicated input and output, complete local heads, and no sequence parallelism.
</figcaption>
<div aria-describedby="tbl-m4-c13-t02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Transformer subpath</th>
<th>Local tensor-parallel work</th>
<th>Collective placement</th>
<th>Why the placement matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MLP gate/up projection</td>
<td>Matching column shards produce local G and U, then Y = SiLU(G) times U elementwise</td>
<td>No immediate forward all-reduce</td>
<td>Activation and gating stay local because both branches use matching channels</td>
</tr>
<tr class="even">
<td>MLP down projection</td>
<td>Row-parallel input channels; each rank computes a partial hidden output</td>
<td>All-reduce after the down projection</td>
<td>Partial sums must be combined before the residual connection</td>
</tr>
<tr class="odd">
<td>Attention Q/K/V projection</td>
<td>Complete attention heads are assigned to ranks in this layout</td>
<td>Often no immediate all-reduce</td>
<td>Attention for local heads can proceed without synchronizing every projection</td>
</tr>
<tr class="even">
<td>Attention output projection</td>
<td>Each rank computes a partial contribution back to hidden dimension</td>
<td>All-reduce before block output is complete</td>
<td>The next residual or layer needs the full hidden vector</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Pipeline parallelism assigns contiguous layer ranges to K stages and moves each micro-batch through them in order.</p>
<div id="fig-m4-c13-f03" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Pipeline parallelism partitions the model by layers rather than by tensor dimensions. Each stage holds a contiguous range of layers. The key trade-off is utilization versus bubbles. Micro-batches keep stages busy, but activation movement and scheduling complexity increase.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m4-c13-f03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m4-c13-f03.jpg" class="img-fluid figure-img" style="width:6.1in" alt="Pipeline parallelism partitions the model by layers rather than by tensor dimensions. Each stage holds a contiguous range of layers. The key trade-off is utilization versus bubbles. Micro-batches keep stages busy, but activation movement and scheduling complexity increase.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m4-c13-f03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.3: Pipeline parallelism
</figcaption>
</figure>
</div>
<p>During forward fill, later stages wait for their first input. During forward drain, earlier stages finish their forward work first. Backward work moves in the opposite direction: in Figure 13.4’s final backward drain, the last forward stage finishes first and the first forward stage finishes last. These idle stage intervals form the <span class="definition-term" data-custom-style="Definition Term"><strong>pipeline bubble</strong></span>. Figure 13.4 shows the occupied and idle intervals for a GPipe schedule.</p>
<div id="fig-m4-c13-f04" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four pipeline stages process four micro-batches forward, then backward. Later stages wait during forward fill. In the final backward drain, the last forward stage finishes first and the first forward stage finishes last. Idle stage intervals form the pipeline bubble. More micro-batches reduce the relative fill and drain time under balanced-stage assumptions. Their activation-memory effect depends on whether global batch size or micro-batch size is fixed and on the schedule's retention policy.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m4-c13-f04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m4-c13-f04.jpg" class="img-fluid figure-img" style="width:6.1in" alt="Four pipeline stages process four micro-batches forward, then backward. Later stages wait during forward fill. In the final backward drain, the last forward stage finishes first and the first forward stage finishes last. Idle stage intervals form the pipeline bubble. More micro-batches reduce the relative fill and drain time under balanced-stage assumptions. Their activation-memory effect depends on whether global batch size or micro-batch size is fixed and on the schedule's retention policy.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m4-c13-f04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.4: GPipe micro-batch schedule and pipeline bubble
</figcaption>
</figure>
</div>
<div class="publisher-clarification-note" data-custom-style="Clarification Note">
<p><strong>Reading the pipeline schedule</strong></p>
<p>Figure 13.4 is a schematic GPipe schedule, not a measured timing trace. Pipeline stages appear on the vertical axis and schedule time on the horizontal axis. Labeled blocks show forward and backward work for each micro-batch. Empty regions show fill, drain, or waiting time. Under the balanced-stage assumptions of Equation 13.1, increasing the number of micro-batches reduces the first-order fill/drain fraction. The activation-memory effect is schedule-dependent: with a fixed micro-batch size, additional in-flight work can extend activation lifetimes, while with a fixed global batch, increasing the micro-batch count usually reduces each micro-batch’s size. Check peak memory for the actual schedule and retention policy.</p>
<p>F1 and B1 refer to the forward and backward work for the same micro-batch, and likewise for indices 2 through 4. Throughout this step, the stages use unchanged parameters. B4, B3, B2, and B1 add contributions to the step’s accumulated gradients, normalized for the intended batch loss as described in <a href="ch-m4-c07.html#sec-m4-c07-s03">Section 7.3</a>. They do not trigger four separate parameter updates. After the step’s required backward work and any gradient synchronization finish, each stage’s optimizer updates its parameters once, before the next step’s forward work uses them.<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a></p>
</div>
<p>With M equal-duration micro-batches and balanced stages, following <em>GPipe: Easy Scaling with Micro-Batch Pipeline Parallelism</em><a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a>, the first-order bubble fraction is:</p>
<p><span id="eq-m4-c13-e01"><span class="math display">\[
\text{bubble}_{\text{fraction}} = \frac{K - 1}{M + K - 1}
\tag{13.1}\]</span></span></p>
<p>Here K is the number of pipeline stages and M is the number of micro-batches per global step. This first-order GPipe fill-and-drain model assumes balanced stages, equal micro-batch times, and no additional communication or scheduling delay. Increasing M reduces the relative fill/drain bubble under those assumptions, while more micro-batches may keep additional activation state live.</p>
<div class="publisher-clarification-note" data-custom-style="Clarification Note">
<p><strong>Worked calculation - pipeline bubble</strong></p>
<p><strong>Inputs:</strong> Use K = 4 pipeline stages and M = 8 micro-batches.</p>
<p><strong>Substitution:</strong> (4 - 1) / (8 + 4 - 1) = 3 / 11.</p>
<p><strong>Result:</strong> The first-order bubble fraction is about 27.3 percent before stage imbalance, communication, or scheduling overhead.</p>
<p><strong>Change to test:</strong> With M = 32, the estimate becomes 3 / 35, or about 8.6 percent. The activation-memory change depends on whether the global batch or micro-batch size is held fixed and on the schedule’s retention policy.</p>
</div>
<ul>
<li><strong>Pipeline bubble:</strong> Idle stage time caused by pipeline fill, drain, imbalance, or waiting for neighboring stages.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>GPipe:</strong></span> A pipeline-parallel training schedule that uses micro-batches to keep stage devices busier than a single large batch would.</li>
<li><strong>Micro-batch:</strong> A smaller slice of the global batch that can be advanced independently through pipeline stages.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Stage balance:</strong></span> Pipeline throughput is limited by the slowest stage, so layer partitioning matters as much as the communication path.</li>
</ul>
<p>Mixture of Experts (MoE) changes the distributed problem again. A model contains many expert modules, but each token is routed to only a subset. This sparse expert approach follows <em>GShard: Scaling Giant Models with Conditional Computation and Automatic Sharding</em><a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a>, which shards experts across devices with learned top-2 style routing. Expert parallelism places different experts on different GPUs. The router dispatches token representations to the devices holding the selected experts, and the outputs must be gathered back into the original token order. This often creates all-to-all communication pressure, load-balancing risk, and sensitivity to router skew. The dispatch and combine path described below assumes one all-to-all for dispatch and one for combine. Actual runtimes vary in grouping, overlap, and collective schedule.</p>
<ul>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>MoE:</strong></span> Mixture of Experts: a sparse model structure with many expert submodules where each token activates only selected experts.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Expert parallelism:</strong></span> Placement strategy where experts are distributed across GPUs and tokens are routed to the devices that hold their selected experts.</li>
<li><strong>All-to-all pressure:</strong> Each rank may send different token slices to many other ranks and receive different slices back, which can dominate sparse-model performance.</li>
<li><strong>Communication condition:</strong> Sparse expert execution reduces the arithmetic performed per token relative to activating every expert. That reduction yields a speedup only when router imbalance, token dispatch, and communication do not consume the time saved.</li>
</ul>
<p>One expert-parallel layer follows a concrete state path: the router assigns one or more expert destinations to each token. Each rank packs token representations by destination. An all-to-all dispatch moves those slices to the expert-owning ranks. Local experts compute their outputs. A second all-to-all returns the results. The runtime restores original token order and combines the selected expert outputs using their router weights before the next model operation. Imbalanced destinations can make the busiest expert or rank determine the expert phase’s completion time and delay dependent computation.</p>
<p>The table compares the distributed layouts. Its FSDP rows use PyTorch 2.14 FullyShardedDataParallel outside <code>no_sync</code>. <a href="#sec-m4-c13-s05">Section 13.4</a> explains the storage windows.</p>
<div id="tbl-m4-c13-t03" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c13-t03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.6: Distributed parallelism comparison. FSDP rows use PyTorch 2.14 FullyShardedDataParallel outside no_sync; see Section 13.4 for storage windows.
</figcaption>
<div aria-describedby="tbl-m4-c13-t03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Strategy</th>
<th>What is split</th>
<th>Memory effect</th>
<th>Communication pattern</th>
<th>Best fit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DDP</td>
<td>Data batch</td>
<td>Replicates parameters, gradients, and optimizer state</td>
<td>Gradient all-reduce</td>
<td>Model fits per GPU</td>
</tr>
<tr class="even">
<td>FSDP FULL_SHARD</td>
<td>Parameters, gradients, optimizer state</td>
<td>Parameter shards between forward/backward use windows; gradient and optimizer shards</td>
<td>Parameter all-gather before forward and backward; gradient reduce-scatter</td>
<td>Model state exceeds one GPU</td>
</tr>
<tr class="odd">
<td>FSDP SHARD_GRAD_OP</td>
<td>Gradients, optimizer state, and parameters outside computation</td>
<td>Full parameters from pre-forward gather through backward, then resharded; gradient and optimizer state sharded</td>
<td>Pre-forward parameter all-gather and gradient reduce-scatter; no second parameter gather before backward</td>
<td>Full parameter windows fit; retaining them avoids a backward gather</td>
</tr>
<tr class="even">
<td>Tensor parallelism</td>
<td>Layer tensors</td>
<td>Shards layer parameters; each rank keeps local activations and optimizer state</td>
<td>Frequent layer collectives such as all-reduce and all-gather</td>
<td>Large layers on fast fabric</td>
</tr>
<tr class="odd">
<td>Pipeline parallelism</td>
<td>Layer sequence</td>
<td>Keeps one contiguous parameter stage plus activations for active micro-batches</td>
<td>Forward activation transfers and backward activation-gradient transfers between stages</td>
<td>Deep models across devices</td>
</tr>
<tr class="even">
<td>Expert parallelism</td>
<td>Experts and token routes</td>
<td>Stores local expert parameters and optimizer state</td>
<td>All-to-all token routing</td>
<td>Mixture-of-Experts models</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-m4-c13-s09" class="level3" data-number="13.5.2">
<h3 data-number="13.5.2" class="anchored" data-anchor-id="sec-m4-c13-s09"><span class="header-section-number">13.5.2</span> Activation-memory derivation for GPT-style training</h3>
<p>Large-model training often hits the activation wall before the parameter wall. Parameters are static with respect to batch size and sequence length, but saved activations grow with both. In GPT-style transformers, attention score tensors can also scale quadratically with sequence length if the implementation materializes them.</p>
<p>Saved activation storage follows from two common tensor shapes. Let <span class="math inline">\(B\)</span> be local micro-batch size, <span class="math inline">\(T\)</span> sequence length, <span class="math inline">\(d\)</span> hidden width, <span class="math inline">\(H\)</span> attention-head count, <span class="math inline">\(L\)</span> local transformer layers, and <span class="math inline">\(b\)</span> bytes per stored element.</p>
<ul>
<li>A hidden-sized tensor has <span class="math inline">\(BTd\)</span> elements and occupies <span class="math inline">\(BTdb\)</span> bytes per layer.</li>
<li>A materialized dense attention matrix has <span class="math inline">\(BHT^2\)</span> elements and occupies <span class="math inline">\(BHT^2b\)</span> bytes per layer.</li>
</ul>
<p>If each layer saves <span class="math inline">\(n_{\text{hidden}}\)</span> hidden-sized tensors and <span class="math inline">\(n_{\text{score}}\)</span> attention-matrix-sized tensors, their combined payload is approximately</p>
<p><span class="math display">\[ A \approx Lb\left(n_{\text{hidden}}BTd+n_{\text{score}}BHT^2\right). \]</span></p>
<p>For an illustrative calculation, assume <span class="math inline">\(n_{\text{hidden}}=16\)</span>, <span class="math inline">\(n_{\text{score}}=1\)</span>, <span class="math inline">\(B=1\)</span>, <span class="math inline">\(T=2048\)</span>, <span class="math inline">\(d=4096\)</span>, <span class="math inline">\(H=32\)</span>, <span class="math inline">\(L=10\)</span>, and <span class="math inline">\(b=2\)</span> bytes. This uses the same coarse hidden-tensor count as Chapter 7 so the two estimates can be compared.</p>
<p><span class="math display">\[ A \approx 10\cdot2\left(16\cdot2048\cdot4096+32\cdot2048^2\right) =5{,}368{,}709{,}120\ \text{bytes}=5\ \text{GiB}. \]</span></p>
<p>These are assumed tensor counts, not measurements of a particular model. Actual counts depend on the layer implementation, backward algorithm, recomputation policy, and fused kernels. The estimate excludes weights, gradients, optimizer state, temporary workspaces, and allocator overhead. Measure peak allocation before using it as a device-memory budget.</p>
<p>Several techniques change the saved tensors. Activation checkpointing discards selected forward intermediates and recomputes them during backward. FlashAttention-style kernels avoid materializing the full attention matrix. Sequence and context parallelism divide the sequence dimension across GPUs (<a href="#sec-m4-c13-s14">Section 13.5.4</a>). The exact per-rank saving depends on which tensors each implementation keeps or reconstructs.</p>
<p>This derivation explains why FSDP or tensor parallelism alone can leave training memory limited by activations. FSDP shards model state, while activations remain tied to local micro-batch and layer execution unless activation checkpointing, sequence parallelism, FlashAttention, or smaller micro-batches reduce them.</p>
</section>
<section id="sec-m4-c13-s10" class="level3" data-number="13.5.3">
<h3 data-number="13.5.3" class="anchored" data-anchor-id="sec-m4-c13-s10"><span class="header-section-number">13.5.3</span> Column-wise and row-wise tensor-parallel communication</h3>
<p>Column-wise and row-wise tensor parallelism describe where a linear layer is split and where the ranks must communicate. The distinction matters because splitting output channels and splitting input channels place collective operations at different points in the transformer block.</p>
<p>Megatron-LM-style tensor parallelism chooses where communication occurs by pairing column-parallel and row-parallel projections inside transformer blocks, following <em>Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism</em><a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a>. A column-parallel linear layer splits output channels. Each rank computes its own output slice from the full input, so the forward edge can avoid an immediate all-reduce. The backward pass accumulates gradients for each local weight shard and may need to combine input gradients depending on how the following layer is arranged. Exact collectives depend on the layer and sequence-parallel configuration.</p>
<p>A row-parallel linear layer splits input channels. Each rank computes a partial output from its input slice and weight shard, then the partial outputs must be summed. In the replicated-output layout used above, that summation is an all-reduce in the forward path. Sequence-parallel layouts can instead reduce-scatter the output. The need to communicate inside each layer is why tensor parallelism is usually kept inside fast NVLink or NVSwitch domains.</p>
<p>The placement intuition is: keep attention heads or MLP intermediate channels local as long as possible, then reduce only when the full hidden vector is needed by a residual connection, normalization, or the next block boundary. This reduces communication frequency compared with naively synchronizing after every projection.</p>
<p>In the forward MLP trace in <a href="#sec-m4-c13-s08">Section 13.5.1</a>, the residual computation waits for the tensor-parallel sum. Backward likewise must combine partial input gradients before dependent earlier work uses them. Overlap is possible only with computation that does not need the pending result and with a schedule that permits both operations to run. If training also uses data parallelism, a separate group synchronizes corresponding parameter-shard replicas with gradient buckets. Those buckets serve the data-parallel group and do not remove the tensor-parallel layer dependencies.<a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a><a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a></p>
</section>
<section id="sec-m4-c13-s14" class="level3" data-number="13.5.4">
<h3 data-number="13.5.4" class="anchored" data-anchor-id="sec-m4-c13-s14"><span class="header-section-number">13.5.4</span> Sequence and context parallelism for long contexts</h3>
<p>Tensor parallelism divides the weights of a layer, but every tensor-parallel rank still holds activations for the whole sequence in the operations it does not split, and attention state grows with the sequence. At long context lengths, that per-GPU state becomes the limit. Two methods divide the sequence dimension itself.</p>
<ul>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Sequence parallelism</strong></span> splits the sequence across the tensor-parallel ranks for the operations that tensor parallelism leaves replicated, such as layer normalization and dropout. The forward all-reduce of tensor parallelism becomes a reduce-scatter and an all-gather around those regions. Together with selective recomputation, Korthikanti et al.&nbsp;report a 5 times reduction in activation memory while almost eliminating the need to recompute activations.<a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a></li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Context parallelism</strong></span> splits the sequence through attention as well. In a simple block partition, each rank holds one block of the sequence’s queries, keys, and values. Ring Attention circulates key and value blocks and can overlap their transfer with attention on a block already present. Its blockwise method preserves the attention operation, apart from floating-point rounding, and can scale the supported sequence length with device count. Full overlap requires enough computation per block relative to communication time.<a href="#fn25" class="footnote-ref" id="fnref25" role="doc-noteref"><sup>25</sup></a></li>
</ul>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: A 128k-token sequence on eight GPUs</strong></p>
<p><strong>Inputs:</strong> A full-sequence forward attention pass with Llama 3 8B-like shapes (32 layers, 32 query heads, 8 KV heads, <span class="math inline">\(d_h=128\)</span>, BF16), one sequence of 131,072 tokens, and context parallelism over 8 GPUs, so each holds a block of 16,384 tokens. The link rate of 400 GB/s and compute rate of 989 TFLOP/s are illustrative inputs to the estimate, not measurements. This is a training/prefill-sized query block, not a one-token decode step.</p>
<p><strong>Memory:</strong> Storing keys and values for the full sequence across all 32 layers requires 16 GiB with these shapes (<a href="ch-m4-c09.html#sec-m4-c09-s08">Section 9.7</a>). Partitioning that payload evenly gives 2 GiB per GPU. This counts the resident KV shards only, not queries, outputs, received KV buffers, backward state, or other saved activations. In training, these tensors are activations rather than a persistent decode cache.</p>
<p><strong>Overlap:</strong> In one layer, one KV block is <span class="math inline">\(2\times16{,}384\times8\times128\times2\approx67\)</span> MB, which takes about 0.17 ms at the assumed 400 GB/s, excluding startup and contention. Dense attention from a 16,384-token query block to one 16,384-token KV block takes <span class="math inline">\(4\times16{,}384^2\times32\times128\approx4.4\times10^{12}\)</span> FLOPs, about 4.4 ms at the assumed 989 TFLOP/s. For contiguous causal blocks, an earlier KV block contributes a full block of attention, the diagonal block contributes roughly half, and a future block is fully masked. Useful compute and rank balance therefore depend on block order and the causal schedule.</p>
<p><strong>Conclusion:</strong> For a block pair with substantial attention work, this estimate leaves room to hide the next transfer behind computation. It does not establish full overlap for the complete causal pass or divide all training memory by eight. A profile must include startup, temporary buffers, rank imbalance, and the actual attention schedule. Small blocks, slow links, and one-token decode can expose communication even when this long-block estimate looks favorable. A fast scale-up domain reduces that risk (<a href="ch-m4-c12.html#sec-m4-c12-s11">Section 12.11</a>).</p>
</div>
</section>
</section>
<section id="sec-m4-c13-s15" class="level2" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="sec-m4-c13-s15"><span class="header-section-number">13.6</span> Combining and sizing parallelism</h2>
<p>Large training runs often combine strategies because each has a different cost. Plain data parallelism replicates model state on every GPU. Tensor parallelism adds per-layer collectives that become more expensive when they cross slower links. Pipeline parallelism introduces fill and drain time. For independent data-, tensor-, and pipeline-parallel axes, GPU count is the product of their degrees, an arrangement often called 3D parallelism. An independent context-parallel axis adds another factor. In Megatron Bridge, expert parallelism changes expert layers without changing the mapping of other layers. Do not treat every configured parallelism degree as an independent GPU-count factor. Check the runtime’s group definitions.<a href="#fn26" class="footnote-ref" id="fnref26" role="doc-noteref"><sup>26</sup></a></p>
<p>The choice of degrees follows the communication frequencies of <a href="ch-m4-c12.html#sec-m4-c12-s11">Section 12.11</a>. In their tested layouts, Narayanan et al.&nbsp;found that tensor parallelism is effective within a multi-GPU server, that pipeline parallelism is needed for larger models across servers, and that poor combinations of the two can cost up to 2 times in throughput even with fast inter-server links. Their composition performed training iterations for a one-trillion-parameter model at 502 petaFLOP/s on 3,072 GPUs, 52 percent of theoretical peak.<a href="#fn27" class="footnote-ref" id="fnref27" role="doc-noteref"><sup>27</sup></a> A practical sizing sequence follows from those findings:</p>
<ol type="1">
<li><strong>Tensor degree:</strong> Choose the smallest degree, up to the size of one NVLink domain, at which one layer’s weights and activations fit.</li>
<li><strong>Pipeline degree:</strong> Add stages across servers until the model state fits per GPU, and choose enough micro-batches to keep the bubble small (<a href="#sec-m4-c13-s08">Section 13.5.1</a>).</li>
<li><strong>Data degree:</strong> Use the remaining GPUs as data-parallel replicas, with ZeRO or FSDP sharding across them if memory is still tight.</li>
<li><strong>Check:</strong> Recompute memory per GPU, bubble fraction, and gradient-synchronization volume, then confirm with a profile.</li>
</ol>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: A 70B model on 64 GPUs</strong></p>
<p><strong>Inputs:</strong> Consider training a 70-billion-parameter model with mixed-precision Adam on 8 servers of 8 H100 80 GB GPUs. Its model state is <span class="math inline">\(16\times70\times10^9=1{,}120\)</span> GB (<a href="ch-m4-c01.html#sec-m4-c01-s02">Section 1.3</a>), far beyond one GPU.</p>
<p><strong>Layout:</strong> Tensor degree 8 inside each server, pipeline degree 2 across servers, and data degree 4 (<span class="math inline">\(8\times2\times4=64\)</span>), with ZeRO-1 sharding of the optimizer state across the 4 replicas.</p>
<p><strong>Memory per GPU:</strong> Assuming evenly sized tensor and pipeline partitions, each GPU holds <span class="math inline">\(70\times10^9/(8\times2)\approx4.4\)</span> billion parameters. Weights and gradients take <span class="math inline">\(4\times4.375\times10^9=17.5\)</span> GB, and the sharded optimizer state takes <span class="math inline">\(12\times4.375\times10^9/4\approx13.1\)</span> GB, 30.6 GB in total. Using 80 GB as the planning capacity leaves about 49 GB before activations, workspaces, communication buffers, allocator overhead, and partition imbalance are counted.</p>
<p><strong>Pipeline bubble:</strong> With 16 micro-batches per step, the balanced GPipe fill-and-drain estimate is <span class="math inline">\((2-1)/(16+2-1)\approx5.9\)</span> percent. Other schedules and unequal stage times change the result.</p>
<p><strong>Gradient synchronization:</strong> Each GPU’s tensor/pipeline partition has <span class="math inline">\(4.375\times10^9\times2=8.75\)</span> GB of gradients. A schedule with one ring gradient all-reduce over the 4 data-parallel replicas per optimizer step sends about <span class="math inline">\(2\times(3/4)\times8.75\approx13.1\)</span> GB per GPU across servers. That is a gradient-only estimate: a ZeRO-1 schedule using full gradient all-reduce also distributes updated parameter partitions. An optimized schedule can instead reduce gradients to their optimizer owners and gather updated parameters, replacing the full gradient all-reduce. Count the operations the runtime actually uses before estimating total traffic. Overlap with backward can reduce the exposed part (<a href="ch-m4-c12.html#sec-m4-c12-s09">Section 12.9</a>).<a href="#fn28" class="footnote-ref" id="fnref28" role="doc-noteref"><sup>28</sup></a></p>
<p><strong>Conclusion:</strong> The layout keeps tensor-parallel collectives on NVLink. Cross-server traffic includes data-parallel synchronization and pipeline activations plus their backward gradients for each micro-batch. A fully sharded alternative, tensor degree 8 with FSDP across 8 data-parallel replicas, reduces persistent model state to 17.5 GB per GPU under the same byte accounting, but adds cross-server parameter gathers around wrapped-unit use and temporary full-parameter storage. The profile, not the memory arithmetic alone, decides between them.</p>
</div>
</section>
<section id="sec-m4-c13-s11" class="level2" data-number="13.7">
<h2 data-number="13.7" class="anchored" data-anchor-id="sec-m4-c13-s11"><span class="header-section-number">13.7</span> Distributed inference and serving</h2>
<p>Distributed inference uses the same links, backends, and collective libraries as distributed training, while the user-facing metric changes. The goal includes latency, Time To First Token (TTFT), Time Per Output Token (TPOT), tail behavior, serving capacity, and tokens per second.</p>
<section id="sec-m4-c13-s12" class="level3" data-number="13.7.1">
<h3 data-number="13.7.1" class="anchored" data-anchor-id="sec-m4-c13-s12"><span class="header-section-number">13.7.1</span> Distributed serving frameworks</h3>
<p>A distributed serving framework combines request routing and cache ownership with replica, tensor-parallel, or pipeline-parallel worker groups. vLLM and SGLang can coordinate multi-GPU serving groups. TensorRT-LLM and related deployment stacks can execute compiled sharded engines on supported configurations. The framework choice follows the placement strategy and topology rather than defining them.</p>
<p>The critical ownership questions are which worker group holds the model shard, which group owns each request’s KV cache, which collectives lie on every decode step, and whether routing preserves that locality across replicas.</p>
<p>A serving design combines three decisions: how each model is split within a worker group, how requests are routed among groups, and where each request’s KV cache remains. Together they determine whether communication occurs at admission, during prefill, inside every layer, or for every generated token.</p>
<p>A common serving strategy keeps frequent collectives inside a node and scales across nodes by replicating serving groups. This avoids making every token depend on a slow cross-node path. When the model is too large for one node, the system must balance model sharding, cache locality, batch scheduling, and network cost.</p>
<ul>
<li><strong>Tensor-parallel serving:</strong> Splits layer math across GPUs. It helps when one layer is too large or too slow for one GPU, but it may put collectives in the per-layer or per-token path, so fast intra-node links matter.</li>
<li><strong>Pipeline-parallel serving:</strong> Assigns different layer ranges to different devices. It can fit deeper models, but stage imbalance, micro-batch scheduling, and activation transfer can increase tail latency.</li>
<li><strong>Replica groups:</strong> Multiple complete serving instances route requests among them. This is often simpler than cross-node sharding when the model fits per group, and it can preserve low Time Per Output Token (TPOT).</li>
<li><strong>Router and cache locality:</strong> The router should avoid moving an active request away from the devices holding its KV cache unless the benefit outweighs the transfer cost.</li>
<li><strong>Cross-node sharding:</strong> A capacity or throughput option when one node is insufficient or another placement goal justifies it. It carries higher decode-latency risk when each token depends on cross-node communication with little independent work to hide the cost.</li>
</ul>
<p>Distributed inference can be slower than single-node inference when the model already fits and per-token communication dominates. A single optimized replica may produce lower TPOT than a cross-node sharded model because decode has little independent work to hide network latency. The correct scale-out design depends on whether the bottleneck is memory capacity, throughput, Time To First Token (TTFT), TPOT, or tail latency.</p>
<div id="tbl-m4-c13-t04" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c13-t04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.7: Training versus inference tensor parallelism.
</figcaption>
<div aria-describedby="tbl-m4-c13-t04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>Training tensor parallelism</th>
<th>Inference tensor parallelism</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Primary metric</td>
<td>Step throughput and model flops utilization</td>
<td>TTFT, TPOT, tail latency, throughput within SLA</td>
</tr>
<tr class="even">
<td>Batch shape</td>
<td>Large micro-batches can amortize collectives</td>
<td>Decode may have one token per sequence, so per-layer collectives are more exposed</td>
</tr>
<tr class="odd">
<td>Overlap opportunity</td>
<td>Layer collectives overlap only independent work; dependent forward outputs and backward input gradients must wait. DDP buckets belong to a separate data-parallel group</td>
<td>The next token or layer often needs the collective result immediately</td>
</tr>
<tr class="even">
<td>State pressure</td>
<td>Activations, gradients, optimizer state, and parameters</td>
<td>Weights plus KV-cache placement and per-request cache locality</td>
</tr>
<tr class="odd">
<td>Topology rule</td>
<td>Cross-node TP needs enough compute per exchange or sufficiently fast links to keep exposed communication acceptable; overlap helps where dependencies permit it</td>
<td>Per-token TP should usually stay inside the fastest scale-up domain</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-m4-c13-s16" class="level3" data-number="13.7.2">
<h3 data-number="13.7.2" class="anchored" data-anchor-id="sec-m4-c13-s16"><span class="header-section-number">13.7.2</span> Serving mixture-of-experts models</h3>
<p>A mixture-of-experts model separates the parameters it stores from the parameters each token uses. DeepSeek-V2, for example, has 236 billion parameters in total, of which 21 billion are activated for each token.<a href="#fn29" class="footnote-ref" id="fnref29" role="doc-noteref"><sup>29</sup></a> A deployment must make all required expert weights available, while each token uses only its selected experts and shared components. Assuming all weights remain on GPUs in BF16, their payload is 472 GB, a capacity-only lower bound of six 80 GB GPUs before KV cache, workspaces, replication, or placement constraints. The coarse <span class="math inline">\(2P\)</span> estimate gives about <span class="math inline">\(2\times21\times10^9=42\)</span> GFLOP per token for parameter-related forward work, compared with 472 GFLOP when all 236B parameters are active (<a href="ch-m4-c01.html#sec-m4-c01-s03">Section 1.4</a>). This excludes attention’s context-dependent work and routing overhead. The active count alone therefore cannot predict memory needs or the serving bottleneck.</p>
<ul>
<li><strong>Expert parallelism in serving:</strong> Experts are spread across GPUs. In the dispatch/combine layout of <a href="#sec-m4-c13-s08">Section 13.5.1</a>, a layer routes token representations to remote experts and returns their outputs through two logical exchanges. An engine may implement these with all-to-all collectives or another schedule, and local routes need no cross-GPU transfer. Frequent remote routing favors a fast scale-up domain when capacity permits (<a href="ch-m4-c12.html#sec-m4-c12-s11">Section 12.11</a>).</li>
<li><strong>Tokens per expert:</strong> A step with <span class="math inline">\(B\)</span> tokens and top-<span class="math inline">\(k\)</span> routing over <span class="math inline">\(E\)</span> experts has an average of <span class="math inline">\(Bk/E\)</span> token assignments per expert before capacity limits. With 64 experts, top-2 routing, and 256 tokens, that average is 8 rows. Actual counts depend on the router. Eight-row multiplications often have little weight reuse and can be memory-bound (<a href="ch-m4-c02.html#sec-m4-c02-s08">Section 2.8</a>); dtype, matrix dimensions, caching, and grouped kernels affect the measured limit. Larger decode batches can raise rows per expert and arithmetic intensity when routing remains balanced.</li>
<li><strong>Load imbalance:</strong> The busiest expert or rank can set the expert phase’s completion time when its work lies on the critical path. For its top-1 routing, Switch Transformer sizes each expert’s buffer as the tokens per batch divided by the number of experts, times a <span class="definition-term" data-custom-style="Definition Term"><strong>capacity factor</strong></span>, and passes tokens that exceed it to the next layer through the residual connection without expert computation.<a href="#fn30" class="footnote-ref" id="fnref30" role="doc-noteref"><sup>30</sup></a> Top-<span class="math inline">\(k\)</span> engines may use different capacity accounting. Dropping an expert computation can change the model’s output, so a serving deployment checks how its engine handles overflow.</li>
</ul>
</section>
</section>
<section id="sec-m4-c13-s13" class="level2" data-number="13.8">
<h2 data-number="13.8" class="anchored" data-anchor-id="sec-m4-c13-s13"><span class="header-section-number">13.8</span> KV-cache locality in distributed serving</h2>
<p>KV-cache locality is the serving-design property that keeps an active request near the GPU group holding its key-value cache blocks. It matters because decode repeatedly reads old KV blocks and appends new ones. Moving an active request away from its cache can add a large transfer or force recomputation.</p>
<p>The common pattern is sticky placement: once a request has built substantial KV state on a serving group, the router prefers keeping later decode steps on that group unless the load-balancing benefit outweighs transfer or recomputation cost. This is a serving-scheduler property, not an attention-kernel or hardware-cache optimization.</p>
<ul>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Sticky placement:</strong></span> An active request remains on the worker group that owns its current KV blocks.</li>
<li><strong>Locality-aware routing:</strong> New-request routing considers both load and whether useful prefix or cache state already exists on a worker.</li>
<li><strong>Cache migration:</strong> Moving KV blocks between worker groups. For load balancing, the expected benefit should outweigh peer, host, or network transfer cost. Prefill/decode handoff or worker evacuation can require movement for other reasons.</li>
</ul>
<div class="publisher-clarification-note" data-custom-style="Clarification Note">
<p><strong>KV-cache locality scenario</strong></p>
<p><strong>Setup:</strong> A request has built an 8k-token KV cache on serving group A. Group B is less busy, but it does not hold that request’s cache blocks.</p>
<p><strong>Migration cost:</strong> Moving the next decode step to group B requires cache-block transfer, host or network staging, or recomputation of cache state.</p>
<p><strong>Better pattern:</strong> Keep decode on group A, route new requests to group B, or migrate only when the expected future benefit exceeds the cache-transfer and tail-latency cost.</p>
<p><strong>Evidence:</strong> Watch TPOT, cache-migration counters, prefix-cache hit rate, per-worker queue depth, and tail latency rather than only average GPU utilization.</p>
</div>
<p>The measured hot path determines the placement. Replicated groups can scale request throughput without adding per-token cross-node collectives when the model fits per group. A sharded group can solve capacity or parallel-compute limits, but its per-layer or per-token communication must be included in TTFT, TPOT, throughput, and tail-latency measurements.</p>
<p>The strategy follows from the object that must be split, the resulting payload and communication frequency, and a topology appropriate for that traffic. More GPUs help when they make the workload fit or improve the chosen throughput or latency target after communication, synchronization, and other distributed overheads are included.</p>
<p>This completes the path from one-device execution to distributed training and serving. Appendix A collects the formulas, software controls, compatibility checks, practice questions, and source map needed to apply the same reasoning during implementation and review.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>PyTorch. (2026). <em>Distributed Data Parallel</em>. Versioned v2.14 design note at <a href="https://docs.pytorch.org/docs/2.14/notes/ddp.html">https://docs.pytorch.org/docs/2.14/notes/ddp.html</a>, created 2026-05-16 and updated 2026-05-16, describing implementation state as of v1.4. Supports Reducer gradient buckets with <code>bucket_cap_mb</code>, autograd hooks, per-bucket async all-reduce with mean gradients, same-order all-reduce across ranks, and overlap of collectives with backward compute. Limit: input sharding is done by the application, for example with a distributed sampler; DDP synchronizes gradients but does not partition inputs by itself.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>PyTorch. (2026). <em>Distributed Data Parallel</em>. Versioned v2.14 design note at <a href="https://docs.pytorch.org/docs/2.14/notes/ddp.html">https://docs.pytorch.org/docs/2.14/notes/ddp.html</a>, created 2026-05-16 and updated 2026-05-16, describing implementation state as of v1.4. Supports Reducer gradient buckets with <code>bucket_cap_mb</code>, autograd hooks, per-bucket async all-reduce with mean gradients, same-order all-reduce across ranks, and overlap of collectives with backward compute. Limit: input sharding is done by the application, for example with a distributed sampler; DDP synchronizes gradients but does not partition inputs by itself.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>PyTorch. (2026). <em>Distributed Data Parallel</em>. Versioned v2.14 design note at <a href="https://docs.pytorch.org/docs/2.14/notes/ddp.html">https://docs.pytorch.org/docs/2.14/notes/ddp.html</a>, created 2026-05-16 and updated 2026-05-16, describing implementation state as of v1.4. Supports Reducer gradient buckets with <code>bucket_cap_mb</code>, autograd hooks, per-bucket async all-reduce with mean gradients, same-order all-reduce across ranks, and overlap of collectives with backward compute. Limit: input sharding is done by the application, for example with a distributed sampler; DDP synchronizes gradients but does not partition inputs by itself.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>PyTorch. (2026). <em>Distributed Data Parallel</em>. Versioned v2.14 design note at <a href="https://docs.pytorch.org/docs/2.14/notes/ddp.html">https://docs.pytorch.org/docs/2.14/notes/ddp.html</a>, created 2026-05-16 and updated 2026-05-16, describing implementation state as of v1.4. Supports Reducer gradient buckets with <code>bucket_cap_mb</code>, autograd hooks, per-bucket async all-reduce with mean gradients, same-order all-reduce across ranks, and overlap of collectives with backward compute. Limit: input sharding is done by the application, for example with a distributed sampler; DDP synchronizes gradients but does not partition inputs by itself.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>PyTorch. (2026). <em>FullyShardedDataParallel</em>, <code>ShardingStrategy</code> entries. Versioned v2.14 documentation at <a href="https://docs.pytorch.org/docs/2.14/fsdp.html">https://docs.pytorch.org/docs/2.14/fsdp.html</a>, created 2022-02-02 and updated 2026-05-12. Supports the <code>FULL_SHARD</code> and <code>SHARD_GRAD_OP</code> storage windows, gathers, gradient reduce-scatter, and local optimizer updates described here. <code>SHARD_GRAD_OP</code> retains full parameters after backward inside <code>no_sync()</code>. Limit: this wrapper’s API contract does not establish the behavior of every FSDP API or achieved step time.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>PyTorch. (2026). <em>FullyShardedDataParallel</em>, <code>ShardingStrategy</code> entries. Versioned v2.14 documentation at <a href="https://docs.pytorch.org/docs/2.14/fsdp.html">https://docs.pytorch.org/docs/2.14/fsdp.html</a>, created 2022-02-02 and updated 2026-05-12. Supports the <code>FULL_SHARD</code> and <code>SHARD_GRAD_OP</code> storage windows, gathers, gradient reduce-scatter, and local optimizer updates described here. <code>SHARD_GRAD_OP</code> retains full parameters after backward inside <code>no_sync()</code>. Limit: this wrapper’s API contract does not establish the behavior of every FSDP API or achieved step time.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Rajbhandari, S., Rasley, J., Ruwase, O., &amp; He, Y. (2020). <em>ZeRO: Memory Optimizations Toward Training Trillion Parameter Models</em>. Preprint at <a href="https://arxiv.org/abs/1910.02054">https://arxiv.org/abs/1910.02054</a> (<a href="https://doi.org/10.48550/arXiv.1910.02054">DOI</a>), v2 submitted 2019-10-07, v3 revised 2020-05-13. Supports staged sharding with Stage 1 for optimizer states, Stage 2 adding gradients, and Stage 3 adding parameters outside materialized use windows. The paper gives per-rank model-state memory of 4 + K/N_d, 2 + 14/N_d, and 16/N_d bytes per parameter with K = 12, the 7.5B-parameter, 64-GPU example of 120, 31.4, 16.6, and 1.9 GB, and a 1.5x communication volume for parameter partitioning. Limit: memory and scaling results depend on model, device count, and implementation policy for gathering and resharding.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Rajbhandari, S., Rasley, J., Ruwase, O., &amp; He, Y. (2020). <em>ZeRO: Memory Optimizations Toward Training Trillion Parameter Models</em>. Preprint at <a href="https://arxiv.org/abs/1910.02054">https://arxiv.org/abs/1910.02054</a> (<a href="https://doi.org/10.48550/arXiv.1910.02054">DOI</a>), v2 submitted 2019-10-07, v3 revised 2020-05-13. Supports staged sharding with Stage 1 for optimizer states, Stage 2 adding gradients, and Stage 3 adding parameters outside materialized use windows. The paper gives per-rank model-state memory of 4 + K/N_d, 2 + 14/N_d, and 16/N_d bytes per parameter with K = 12, the 7.5B-parameter, 64-GPU example of 120, 31.4, 16.6, and 1.9 GB, and a 1.5x communication volume for parameter partitioning. Limit: memory and scaling results depend on model, device count, and implementation policy for gathering and resharding.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>PyTorch. (2026). <em>FullyShardedDataParallel</em>, <code>ShardingStrategy</code> entries. Versioned v2.14 documentation at <a href="https://docs.pytorch.org/docs/2.14/fsdp.html">https://docs.pytorch.org/docs/2.14/fsdp.html</a>, created 2022-02-02 and updated 2026-05-12. Supports the <code>FULL_SHARD</code> and <code>SHARD_GRAD_OP</code> storage windows, gathers, gradient reduce-scatter, and local optimizer updates described here. <code>SHARD_GRAD_OP</code> retains full parameters after backward inside <code>no_sync()</code>. Limit: this wrapper’s API contract does not establish the behavior of every FSDP API or achieved step time.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>PyTorch. (2026). <em>SGD</em>. Versioned v2.14 API documentation at <a href="https://docs.pytorch.org/docs/2.14/generated/torch.optim.SGD.html">https://docs.pytorch.org/docs/2.14/generated/torch.optim.SGD.html</a>. Supports the momentum-buffer recurrence and parameter update. The illustration assumes existing buffers and excludes weight decay, dampening, and Nesterov momentum. It does not illustrate Adam’s update or distributed optimizer implementation details.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Rajbhandari, S., Rasley, J., Ruwase, O., &amp; He, Y. (2020). <em>ZeRO: Memory Optimizations Toward Training Trillion Parameter Models</em>. Preprint at <a href="https://arxiv.org/abs/1910.02054">https://arxiv.org/abs/1910.02054</a> (<a href="https://doi.org/10.48550/arXiv.1910.02054">DOI</a>), v2 submitted 2019-10-07, v3 revised 2020-05-13. Supports staged sharding with Stage 1 for optimizer states, Stage 2 adding gradients, and Stage 3 adding parameters outside materialized use windows. The paper gives per-rank model-state memory of 4 + K/N_d, 2 + 14/N_d, and 16/N_d bytes per parameter with K = 12, the 7.5B-parameter, 64-GPU example of 120, 31.4, 16.6, and 1.9 GB, and a 1.5x communication volume for parameter partitioning. Limit: memory and scaling results depend on model, device count, and implementation policy for gathering and resharding.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Ren, J., Rajbhandari, S., Aminabadi, R. Y., Ruwase, O., Yang, S., Zhang, M., Li, D., &amp; He, Y. (2021). <em>ZeRO-Offload: Democratizing Billion-Scale Model Training</em>. USENIX ATC 2021. <a href="https://arxiv.org/abs/2101.06840">arXiv:2101.06840</a>. Supports offloading data and compute to the CPU, a fast CPU optimizer whose step can overlap GPU compute through a one-step delayed parameter update, and training models with over 13 billion parameters on a single GPU, a 10x increase over PyTorch, without model changes. Limit: throughput depends on CPU speed and PCIe bandwidth.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>PyTorch. (2026). <em>FullyShardedDataParallel</em>, <code>CPUOffload</code> (v2.14 documentation). <a href="https://docs.pytorch.org/docs/2.14/fsdp.html">https://docs.pytorch.org/docs/2.14/fsdp.html</a>. Supports that <code>offload_params=True</code> offloads parameters to the CPU when they are not involved in computation, which also offloads gradients so that the optimizer step runs on the CPU. Limit: the page documents behavior, not the resulting step time.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>Shoeybi, M., Patwary, M., Puri, R., LeGresley, P., Casper, J., &amp; Catanzaro, B. (2019). <em>Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism</em>. Preprint at <a href="https://arxiv.org/abs/1909.08053">https://arxiv.org/abs/1909.08053</a> (<a href="https://doi.org/10.48550/arXiv.1909.08053">DOI</a>), v1 submitted 2019-09-17, v4 revised 2020-03-13. Supports intra-layer model parallelism with column-parallel and row-parallel linear layers separated by a small number of collectives, orthogonal to pipeline parallelism. Limit: exact collective placement depends on layer and sequence-parallel configuration; reported PetaFLOP and scaling efficiency apply to tested 8.3 billion parameter setups on 512 GPUs.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>Huang, Y., Cheng, Y., Bapna, A., Firat, O., Chen, M. X., Chen, D., Lee, H., Ngiam, J., Le, Q. V., Wu, Y., &amp; Chen, Z. (2019). <em>GPipe: Easy Scaling with Micro-Batch Pipeline Parallelism</em>. v5 HTML at <a href="https://arxiv.org/html/1811.06965v5">https://arxiv.org/html/1811.06965v5</a>, abstract page at <a href="https://arxiv.org/abs/1811.06965">https://arxiv.org/abs/1811.06965</a> (<a href="https://doi.org/10.48550/arXiv.1811.06965">DOI</a>), v1 submitted 2018-11-16, v5 revised 2019-07-25. Supports dividing a batch into micro-batches across partitioned layer stages and the first-order bubble overhead of order (K minus 1) divided by (M plus K minus 1) under balanced equal-duration assumptions, with negligible overhead reported when M is at least 4 times K. Limit: estimate omits imbalance, communication, and scheduling delay; more micro-batches can extend activation lifetimes.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>Lepikhin, D., et al.&nbsp;(2020). <em>GShard: Scaling Giant Models with Conditional Computation and Automatic Sharding</em>. Preprint at <a href="https://arxiv.org/abs/2006.16668">https://arxiv.org/abs/2006.16668</a> (<a href="https://doi.org/10.48550/arXiv.2006.16668">DOI</a>), v1 submitted 2020-06-30. Supports sparsely gated Mixture-of-Experts Transformer layers with top-2 style routing, expert sharding across devices, and sublinear scaling of computation with capacity, demonstrated beyond 600 billion parameters on TPU v3 systems. Limit: dispatch and combine grouping, overlap, and collective schedule vary by runtime; the guide illustration assumes one dispatch and one combine all-to-all.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>Shazeer, N. (2020). <em>GLU Variants Improve Transformer</em>. arXiv:2002.05202v1, Section 2, equations 5-6. <a href="https://arxiv.org/html/2002.05202v1">https://arxiv.org/html/2002.05202v1</a>. Supports the bias-free three-matrix SwiGLU operation with a Swish-1 gate. The two-rank partition and numerical values are a teaching derivation of that operation, not performance results from the paper. This is the same work cited for sizing in Chapter 8.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>Huang, Y., Cheng, Y., Bapna, A., Firat, O., Chen, M. X., Chen, D., Lee, H., Ngiam, J., Le, Q. V., Wu, Y., &amp; Chen, Z. (2019). <em>GPipe: Easy Scaling with Micro-Batch Pipeline Parallelism</em>. v5 HTML at <a href="https://arxiv.org/html/1811.06965v5">https://arxiv.org/html/1811.06965v5</a>, abstract page at <a href="https://arxiv.org/abs/1811.06965">https://arxiv.org/abs/1811.06965</a> (<a href="https://doi.org/10.48550/arXiv.1811.06965">DOI</a>), v1 submitted 2018-11-16, v5 revised 2019-07-25. Supports dividing a batch into micro-batches across partitioned layer stages and the first-order bubble overhead of order (K minus 1) divided by (M plus K minus 1) under balanced equal-duration assumptions, with negligible overhead reported when M is at least 4 times K. Limit: estimate omits imbalance, communication, and scheduling delay; more micro-batches can extend activation lifetimes.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>Huang, Y., Cheng, Y., Bapna, A., Firat, O., Chen, M. X., Chen, D., Lee, H., Ngiam, J., Le, Q. V., Wu, Y., &amp; Chen, Z. (2019). <em>GPipe: Easy Scaling with Micro-Batch Pipeline Parallelism</em>. v5 HTML at <a href="https://arxiv.org/html/1811.06965v5">https://arxiv.org/html/1811.06965v5</a>, abstract page at <a href="https://arxiv.org/abs/1811.06965">https://arxiv.org/abs/1811.06965</a> (<a href="https://doi.org/10.48550/arXiv.1811.06965">DOI</a>), v1 submitted 2018-11-16, v5 revised 2019-07-25. Supports dividing a batch into micro-batches across partitioned layer stages and the first-order bubble overhead of order (K minus 1) divided by (M plus K minus 1) under balanced equal-duration assumptions, with negligible overhead reported when M is at least 4 times K. Limit: estimate omits imbalance, communication, and scheduling delay; more micro-batches can extend activation lifetimes.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>Lepikhin, D., et al.&nbsp;(2020). <em>GShard: Scaling Giant Models with Conditional Computation and Automatic Sharding</em>. Preprint at <a href="https://arxiv.org/abs/2006.16668">https://arxiv.org/abs/2006.16668</a> (<a href="https://doi.org/10.48550/arXiv.2006.16668">DOI</a>), v1 submitted 2020-06-30. Supports sparsely gated Mixture-of-Experts Transformer layers with top-2 style routing, expert sharding across devices, and sublinear scaling of computation with capacity, demonstrated beyond 600 billion parameters on TPU v3 systems. Limit: dispatch and combine grouping, overlap, and collective schedule vary by runtime; the guide illustration assumes one dispatch and one combine all-to-all.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p>Shoeybi, M., Patwary, M., Puri, R., LeGresley, P., Casper, J., &amp; Catanzaro, B. (2019). <em>Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism</em>. Preprint at <a href="https://arxiv.org/abs/1909.08053">https://arxiv.org/abs/1909.08053</a> (<a href="https://doi.org/10.48550/arXiv.1909.08053">DOI</a>), v1 submitted 2019-09-17, v4 revised 2020-03-13. Supports intra-layer model parallelism with column-parallel and row-parallel linear layers separated by a small number of collectives, orthogonal to pipeline parallelism. Limit: exact collective placement depends on layer and sequence-parallel configuration; reported PetaFLOP and scaling efficiency apply to tested 8.3 billion parameter setups on 512 GPUs.<a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22"><p>Shoeybi, M., Patwary, M., Puri, R., LeGresley, P., Casper, J., &amp; Catanzaro, B. (2019). <em>Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism</em>. Preprint at <a href="https://arxiv.org/abs/1909.08053">https://arxiv.org/abs/1909.08053</a> (<a href="https://doi.org/10.48550/arXiv.1909.08053">DOI</a>), v1 submitted 2019-09-17, v4 revised 2020-03-13. Supports intra-layer model parallelism with column-parallel and row-parallel linear layers separated by a small number of collectives, orthogonal to pipeline parallelism. Limit: exact collective placement depends on layer and sequence-parallel configuration; reported PetaFLOP and scaling efficiency apply to tested 8.3 billion parameter setups on 512 GPUs.<a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23"><p>PyTorch. (2026). <em>Distributed Data Parallel</em>. Versioned v2.14 design note at <a href="https://docs.pytorch.org/docs/2.14/notes/ddp.html">https://docs.pytorch.org/docs/2.14/notes/ddp.html</a>, created 2026-05-16 and updated 2026-05-16, describing implementation state as of v1.4. Supports Reducer gradient buckets with <code>bucket_cap_mb</code>, autograd hooks, per-bucket async all-reduce with mean gradients, same-order all-reduce across ranks, and overlap of collectives with backward compute. Limit: input sharding is done by the application, for example with a distributed sampler; DDP synchronizes gradients but does not partition inputs by itself.<a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24"><p>Korthikanti, V., Casper, J., Lym, S., McAfee, L., Andersch, M., Shoeybi, M., &amp; Catanzaro, B. (2022). <em>Reducing Activation Recomputation in Large Transformer Models</em>. <a href="https://arxiv.org/abs/2205.05198">arXiv:2205.05198</a>. Supports sequence parallelism and selective activation recomputation used with tensor parallelism, reducing activation memory by 5x and almost eliminating recomputation in the paper’s models up to one trillion parameters. Limit: the savings depend on the model and the recomputation policy.<a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn25"><p>Liu, H., Zaharia, M., &amp; Abbeel, P. (2023). <em>Ring Attention with Blockwise Transformers for Near-Infinite Context</em>. <a href="https://arxiv.org/abs/2310.01889">arXiv:2310.01889</a>. Supports distributing long sequences across devices with blockwise attention and feed-forward computation, fully overlapping key-value block communication with computation, and sequences up to device count times longer without approximation. Limit: full overlap requires enough computation per block relative to link speed.<a href="#fnref25" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn26"><p>NVIDIA. (n.d.). <em>Parallelisms Guide</em> (Megatron Bridge documentation), Data Parallel Size Calculation and Expert Parallelism. Retrieved September 28, 2026, from <a href="https://docs.nvidia.com/nemo/megatron-bridge/0.4.1/parallelisms.html">https://docs.nvidia.com/nemo/megatron-bridge/0.4.1/parallelisms.html</a>. The data degree uses world size divided by tensor, pipeline, and context degrees. Expert parallelism applies to expert layers without changing the parallel mapping of other layers. The caution against multiplying every configured degree follows from distinguishing independent axes; this page does not specify expert/data-parallel rank membership.<a href="#fnref26" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn27"><p>Narayanan, D., et al.&nbsp;(2021). <em>Efficient Large-Scale Language Model Training on GPU Clusters Using Megatron-LM</em>. SC21. <a href="https://arxiv.org/abs/2104.04473">arXiv:2104.04473</a>. Supports composing tensor, pipeline, and data parallelism. In the paper’s tested layouts, tensor parallelism is effective within a multi-GPU server, pipeline parallelism is needed for larger models, poor combinations cost up to 2x in throughput, and the composition reached 502 petaFLOP/s on 3,072 GPUs (52 percent of peak) for a one-trillion-parameter model. Limit: the sizing sequence in Section 13.6 is engineering guidance derived from these findings.<a href="#fnref27" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn28"><p>Rajbhandari, S., Rasley, J., Ruwase, O., &amp; He, Y. (2020). <em>ZeRO: Memory Optimizations Toward Training Trillion Parameter Models</em>. Preprint at <a href="https://arxiv.org/abs/1910.02054">https://arxiv.org/abs/1910.02054</a> (<a href="https://doi.org/10.48550/arXiv.1910.02054">DOI</a>), v2 submitted 2019-10-07, v3 revised 2020-05-13. Supports staged sharding with Stage 1 for optimizer states, Stage 2 adding gradients, and Stage 3 adding parameters outside materialized use windows. The paper gives per-rank model-state memory of 4 + K/N_d, 2 + 14/N_d, and 16/N_d bytes per parameter with K = 12, the 7.5B-parameter, 64-GPU example of 120, 31.4, 16.6, and 1.9 GB, and a 1.5x communication volume for parameter partitioning. Limit: memory and scaling results depend on model, device count, and implementation policy for gathering and resharding.<a href="#fnref28" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn29"><p>DeepSeek-AI. (2024). <em>DeepSeek-V2: A Strong, Economical, and Efficient Mixture-of-Experts Language Model</em>. <a href="https://arxiv.org/abs/2405.04434">arXiv:2405.04434</a>. Supports 236B total parameters with 21B activated per token. Limit: the memory and FLOP figures in Section 13.7.2 are derived from these counts.<a href="#fnref29" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn30"><p>Fedus, W., Zoph, B., &amp; Shazeer, N. (2022). <em>Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity</em>. Journal of Machine Learning Research, 23(120), 1-39. <a href="https://jmlr.org/papers/v23/21-0998.html">Journal article</a>; <a href="https://arxiv.org/abs/2101.03961">arXiv:2101.03961</a>. Supports expert capacity = (tokens per batch / number of experts) x capacity factor, and dropped tokens passing to the next layer through the residual connection. Limit: the paper describes training, and inference engines handle overflow in their own ways.<a href="#fnref30" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch-m4-c12.html" class="pagination-link" aria-label="GPU Communication">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">GPU Communication</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../appendices/ch-m4-app-a.html" class="pagination-link" aria-label="Reference Material">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Reference Material</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>