<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; GPU Hardware and Memory – Advanced LLM Performance Engineering</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch-m4-c03.html" rel="next">
<link href="../chapters/ch-m4-c01.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5c9691461893454a086f8fd2bcb3ff91.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-i.html">Part I: Fundamentals</a></li><li class="breadcrumb-item"><a href="../chapters/ch-m4-c02.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">GPU Hardware and Memory</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Advanced LLM Performance Engineering</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Advanced LLM Performance Engineering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/ch-m4-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction and Learning Path</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part I: Fundamentals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">LLM Workloads and Performance Limits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c02.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">GPU Hardware and Memory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Software to CUDA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Triton and Custom Kernels</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Performance Models and Profiling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Compilation and Runtime</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part II: Training and Inference Workloads</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Training and Precision</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference Workloads</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Decode and KV Cache</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Serving Engines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Performance Experiments</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part III: Communication and Distributed Systems</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">GPU Communication</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m4-c13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Distributed Training and Serving</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/ch-m4-app-a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Reference Material</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/ch-m4-app-c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-m4-c02-s01" id="toc-sec-m4-c02-s01" class="nav-link active" data-scroll-target="#sec-m4-c02-s01"><span class="header-section-number">2.1</span> CPU and GPU strengths</a></li>
  <li><a href="#sec-m4-c02-s02" id="toc-sec-m4-c02-s02" class="nav-link" data-scroll-target="#sec-m4-c02-s02"><span class="header-section-number">2.2</span> GPU chip structure</a></li>
  <li><a href="#sec-m4-c02-s03" id="toc-sec-m4-c02-s03" class="nav-link" data-scroll-target="#sec-m4-c02-s03"><span class="header-section-number">2.3</span> Memory hierarchy</a></li>
  <li><a href="#sec-m4-c02-s04" id="toc-sec-m4-c02-s04" class="nav-link" data-scroll-target="#sec-m4-c02-s04"><span class="header-section-number">2.4</span> Tensor cores and shape alignment</a></li>
  <li><a href="#sec-m4-c02-s05" id="toc-sec-m4-c02-s05" class="nav-link" data-scroll-target="#sec-m4-c02-s05"><span class="header-section-number">2.5</span> Intra-node interconnects</a></li>
  <li><a href="#sec-m4-c02-s06" id="toc-sec-m4-c02-s06" class="nav-link" data-scroll-target="#sec-m4-c02-s06"><span class="header-section-number">2.6</span> Interconnect hierarchy beyond HBM</a></li>
  <li><a href="#sec-m4-c02-s07" id="toc-sec-m4-c02-s07" class="nav-link" data-scroll-target="#sec-m4-c02-s07"><span class="header-section-number">2.7</span> Hardware limits on software design</a></li>
  <li><a href="#sec-m4-c02-s08" id="toc-sec-m4-c02-s08" class="nav-link" data-scroll-target="#sec-m4-c02-s08"><span class="header-section-number">2.8</span> Work, bytes, and time</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-i.html">Part I: Fundamentals</a></li><li class="breadcrumb-item"><a href="../chapters/ch-m4-c02.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">GPU Hardware and Memory</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-ch-m4-c02" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">GPU Hardware and Memory</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="publisher-purpose">
<p>Explain how GPU execution units, the memory hierarchy, and interconnects determine the cost of moving and processing model tensors.</p>
</div>
<p>A GPU can execute transformer operations quickly only when enough parallel work reaches its arithmetic units and reused data stays close to them. This chapter follows tensors from registers and shared memory through L2 and HBM, then across links between GPUs and servers, so later optimizations can be tied to the hardware resource they use.</p>
<p>A GPU combines device-wide memory and cache with many <span class="definition-term" data-custom-style="Definition Term"><strong>Streaming Multiprocessors (SMs)</strong></span> (the GPU’s independent processing units, <a href="#sec-m4-c02-s02">Section 2.2</a>), each containing local execution and storage resources.</p>
<div id="fig-m4-c02-f01" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two GPU devices each contain HBM, shared L2 cache, and Streaming Multiprocessors. One SM is expanded into registers, shared memory, warp scheduling, and Tensor Cores. NVLink joins device boundaries. Section labels identify chapter 2 section map: 2.1 - CPU and GPU strengths; 2.2 - GPU chip structure; 2.3 - Memory hierarchy; 2.4 - Tensor cores and shape alignment; 2.5 - Intra-node interconnects; 2.6 - Interconnect hierarchy beyond HBM; 2.7 - Hardware limits on software design; 2.8 - Work, bytes, and time.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m4-c02-f01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m4-c02-f01.png" class="img-fluid figure-img" style="width:6.25in" alt="Two GPU devices each contain HBM, shared L2 cache, and Streaming Multiprocessors. One SM is expanded into registers, shared memory, warp scheduling, and Tensor Cores. NVLink joins device boundaries. Section labels identify chapter 2 section map: 2.1 - CPU and GPU strengths; 2.2 - GPU chip structure; 2.3 - Memory hierarchy; 2.4 - Tensor cores and shape alignment; 2.5 - Intra-node interconnects; 2.6 - Interconnect hierarchy beyond HBM; 2.7 - Hardware limits on software design; 2.8 - Work, bytes, and time.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m4-c02-f01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: GPU resources are nested within a device, while NVLink connects device boundaries.
</figcaption>
</figure>
</div>
<p>High Bandwidth Memory (HBM) and the <span class="definition-term" data-custom-style="Definition Term"><strong>L2 cache</strong></span> (an on-chip cache shared by all SMs) serve the whole device. Registers, shared memory, <span class="definition-term" data-custom-style="Definition Term"><strong>warp</strong></span> scheduling (the SM’s rotation among groups of 32 threads), and Tensor Cores belong inside an SM. The second device makes the boundary explicit: <span class="definition-term" data-custom-style="Definition Term"><strong>NVLink</strong></span> (NVIDIA’s direct GPU-to-GPU link) carries peer traffic between GPUs rather than connecting an SM directly to another device’s cache.</p>
<p>This chapter supplies the hardware facts behind two of the levers in <a href="ch-m4-c01.html#sec-m4-c01-s10">Section 1.6.1</a>: move fewer bytes, because the memory hierarchy decides what reuse costs, and use faster hardware paths, because Tensor Cores reach their peak rate only for the shapes and formats they support.</p>
<section id="sec-m4-c02-s01" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="sec-m4-c02-s01"><span class="header-section-number">2.1</span> CPU and GPU strengths</h2>
<p>CPUs emphasize latency and branch-heavy control flow. They devote more chip area to caches and complex execution logic. GPUs emphasize throughput. They devote more area to arithmetic units and hardware scheduling of many simple <span class="definition-term" data-custom-style="Definition Term"><strong>threads</strong></span> (independent sequences of instructions, each working on its own data). To use a GPU effectively, a workload must expose enough parallel work to keep those arithmetic units busy and regular enough memory access to use the bandwidth efficiently. CPU-bound work, like request parsing or complex tokenization, often stays on the host.</p>
<div id="fig-m4-c02-f02" class="quarto-float quarto-figure quarto-figure-center anchored" alt="CPU and GPU designs emphasize different kinds of work. As a broad design tendency, CPUs devote more resources to low-latency control, caches, and irregular execution, while GPUs devote more resources to throughput across many similar operations. Treat the visual as a conceptual comparison rather than a literal chip floorplan. Modern CPUs and GPUs overlap in capability, but the throughput emphasis of GPUs explains why regular tensor shapes, batching, and memory coalescing matter.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m4-c02-f02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m4-c02-f02.jpg" class="img-fluid figure-img" style="width:6.1in" alt="CPU and GPU designs emphasize different kinds of work. As a broad design tendency, CPUs devote more resources to low-latency control, caches, and irregular execution, while GPUs devote more resources to throughput across many similar operations. Treat the visual as a conceptual comparison rather than a literal chip floorplan. Modern CPUs and GPUs overlap in capability, but the throughput emphasis of GPUs explains why regular tensor shapes, batching, and memory coalescing matter.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m4-c02-f02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: CPU and GPU design trade-off
</figcaption>
</figure>
</div>
</section>
<section id="sec-m4-c02-s02" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="sec-m4-c02-s02"><span class="header-section-number">2.2</span> GPU chip structure</h2>
<p>GPU chip structure is the organization of execution units, on-chip storage (memory built into the GPU chip itself), caches, and off-chip memory that a kernel uses while it runs. Computation happens in execution units, while data is staged and reused through several storage levels with different scopes and costs.</p>
<p>GPU performance depends on registers, per-block shared memory, hardware-managed caches, High Bandwidth Memory (HBM), and external interconnects. Each level differs in scope, capacity, lifetime, and how software influences placement or reuse.</p>
<div id="fig-m4-c02-f03" class="quarto-float quarto-figure quarto-figure-center anchored" alt="GPU performance depends on registers, per-block shared memory, hardware-managed caches, High Bandwidth Memory (HBM), and external interconnects. Each level differs in scope, capacity, lifetime, and how software influences placement or reuse. The capacities printed in this source slide describe a particular accelerator rather than every GPU. Do not read the tiers as one compulsory path for every access: instructions, caches, shared-memory staging, and interconnect traffic depend on the operation and kernel.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m4-c02-f03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m4-c02-f03.jpg" class="img-fluid figure-img" style="width:6.1in" alt="GPU performance depends on registers, per-block shared memory, hardware-managed caches, High Bandwidth Memory (HBM), and external interconnects. Each level differs in scope, capacity, lifetime, and how software influences placement or reuse. The capacities printed in this source slide describe a particular accelerator rather than every GPU. Do not read the tiers as one compulsory path for every access: instructions, caches, shared-memory staging, and interconnect traffic depend on the operation and kernel.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m4-c02-f03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: GPU memory hierarchy
</figcaption>
</figure>
</div>
<p>The capacities printed in the figure describe a particular accelerator rather than every GPU. The tiers are not one compulsory path for every access: instructions, caches, shared-memory staging, and interconnect traffic depend on the operation and kernel.</p>
<p>A <strong>Streaming Multiprocessor (SM)</strong> is a GPU execution unit with a finite pool of registers, shared memory, scheduling slots, and arithmetic resources. The CPU launches a <span class="definition-term" data-custom-style="Definition Term"><strong>kernel</strong></span>, a GPU function executed by many logical threads. Its launch groups those threads into <span class="definition-term" data-custom-style="Definition Term"><strong>blocks</strong></span>, whose threads can share on-chip storage and synchronize. In the baseline CUDA execution model, each block executes on one SM, and several blocks can reside there together if resources permit. A <strong>warp</strong> is a scheduling group of 32 threads within a block on the NVIDIA GPUs described by the <em>CUDA C++ Programming Guide 12.4</em>. The SM schedules these warps, while L2 and HBM serve the whole device.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Chapter 3 develops indexing and scheduling in detail.</p>
<div class="publisher-clarification-note" data-custom-style="Clarification Note">
<p><strong>One word, four meanings: block</strong></p>
<p><strong>Thread block:</strong> the group of threads that a kernel launch creates together, which shares on-chip memory and can synchronize. This is the meaning used here and in <a href="ch-m4-c03.html#sec-m4-c03-s04">Section 3.2</a>.</p>
<p><strong>Block of data, also called a tile:</strong> the rectangular piece of a tensor that one Triton program instance loads and computes, sized by constants such as <code>BLOCK_SIZE</code> (<a href="ch-m4-c04.html#sec-m4-c04-s04">Section 4.3</a>). It names a piece of data, not a group of threads.</p>
<p><strong>Transformer block:</strong> one layer of the model, meaning its attention and feed-forward sub-layers together (<a href="ch-m4-c01.html#sec-m4-c01-s09">Section 1.1</a>).</p>
<p><strong>KV-cache block:</strong> the fixed number of token positions whose keys and values are stored in one allocation (<a href="ch-m4-c09.html#sec-m4-c09-s05">Section 9.5</a>). It names a unit of memory management.</p>
<p>The subject under discussion decides which one is meant.</p>
</div>
<div class="publisher-clarification-note" data-custom-style="Clarification Note">
<p><strong>Resident blocks and occupancy</strong></p>
<p>Registers are used by individual threads, but all resident threads draw from the SM’s finite register capacity. Shared memory is allocated per block, but all resident blocks draw from the SM’s shared-memory capacity. Admission must satisfy both limits together, as well as the device’s block and thread limits.</p>
<p><span class="definition-term" data-custom-style="Definition Term"><strong>Occupancy</strong></span> is the ratio of resident active warps on an SM to its maximum supported resident warps. High occupancy can hide latency, but it does not guarantee high throughput when memory access, instruction mix, or dependencies are poor.</p>
</div>
<p>The chip structure matters because every kernel consumes scarce per-SM resources: registers, shared memory, scheduler slots, and memory bandwidth. A kernel with too many registers per thread may reduce the number of active warps. A kernel with too much shared memory per block may reduce how many blocks can reside on an SM. A kernel with poor memory locality can keep arithmetic units idle even when many threads are present.</p>
</section>
<section id="sec-m4-c02-s03" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-m4-c02-s03"><span class="header-section-number">2.3</span> Memory hierarchy</h2>
<p>GPU memory is not one uniform pool. Performance depends on which level serves the data, who can see it, and how directly the programmer can control it.</p>
<ul>
<li><strong>Registers:</strong> Fastest storage, private to one thread, and used for scalar temporaries and small per-thread fragments. <span class="definition-term" data-custom-style="Definition Term"><strong>Register pressure</strong></span> (a kernel’s demand on the finite register file) can reduce occupancy because each Streaming Multiprocessor (SM) has a finite register file.</li>
<li><strong>Shared memory:</strong> On-chip memory shared by threads in one block, also called a Cooperative Thread Array (CTA). It is explicitly managed and useful for tiled reuse, but capacity is small and bank conflicts can waste bandwidth.</li>
<li><strong>L2 cache:</strong> Device-wide cache shared across SMs. It can capture cross-SM or cross-kernel locality, but programmers usually control it indirectly through access patterns and kernel choices rather than direct allocation.</li>
<li><strong>High Bandwidth Memory (HBM):</strong> Large off-chip GPU memory that stores model weights, activations, gradients, optimizer state, and KV cache. Its bandwidth is high in absolute terms, but it is still much slower than on-chip storage.</li>
<li><strong>Host memory and interconnect:</strong> CPU memory reached over <span class="definition-term" data-custom-style="Definition Term"><strong>PCIe</strong></span> (the standard expansion bus that connects GPUs, network cards, and other devices to the CPU) or another system path. Transfers are much slower than on-device reuse, so repeated host/device movement in frequently executed code is usually wasteful.</li>
</ul>
<div class="publisher-clarification-note" data-custom-style="Clarification Note">
<p><strong>Memory-tier caveat</strong></p>
<p>The phrase ‘GPU memory’ hides large cost differences among registers, shared memory, L2, HBM, and host transfers. A kernel can fit in HBM and still be slow because it fails to reuse data closer to the SM.</p>
</div>
<div id="tbl-m4-c02-t01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c02-t01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: Memory hierarchy comparison.
</figcaption>
<div aria-describedby="tbl-m4-c02-t01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Level</th>
<th>Scope</th>
<th>Engineering role</th>
<th>Main risk</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Registers</td>
<td>Thread</td>
<td>Fast scalar and vector temporaries</td>
<td>Too many registers reduce occupancy</td>
</tr>
<tr class="even">
<td>Shared memory</td>
<td>Block / CTA</td>
<td>Tile reuse and cooperative staging</td>
<td>Bank conflicts or capacity pressure</td>
</tr>
<tr class="odd">
<td>L2 cache</td>
<td>Device</td>
<td>Cross-SM reuse and caching</td>
<td>Limited control and eviction</td>
</tr>
<tr class="even">
<td>HBM</td>
<td>Device</td>
<td>Large tensor storage</td>
<td>Bandwidth and latency dominate if reuse is poor</td>
</tr>
<tr class="odd">
<td>Host / interconnect</td>
<td>System or cluster</td>
<td>Data loading and multi-GPU movement</td>
<td>Transfer latency and bandwidth</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>GPU caches are hardware-managed storage between Streaming Multiprocessors and HBM. CUDA memory spaces such as registers, shared memory, global memory, and constant memory expose explicit placement choices. Ordinary L1 and L2 cache residency mostly follows access pattern, instruction choice, and hardware replacement policy.</p>
<p>The per-SM L1 or unified data cache is closest to executing warps. It can reduce latency for repeated or nearby accesses inside work scheduled on the same SM. Cross-SM reuse belongs mainly to the device-wide L2 cache, which sits between kernel load/store traffic and HBM. L2 can capture reuse across SMs or across nearby kernel launches, while remaining much smaller than model weights, activations, or long KV-cache state.</p>
<p>A <span class="definition-term" data-custom-style="Definition Term"><strong>cache line</strong></span> holds a fixed-size, aligned region of memory together with information identifying its address. The cache’s address-mapping rule assigns each line to a <span class="definition-term" data-custom-style="Definition Term"><strong>set</strong></span>, the group of candidate locations where it may be kept. Each location in that set is a <span class="definition-term" data-custom-style="Definition Term"><strong>way</strong></span>. <span class="definition-term" data-custom-style="Definition Term"><strong>Associativity</strong></span> is the number of ways per set. If more needed lines map to one set than it has ways, one must be evicted even when another set has free space. Returning to the evicted line produces a conflict miss. Exact NVIDIA GPU set mapping and replacement behavior are architecture-specific, not a stable CUDA programming contract.</p>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: Free capacity with repeated cache misses</strong></p>
<p>Consider a hypothetical cache with two sets and two ways per set, initially empty. Let the set be <code>line_number mod 2</code>, and let replacement evict the least recently used line. Accessing lines <code>0, 2, 4, 0</code> sends every access to set 0. Line 0 misses and occupies one way. Line 2 misses and fills the other. Line 4 misses and evicts line 0. The final access to line 0 misses again and evicts line 2. Set 1 remains empty throughout, despite these evictions. If a changed layout places the third item in line 5 instead, accesses <code>0, 2, 5, 0</code> put line 5 in set 1, and the final access to line 0 hits. This illustrates how addresses can change reuse without changing the number of items. The modulo mapping and replacement rule are teaching assumptions, not an NVIDIA cache specification. Actual layout changes need profiler evidence.</p>
</div>
<p>The practical optimization question is therefore not ‘which cache set owns this tensor?’ The useful questions are whether adjacent lanes access adjacent addresses, whether the working set fits within the level that should reuse it, whether a stride pattern repeatedly fights for the same limited cache resources, how many cache sectors (fixed-size units of cache traffic, defined below) are requested, how many requests miss to L2 or HBM, and whether reused data should be staged explicitly in shared memory or registers.</p>
<ul>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>L1 or unified data cache:</strong></span> Per-SM cache path for local load/store traffic. It helps locality inside work scheduled on the same SM, but it is not a general cross-SM state store.</li>
<li><strong>L2 cache:</strong> Device-wide cache shared by SMs. It is the main hardware cache level to discuss for cross-SM global-memory locality and L2 persistence controls.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Cache sector:</strong></span> Profiler-visible access granularity. Nsight Compute reports sectors as 32-byte chunks, with four sectors in a 128-byte L1 or L2 cache line on documented NVIDIA profiling views.</li>
<li><strong>Associativity:</strong> The ways-per-set limit just illustrated. It matters when address layout or stride creates conflict misses even though total cache capacity seems sufficient.</li>
<li><strong>Cache control boundaries:</strong> The hardware limits direct placement, but provides specific controls:
<ul>
<li><code>cudaFuncSetCacheConfig</code>: Requests a preferred L1/shared-memory split on supported devices.</li>
<li><strong>L2 persistence window:</strong> Gives selected accesses preferential retention across kernel launches within the supported cache limits.</li>
<li><strong>PTX eviction hints:</strong> Give streaming data a lower retention priority to reduce interference with reused lines. They do not guarantee that reused data remains cached.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></li>
<li><strong>Profiler-counter proof:</strong> Verifies hit rates to confirm cache effectiveness. None of these controls assigns an arbitrary tensor to a cache set or pins an ordinary cache line.</li>
</ul></li>
</ul>
<p>L2 cache <span class="definition-term" data-custom-style="Definition Term"><strong>hit rates</strong></span> (the fraction of requests found in the cache) can drop if strides repeatedly map different addresses to the same cache sets. This is an associativity or conflict miss. Reorganizing the layout or padding the dimension can reduce these misses, though the exact hardware hash function is not documented.</p>
<p>Cache controls help only when the access pattern creates reuse and profiler counters show that the hardware retains it. They cannot repair scattered accesses or force exact residency. Once operands reach an SM, the next question is whether their shapes and data types let Tensor Cores perform the arithmetic efficiently.</p>
</section>
<section id="sec-m4-c02-s04" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="sec-m4-c02-s04"><span class="header-section-number">2.4</span> Tensor cores and shape alignment</h2>
<p><span class="definition-term" data-custom-style="Definition Term"><strong>Tensor Cores</strong></span> are specialized Matrix Multiply-Accumulate (MMA) units inside Streaming Multiprocessor partitions. They consume supported matrix tiles at very high throughput. One H100 SXM configuration has 132 SMs and four fourth-generation Tensor Cores per SM, but exact counts and available throughput depend on the GPU variant and enabled chip resources. This configuration is documented in <em>NVIDIA Hopper Architecture In-Depth</em>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p><span class="definition-term" data-custom-style="Definition Term"><strong>Multiply-accumulate</strong></span> means multiplying corresponding operand values and adding the products into a running result. For a matrix tile, an operand of shape <span class="math inline">\(m\times k\)</span> multiplies one of shape <span class="math inline">\(k\times n\)</span> and adds into an <span class="math inline">\(m\times n\)</span> accumulator. The result has <span class="math inline">\(m\)</span> rows and <span class="math inline">\(n\)</span> columns. Here <span class="math inline">\(k\)</span> is the shared dimension over which products are summed, not a third output axis. A tile described as <span class="math inline">\(m\times n\times k=16\times16\times16\)</span> therefore consumes two <span class="math inline">\(16\times16\)</span> operand tiles and updates a <span class="math inline">\(16\times16\)</span> result. Exact supported instruction shapes depend on architecture, dtype, and kernel path.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: Padding a reduction dimension</strong></p>
<p>Take <span class="math inline">\(A\)</span> with rows <code>[1,2,3]</code> and <code>[4,5,6]</code>, and <span class="math inline">\(B\)</span> with rows <code>[1,0]</code>, <code>[0,1]</code>, and <code>[1,1]</code>. Their shapes are <span class="math inline">\(2\times3\)</span> and <span class="math inline">\(3\times2\)</span>, so the output has shape <span class="math inline">\(2\times2\)</span>. With a zero starting accumulator, its upper-left value is <span class="math inline">\(1\times1+2\times0+3\times1=4\)</span>.</p>
<p>For an illustrative software tile with <span class="math inline">\(m=n=k=2\)</span>, the first two positions of the shared dimension contribute rows <code>[1,2]</code>, <code>[4,5]</code>. The remaining position contributes <code>[3,3]</code>, <code>[6,6]</code>. Padding <span class="math inline">\(A\)</span> with a zero fourth column and <span class="math inline">\(B\)</span> with a zero fourth row lets that second tile process two positions: its added zero products leave the result unchanged. Summing the two contributions gives output rows <code>[4,5]</code> and <code>[10,11]</code>. All four output entries are retained. The padded calculation performs 16 multiply-add pairs instead of 12, so easier tiling comes with extra work. This small software tile illustrates the arithmetic, not an available Tensor Core instruction. A kernel can also handle the remainder separately. Actual speed depends on the selected implementation.</p>
</div>
<p>This is why hidden sizes, head dimensions, batch shapes, and padding can affect performance. Padding may increase nominal arithmetic while improving utilization on a suitable Tensor Core path. Section 3.7 develops the full GEMM shape relation.</p>
<p>In modern transformer GEMM, ‘compute-bound’ (<a href="#sec-m4-c02-s08">Section 2.8</a>) often means ‘tensor-core-bound’: the useful question is whether the operation reaches the specialized matrix units efficiently. Verify this in traces rather than assuming it. Nsight Systems kernel names, Nsight Compute instruction metrics, and achieved tensor-core utilization can show whether the intended path was actually used.</p>
<p>Shape alignment depends on the library path and GPU architecture as well as the mathematical matrix dimensions. NVIDIA’s matrix-multiplication guidance reports that modern cuBLAS and cuDNN can often use Tensor Cores even when dimensions are imperfectly aligned, while efficiency improves when the fastest-varying matrix dimensions align to hardware-friendly byte multiples. For FP16, a common practical rule is to prefer multiples of 8 elements, with larger multiples often helping on A100-class paths. Exact requirements vary by CUDA library version, dtype, layout, and GPU generation. See <em>Matrix Multiplication Background User’s Guide</em>.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>A poorly aligned matrix shape can trigger internal padding, a less efficient tile path, a different kernel, or Tensor Core execution with lower utilization. A trace relates the actual kernel path, achieved utilization, and tensor dimensions.</p>
<p>The tensor-core figure compares two tile-utilization cases. It is a schematic utilization comparison, not a timing benchmark.</p>
<p>Tensor Cores execute supported matrix multiply-accumulate instructions on small hardware fragments. Kernels combine those fragments into warp-, block-, and software-level tiles that can be much larger than one instruction.</p>
<div id="fig-m4-c02-f04" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Tensor Cores execute supported matrix multiply-accumulate instructions on small hardware fragments. Kernels combine those fragments into warp-, block-, and software-level tiles that can be much larger than one instruction. The 64 by 64 regions in the visual are software or kernel tiles, not the dimensions of one Tensor Core instruction. Alignment and remainder handling can affect utilization, while exact instruction shapes and Tensor Core counts depend on GPU architecture, dtype, and SKU.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m4-c02-f04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m4-c02-f04.jpg" class="img-fluid figure-img" style="width:6.1in" alt="Tensor Cores execute supported matrix multiply-accumulate instructions on small hardware fragments. Kernels combine those fragments into warp-, block-, and software-level tiles that can be much larger than one instruction. The 64 by 64 regions in the visual are software or kernel tiles, not the dimensions of one Tensor Core instruction. Alignment and remainder handling can affect utilization, while exact instruction shapes and Tensor Core counts depend on GPU architecture, dtype, and SKU.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m4-c02-f04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.4: Tensor Core tiling and utilization
</figcaption>
</figure>
</div>
<p>The 64 by 64 regions in the visual are software or kernel tiles, not the dimensions of one Tensor Core instruction. Alignment and remainder handling can affect utilization, while exact instruction shapes and Tensor Core counts depend on GPU architecture, dtype, and SKU.</p>
<p>Tensor Core speed requires a supported numerical format and an execution path that selects the accelerated kernel. Suitable dimension alignment can improve efficiency without being a universal requirement for Tensor Core use. When an operation spans several GPUs, the next question is whether the local interconnect can move partial results quickly enough to preserve that compute gain.</p>
</section>
<section id="sec-m4-c02-s05" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="sec-m4-c02-s05"><span class="header-section-number">2.5</span> Intra-node interconnects</h2>
<p>The earlier sections described one GPU’s execution and memory hierarchy. Scaling starts when tensors must cross a physical boundary: between GPUs in one server or between servers in a cluster. A GPU is one execution device. A board or accelerator card packages one or more GPUs and their local HBM. A node, also called a server, contains CPUs, host memory, PCIe root complexes, network interface cards, and one or more GPU boards. Intra-node traffic stays inside one server. Inter-node traffic crosses the cluster network between servers.</p>
<p>Intra-node topology starts before GPU-to-GPU links. Multi-socket servers often have Non-Uniform Memory Access (NUMA): CPU cores, host memory channels, PCIe root complexes, GPUs, and <span class="definition-term" data-custom-style="Definition Term"><strong>Network Interface Cards (NICs)</strong></span> (the devices that connect a server to the cluster network) are closer to some sockets than others. A process placed on the wrong CPU socket can feed a nearby-looking GPU through a slower path.</p>
<p>Software placement determines which of these paths carries an input batch. A <span class="definition-term" data-custom-style="Definition Term"><strong>process</strong></span> is a running operating-system program instance. A <span class="definition-term" data-custom-style="Definition Term"><strong>rank</strong></span> is its integer identity within a distributed group, not a GPU. Selecting a <span class="definition-term" data-custom-style="Definition Term"><strong>GPU device</strong></span> chooses where that process submits device work. <span class="definition-term" data-custom-style="Definition Term"><strong>CPU affinity</strong></span> restricts which CPU cores may run the process, while host-memory placement is a separate NUMA policy. Optional <span class="definition-term" data-custom-style="Definition Term"><strong>data-loading workers</strong></span> are helper processes that prepare batches for the training process. They do not automatically acquire distributed ranks or their own GPUs.</p>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: Two ranks feeding two local GPUs</strong></p>
<p>Assume one server with two CPU sockets, GPU 0 attached near socket 0 and GPU 1 near socket 1, and one training process per GPU. Process P0 has rank 0, CPU affinity on socket 0, and selects GPU 0. P1 has rank 1, runs on socket 1, and selects GPU 1. These rank-to-device matches are explicit choices in this example. Other mappings are possible.</p>
<p>For P1, optional loader workers prepare a batch using CPU cores and host memory placed near socket 1. P1 submits its input copy through the GPU’s local PCIe path into GPU 1’s HBM, then launches work on that data. If the batch’s host pages are instead on socket 0, the copy may also cross the inter-socket link. CPU affinity alone does not move those pages or select GPU 1. Local placement can reduce this extra traffic, but its effect needs measurement. Chapter 12 extends this setup to communication groups and multiple servers.</p>
</div>
<p>PCIe connects GPUs to the host and sometimes to each other, but it is much slower than on-package or board-level GPU interconnects. NVLink provides higher bandwidth GPU-to-GPU communication inside a node. <span class="definition-term" data-custom-style="Definition Term"><strong>NVSwitch</strong></span> (a switch chip that joins many NVLink GPUs) extends this idea to many GPUs. These fabrics matter for tensor parallelism and frequent collectives.</p>
<p>Table 2.2 provides an initial scale comparison: it shows how the available byte rate usually falls as traffic leaves one GPU. These are planning ranges, not measured ceilings for the current system.</p>
<div id="tbl-m4-c02-t02" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c02-t02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: Typical movement paths and bandwidth ranges for planning. Actual values depend on the hardware generation and topology.
</figcaption>
<div aria-describedby="tbl-m4-c02-t02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Path</th>
<th>Typical scope</th>
<th>Typical bandwidth</th>
<th>How to use the number</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HBM</td>
<td>On one GPU</td>
<td>Several TB/s on data-center GPUs</td>
<td>Use as the roofline memory ceiling for local kernel reads and writes.</td>
</tr>
<tr class="even">
<td>NVLink / NVSwitch</td>
<td>GPU-to-GPU inside supported systems</td>
<td>Hundreds of GB/s to around TB/s-class aggregate paths depending on generation and topology</td>
<td>Useful for frequent tensor-parallel or collective traffic inside the fast local domain.</td>
</tr>
<tr class="odd">
<td>PCIe</td>
<td>CPU/GPU or device path through PCIe</td>
<td>Tens of GB/s per direction for current high-end links</td>
<td>Good for setup and staged copies, but too slow for repeated hot-loop movement.</td>
</tr>
<tr class="even">
<td>InfiniBand / RoCE</td>
<td>Across nodes</td>
<td>Tens to hundreds of GB/s effective per node only on engineered fabrics</td>
<td>Use for scale-out communication after confirming the runtime selected the intended NIC and transport.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-m4-c02-s06" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="sec-m4-c02-s06"><span class="header-section-number">2.6</span> Interconnect hierarchy beyond HBM</h2>
<p>An interconnect is the path used to move data between processors, accelerators, host memory, network cards, or nodes. After data leaves HBM or one GPU, the cost model changes: bandwidth usually drops, latency rises, and synchronization becomes more visible.</p>
<p>Moving a host batch to the GPU also depends on its memory type. <span class="definition-term" data-custom-style="Definition Term"><strong>Pageable memory</strong></span> is ordinary host memory whose physical pages the operating system may move or page out. <strong>Pinned memory</strong> is host memory held in place for transfers. <span class="definition-term" data-custom-style="Definition Term"><strong>Direct Memory Access (DMA)</strong></span> lets a device move the payload without the CPU copying each byte. On a pageable host-to-GPU route, the runtime may first copy the payload with the CPU into a pinned staging buffer. A copy engine then transfers it to HBM. Starting from a pinned buffer can remove that staging copy. The CPU still allocates buffers and submits work, and dependent computation must wait for transfer completion. Pinning consumes host resources and does not itself prove overlap. Section 3.3 gives the CUDA lifecycle.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p><span class="definition-term" data-custom-style="Definition Term"><strong>Remote DMA (RDMA)</strong></span> lets network hardware transfer data to or from registered memory on another machine, with software setting up the accessible buffers and communication. <span class="definition-term" data-custom-style="Definition Term"><strong>GPUDirect RDMA</strong></span> extends the direct path to compatible GPU memory: the NIC can access HBM through PCIe, avoiding an intermediate host payload buffer. A staged GPU-to-network path copies from HBM to host memory before the NIC sends the bytes. A supported direct path transfers between the NIC and HBM. CPU coordination and completion ordering remain necessary. Compatible devices, drivers, memory registration, and topology determine whether this path works, as described in the <a href="https://docs.nvidia.com/cuda/gpudirect-rdma/">NVIDIA GPUDirect RDMA documentation</a>. Section 12.4 develops those network conditions.</p>
<ul>
<li><strong>PCIe:</strong> General host/device expansion bus for CPUs, GPUs, NICs, and other devices.</li>
<li><strong>NVLink:</strong> High-bandwidth GPU-to-GPU link available only on supported systems and topologies.</li>
<li><strong>NVSwitch:</strong> Switch fabric that connects multiple NVLink-capable GPUs inside a server or platform.</li>
<li><strong>NIC:</strong> Network Interface Card, the device that connects a node to the cluster network.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>InfiniBand:</strong></span> High-performance cluster fabric commonly used for multi-node GPU training and serving.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>RoCE:</strong></span> RDMA over Converged Ethernet. Performance depends strongly on Ethernet fabric configuration.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Ethernet:</strong></span> General-purpose network fabric. It is ubiquitous, but unoptimized paths are often weak for frequent GPU collectives.</li>
</ul>
<p>After HBM, the next distance is usually another GPU or another node. Moving tensors across PCIe, NVLink, NVSwitch, InfiniBand, RoCE, or Ethernet is far more expensive than reading registers or shared memory. Distributed training and distributed inference therefore add explicit communication costs and synchronization points to the single-GPU execution model.</p>
<p>Each memory or communication path is a separate measured resource. Register and shared-memory reuse usually avoids slower device-memory traffic. An HBM load uses the GPU memory controllers. A <span class="definition-term" data-custom-style="Definition Term"><strong>peer transfer</strong></span> (a direct copy between two GPUs) uses NVLink, NVSwitch, or PCIe. A cross-node transfer adds a NIC and network fabric. Their relative cost depends on message size, topology, contention, and overlap, so the selected path, effective bandwidth, and latency require measurement.</p>
<p>A memory-transfer path is the hardware route used to move bytes from one memory domain to another. For GPU workloads, the important domains are CPU system memory, pinned host memory, one GPU’s HBM, another GPU’s HBM, and memory reachable through a Network Interface Card (NIC). These domains differ in latency, bandwidth, address-translation rules, and synchronization behavior.</p>
<p>The performance mistake is to treat every transfer as the same kind of HBM traffic. A kernel reading its own tensor, a host batch copied into GPU memory, a peer GPU copy, and a cross-node collective all move bytes, but they use different software owners and hardware paths.</p>
<p>Copy engines and caches solve different movement problems. A copy engine is used for explicit transfer work, such as host-device copies or some device-device copies. The cache hierarchy serves ordinary kernel load/store instructions as warps read and write tensors. A slow trace can involve both: a batch might first move through a DMA copy path into HBM, then a kernel might waste HBM bandwidth because its warp loads miss cache or access scattered sectors.</p>
<p>The following principles and table answer a practical design question: which software layer initiates each path, which physical route carries the bytes, and which condition should be checked before optimizing it.</p>
<div class="publisher-clarification-note" data-custom-style="Clarification Note">
<p><strong>Transfer design principles</strong></p>
<p><strong>Pinned-memory staging:</strong> Use page-locked host buffers when repeated host-to-device copies need efficient DMA and possible overlap.</p>
<p><strong>Compute near data:</strong> Run the operation where the tensor already lives instead of moving the tensor to a more convenient but distant processor.</p>
<p><strong>Direct path validation:</strong> Confirm that a peer, NVLink/NVSwitch, or RDMA path is actually available before assuming the fast route exists.</p>
<p><strong>Distance by frequency:</strong> The more often data moves, the closer the communicating devices must be (<a href="ch-m4-c12.html#sec-m4-c12-s11">Section 12.11</a>).</p>
</div>
<p>After a trace identifies a transfer, Table 2.3 answers a different question: which software submitted it, which physical route likely carried it, and what evidence can distinguish a direct path from staging or fallback.</p>
<div id="tbl-m4-c02-t03" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c02-t03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.3: Transfer paths: initiating software, physical route, and diagnostic check.
</figcaption>
<div aria-describedby="tbl-m4-c02-t03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Path</th>
<th>Typical owner</th>
<th>Hardware route</th>
<th>What to verify</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kernel HBM access</td>
<td>Kernel code, vendor library, Triton, TorchInductor</td>
<td>SM load/store through L2 and HBM controllers</td>
<td>Uncoalesced access or poor reuse wastes HBM bandwidth</td>
</tr>
<tr class="even">
<td>Host to GPU</td>
<td>PyTorch tensor placement, CUDA runtime</td>
<td>Pinned/pageable host memory through PCIe or similar host path</td>
<td>Pageable staging, NUMA mismatch, hidden synchronization</td>
</tr>
<tr class="odd">
<td>GPU to GPU</td>
<td>CUDA peer copy, NCCL, distributed framework</td>
<td>NVLink, NVSwitch, or PCIe peer path</td>
<td>Peer access unavailable, topology asymmetry, host bounce</td>
</tr>
<tr class="even">
<td>GPU to network</td>
<td>NCCL, UCX/MPI, NIC driver</td>
<td>NIC/RDMA path through InfiniBand, RoCE, or Ethernet</td>
<td>Wrong NIC, no GPUDirect RDMA, congestion, rank skew</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Name the data path before choosing a fix. A profiler copy span might be a host-device DMA transfer, a peer GPU copy, a network transfer, unified-memory migration, or explicit kernel load/store traffic. Each path requires a different change.</p>
</section>
<section id="sec-m4-c02-s07" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="sec-m4-c02-s07"><span class="header-section-number">2.7</span> Hardware limits on software design</h2>
<p>Software design is constrained by the cheapest place where data can be reused. If values are reused within a thread, registers are ideal. If values are reused by a block, shared memory can help. If values are reused across kernels or requests, L2, HBM layout, and serving-engine cache policies matter. Distributed systems add another hierarchy: GPU-to-GPU, node-to-node, and storage-to-host movement.</p>
<p>VRAM means the GPU device-memory capacity available for tensors, model weights, activations, workspaces, and caches. On the datacenter GPUs discussed in this module, that device memory is High Bandwidth Memory (HBM).</p>
<p>For many current LLMs, one device cannot hold the weights at the desired precision together with KV cache, activations, temporary workspaces, and allocator headroom. The raw weight byte count and the workload-specific state together determine whether quantization, sharding, or offload is needed. Table 2.4 compares specific GPU variants because capacity and bandwidth depend on that choice. The Tesla P100 SXM2 16 GB row uses the <em>Tesla P100 Datasheet</em><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>, the Tesla V100 SXM2 32 GB row uses the <em>Tesla V100 Datasheet</em><a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>, the A100 80 GB SXM row uses the <em>NVIDIA A100</em> specifications<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>, the H100 SXM5 80 GB row uses the <em>NVIDIA H100</em> product specifications<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a>, and the B200 row derives per-GPU values from the <em>NVIDIA DGX B200</em> system totals<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a>.</p>
<div id="tbl-m4-c02-t04" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c02-t04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.4: Example GPU capacity and raw-weight sizing limits.
</figcaption>
<div aria-describedby="tbl-m4-c02-t04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Example GPU</th>
<th>VRAM capacity</th>
<th>Peak bandwidth</th>
<th>Example model scale</th>
<th>What else uses memory</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tesla P100 SXM2 16 GB (GP100 / Pascal)</td>
<td>16 GB (HBM2)</td>
<td>732 GB/s</td>
<td>BERT-Large (~340M parameters)</td>
<td>FP16 weights are about 0.68 GB; BERT-Large is a small model by current LLM-serving scale</td>
</tr>
<tr class="even">
<td>Tesla V100 SXM2 32 GB (GV100 / Volta)</td>
<td>32 GB (HBM2)</td>
<td>900 GB/s</td>
<td>GPT-2 (~1.5B parameters)</td>
<td>Fits in a single GPU; requires ~3 GB in FP16, leaving room for activations</td>
</tr>
<tr class="odd">
<td>A100 80 GB SXM (GA100 / Ampere)</td>
<td>80 GB (HBM2e)</td>
<td>2.0 TB/s</td>
<td>GPT-3 (~175B parameters)</td>
<td>FP16 weights (~350 GB) require multi-GPU sharding. Crossing nodes depends on GPUs and usable memory per server plus workload headroom</td>
</tr>
<tr class="even">
<td>H100 SXM5 80 GB (GH100 / Hopper)</td>
<td>80 GB (HBM3)</td>
<td>3.35 TB/s</td>
<td>Llama 3-70B (~70B parameters)</td>
<td>FP16 weights need two or more GPUs. Raw FP8 weights can fit one 80 GB GPU only with an explicit KV-cache and workspace budget; INT4 leaves more headroom</td>
</tr>
<tr class="odd">
<td>B200 (DGX B200 / Blackwell, HBM3e)</td>
<td>180 GB (HBM3e)</td>
<td>8.0 TB/s</td>
<td>Llama 3-405B (~405B parameters)</td>
<td>Requires multi-GPU sharding. An 8-GPU node is a common deployment unit; final GPU count depends on weight dtype plus KV-cache and workspace budget</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: GPU count is not server count</strong></p>
<p>At two bytes per parameter, 175 billion parameters occupy about 350 GB before other state. That exceeds one 80 GB GPU, so this placement needs multiple GPUs. A hypothetical server with eight such GPUs has <span class="math inline">\(8\times80=640\)</span> GB of aggregate raw capacity. Thus 350 GB alone does not establish a need for multiple servers. The 640 GB is spread over eight devices, not one allocation pool: a sharding scheme must fit each device’s share together with activations, cache, workspaces, and other required state. The available GPUs and usable memory per server determine whether the workload must cross nodes.</p>
</div>
</section>
<section id="sec-m4-c02-s08" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="sec-m4-c02-s08"><span class="header-section-number">2.8</span> Work, bytes, and time</h2>
<p><a href="ch-m4-c01.html#sec-m4-c01-s03">Section 1.4</a> estimated that one generated token of an 8B model needs about 16 GFLOP, roughly 16 microseconds at an H100’s peak arithmetic rate. For a model whose projection weights exceed cache capacity, a small decode step typically reads most of those weights from HBM, so memory traffic can set the time. Arithmetic and data movement each impose a lower bound. Their maximum is an ideal estimate when they overlap completely. Choosing the right optimization therefore starts with knowing which of the two is slower.</p>
<p>To a first approximation, arithmetic takes FLOPs divided by the peak compute rate, and data movement takes bytes moved divided by the memory bandwidth. Their ratio depends on one property of the operation:</p>
<ul>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Arithmetic intensity</strong></span>: FLOPs performed per byte moved to or from memory, measured in FLOP/byte. It states how much arithmetic each fetched byte supports.</li>
<li><span class="definition-term" data-custom-style="Definition Term"><strong>Ridge point</strong></span>: the peak compute rate divided by the memory bandwidth. At this intensity the two times are equal.</li>
<li><strong>Memory-bound and compute-bound regions:</strong> below the ridge point, the bandwidth ceiling is lower than the compute ceiling. Above it, the compute ceiling is lower. These are the model’s limiting resources. A measured kernel can still be limited by launch overhead, latency, or poor utilization.</li>
</ul>
<p>For an H100 SXM GPU, the dense BF16 Tensor Core peak is about 989 TFLOP/s. NVIDIA’s specification lists 1,979 TFLOP/s with structured sparsity, twice the dense rate. With 3.35 TB/s of HBM bandwidth, the ridge point is <span class="math inline">\(989\times10^{12}/3.35\times10^{12}\approx295\)</span> FLOP/byte.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> A BF16 operation must therefore perform about 295 arithmetic operations for every byte it moves before the arithmetic units, rather than memory, become the limit.</p>
<div class="publisher-worked-calculation" data-custom-style="Worked Calculation">
<p><strong>Worked example: One projection at four batch sizes</strong></p>
<p><strong>Inputs:</strong> A BF16 weight matrix of shape <span class="math inline">\(4{,}096\times4{,}096\)</span> multiplies a batch of <span class="math inline">\(B\)</span> token vectors of width 4,096, the query projection from <a href="ch-m4-c01.html#sec-m4-c01-s09">Section 1.1</a>. Each weight is used once per row in one multiply and one add, so the operation performs <span class="math inline">\(2\times B\times4{,}096^2=33{,}554{,}432\,B\)</span> FLOPs. It reads the weights once (<span class="math inline">\(2\times4{,}096^2=33{,}554{,}432\)</span> bytes) and reads and writes <span class="math inline">\(B\)</span> rows of 4,096 two-byte values (<span class="math inline">\(16{,}384\,B\)</span> bytes). The intensity is therefore <span class="math inline">\(33{,}554{,}432\,B/(33{,}554{,}432+16{,}384\,B)=B/(1+B/2{,}048)\)</span> FLOP/byte.</p>
<div id="tbl-m4-c02-t05" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m4-c02-t05-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.5: Work, estimated HBM bytes, and ideal time lower bounds for one 4,096 by 4,096 projection as the row count grows.
</figcaption>
<div aria-describedby="tbl-m4-c02-t05-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Rows <span class="math inline">\(B\)</span></th>
<th>FLOPs</th>
<th>Bytes moved</th>
<th>Intensity (FLOP/byte)</th>
<th>Time at 3.35 TB/s</th>
<th>Time at 989 TFLOP/s</th>
<th>Limit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>33.6 M</td>
<td>33.6 MB</td>
<td>1.0</td>
<td>10.0 µs</td>
<td>0.03 µs</td>
<td>Memory</td>
</tr>
<tr class="even">
<td>64</td>
<td>2.15 G</td>
<td>34.6 MB</td>
<td>62</td>
<td>10.3 µs</td>
<td>2.2 µs</td>
<td>Memory</td>
</tr>
<tr class="odd">
<td>345</td>
<td>11.6 G</td>
<td>39.2 MB</td>
<td>295</td>
<td>11.7 µs</td>
<td>11.7 µs</td>
<td>Balanced</td>
</tr>
<tr class="even">
<td>2,048</td>
<td>68.7 G</td>
<td>67.1 MB</td>
<td>1,024</td>
<td>20.0 µs</td>
<td>69.5 µs</td>
<td>Compute</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Conclusion:</strong> With one row, which is one token of single-request decode, each weight byte supports about one FLOP, nearly 300 times below the ridge point. Under this HBM-traffic estimate, the memory-time lower bound is about 10 microseconds. Adding rows reuses each loaded weight, so this ideal bound grows slowly until about 345 rows, where the compute and memory bounds meet. This is why prefill and training, which process many tokens at once, tend to be compute-bound, while small-batch decode tends to be memory-bound. The estimate assumes that the weights come from HBM and that copying and computing overlap perfectly.</p>
</div>
<p>These two times give a lower bound, not a prediction. A kernel can be slower than both because of launch overhead, too little parallel work, poor memory access patterns, or synchronization. Chapter 5 turns this estimate into the roofline model, fixes the rules for counting FLOPs and bytes, and shows how profiler measurements expose the gap. <a href="ch-m4-c03.html#sec-m4-c03-s11">Section 3.7</a> applies the same reasoning to matrix-vector products, and Chapter 9 to a whole decode step.</p>
<p>CUDA makes this hierarchy programmable. The next chapter names the host, device, kernel, grid, block, thread, warp, stream, and memory-allocation objects that software uses to express work on this hardware.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>NVIDIA. (2024). <em>CUDA C++ Programming Guide 12.4</em>. <a href="https://docs.nvidia.com/cuda/archive/12.4.0/cuda-c-programming-guide/index.html">https://docs.nvidia.com/cuda/archive/12.4.0/cuda-c-programming-guide/index.html</a> (release 2024-03-05). Support: thread hierarchy, warps of 32 threads, memory hierarchy, streams, events, and coalesced access guidance used in Sections 2.2 and 2.3. Limit: exact SM counts, cache sizes, and bandwidths are architecture specific and are cited separately where stated.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>NVIDIA. (2024). <em>Parallel Thread Execution ISA 8.4</em>, sections 9.7.8.1-9.7.8.2. <a href="https://docs.nvidia.com/cuda/archive/12.4.0/parallel-thread-execution/index.html#cache-operators">Cache operators and eviction priority hints</a>. Cache and eviction policies are performance hints, not guarantees of residency or memory ordering.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Andersch, M., Palmer, G., Krashinsky, R., Stam, N., Mehta, V., Brito, G., &amp; Ramaswamy, S. (2022). <em>NVIDIA Hopper Architecture In-Depth</em> (NVIDIA Technical Blog, 2022-03-22). <a href="https://developer.nvidia.com/blog/nvidia-hopper-architecture-in-depth/">https://developer.nvidia.com/blog/nvidia-hopper-architecture-in-depth/</a> . Support: H100 SXM5 has 132 SMs with 4 fourth-generation Tensor Cores per SM; full GH100 has 144 SMs; HBM3 memory and 50 MB L2 cache configuration. Limit: counts describe the stated SXM5 configuration; PCIe and NVL variants differ and exact throughput depends on clocks and enabled resources.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>NVIDIA. (2023). <em>Matrix Multiplication Background User’s Guide</em> (last updated 2023-02-01). <a href="https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html">https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html</a>. Support: Tensor Core use with cuBLAS 11.0 and cuDNN 7.6.3 and later without strict alignment, with best efficiency for FP16 at multiples of 8 elements and larger multiples on A100 paths. Limit: only the fastest-varying dimensions must obey the rule and exact behavior varies by library version, dtype, layout, and architecture.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>NVIDIA. (2023). <em>Matrix Multiplication Background User’s Guide</em> (last updated 2023-02-01). <a href="https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html">https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html</a>. Support: Tensor Core use with cuBLAS 11.0 and cuDNN 7.6.3 and later without strict alignment, with best efficiency for FP16 at multiples of 8 elements and larger multiples on A100 paths. Limit: only the fastest-varying dimensions must obey the rule and exact behavior varies by library version, dtype, layout, and architecture.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>NVIDIA. (2024). <em>CUDA C++ Programming Guide 12.4</em>. <a href="https://docs.nvidia.com/cuda/archive/12.4.0/cuda-c-programming-guide/index.html">https://docs.nvidia.com/cuda/archive/12.4.0/cuda-c-programming-guide/index.html</a> (release 2024-03-05). Support: thread hierarchy, warps of 32 threads, memory hierarchy, streams, events, and coalesced access guidance used in Sections 2.2 and 2.3. Limit: exact SM counts, cache sizes, and bandwidths are architecture specific and are cited separately where stated.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>NVIDIA. (2016). <em>Tesla P100 Datasheet</em>. <a href="https://images.nvidia.com/content/tesla/pdf/nvidia-tesla-p100-datasheet.pdf">https://images.nvidia.com/content/tesla/pdf/nvidia-tesla-p100-datasheet.pdf</a>. Support: SPECIFICATIONS table lists Tesla P100 SXM2 with 16 GB CoWoS HBM2 and 732 GB/s memory bandwidth. Limit: the PCIe 12 GB variant provides 549 GB/s, so the table row names the SXM2 16 GB variant explicitly.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>NVIDIA. (2018). <em>Tesla V100 Datasheet</em>. <a href="https://images.nvidia.com/content/technologies/volta/pdf/tesla-volta-v100-datasheet-letter-fnl-web.pdf">https://images.nvidia.com/content/technologies/volta/pdf/tesla-volta-v100-datasheet-letter-fnl-web.pdf</a>. Support: SPECIFICATIONS table lists Tesla V100 with 16 GB or 32 GB HBM2 and 900 GB/s memory bandwidth. Limit: the 32 GB configuration doubles the standard 16 GB offering while bandwidth stays 900 GB/s, so the table row names the 32 GB variant explicitly.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>NVIDIA. (n.d.). <em>NVIDIA A100 Tensor Core GPU</em> specifications. <a href="https://www.nvidia.com/en-us/data-center/a100/">https://www.nvidia.com/en-us/data-center/a100/</a>. Support: specifications table lists A100 80 GB HBM2e with 1,935 GB/s (PCIe) and 2,039 GB/s (SXM) memory bandwidth. Limit: the table rounds the SXM value to 2.0 TB/s as a planning value and names the SXM variant explicitly.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>NVIDIA. (n.d.). <em>NVIDIA H100 Tensor Core GPU</em> product specifications. <a href="https://www.nvidia.com/en-us/data-center/h100/">https://www.nvidia.com/en-us/data-center/h100/</a>. Support: product specifications table lists H100 SXM with 80 GB memory and 3.35 TB/s memory bandwidth. Limit: PCIe and NVL variants differ in memory type and bandwidth, so the table row names the SXM5 80 GB HBM3 variant explicitly.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>NVIDIA. (n.d.). <em>NVIDIA DGX B200</em> specifications. <a href="https://www.nvidia.com/en-us/data-center/dgx-b200/">https://www.nvidia.com/en-us/data-center/dgx-b200/</a>. Support: specifications list 8 Blackwell GPUs with 1,440 GB total GPU memory and 64 TB/s total HBM3e bandwidth, which divides to 180 GB and 8 TB/s per GPU. Limit: these per-GPU values are derived from the published eight-GPU system totals, not measured transfer rates.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>NVIDIA. (n.d.). <em>NVIDIA H100 Tensor Core GPU</em> product specifications. <a href="https://www.nvidia.com/en-us/data-center/h100/">https://www.nvidia.com/en-us/data-center/h100/</a>. Support: the H100 SXM column lists BFLOAT16 Tensor Core performance of 1,979 teraFLOPS, footnoted “With sparsity,” and 3.35 TB/s GPU memory bandwidth. Limit: the dense value of about 989 TFLOP/s is half the listed sparse figure, and both are theoretical peaks that depend on clocks and kernel path.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch-m4-c01.html" class="pagination-link" aria-label="LLM Workloads and Performance Limits">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">LLM Workloads and Performance Limits</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch-m4-c03.html" class="pagination-link" aria-label="Software to CUDA">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Software to CUDA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>