<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>24&nbsp; Computational labs: Checks, experiments, and evidence – Mathematical Foundations of LLM Training and Inference</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../appendices/ch-m2-dictionary.html" rel="next">
<link href="../chapters/ch-m2-c23.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9e6c75b63f330ca6992d1da0fbaf20d1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-m2-p06.html">Part VI: Implementation and Extensions</a></li><li class="breadcrumb-item"><a href="../chapters/ch-m2-c24.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Computational labs: Checks, experiments, and evidence</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Mathematical Foundations of LLM Training and Inference</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mathematical Foundations of LLM Training and Inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/ch-m2-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Models, tasks, and learning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/ch-m2-roadmap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Roadmap</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/ch-m2-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/ch-m2-library-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library Map</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-m2-p01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part I: From Text to Mathematical Objects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Prediction targets and training pairs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Token IDs and batches</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Subwords and sequence counts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Count vectors and TF-IDF</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-m2-p02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part II: From Scores to Loss</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">From scores to probabilities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Decoding strategies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cross-entropy and perplexity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Validation and testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-m2-p03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part III: From Error to Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Optimization and regularization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Activation functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Embedding tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Word vectors from context</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-m2-p04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part IV: Modeling Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Recurrent networks: Context, state, and sequential computation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Attention mathematics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Transformer blocks: Context, features, and position</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformer families: Visibility, targets, and generation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Pretraining data and compute allocation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-m2-p05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part V: Adapting and Running LLMs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c20.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Model adaptation: Context, preferences, and trainable weights</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c21.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">KV cache: Generation state, latency, and allocation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-m2-p06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VI: Implementation and Extensions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c22.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Images, audio, and tables: Representations and tasks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c23.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Tensor storage: Shapes, views, devices, and lifetime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch-m2-c24.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Computational labs: Checks, experiments, and evidence</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/ch-m2-dictionary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/ch-m2-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-m2-c24-env" id="toc-sec-m2-c24-env" class="nav-link active" data-scroll-target="#sec-m2-c24-env">Environment and supporting notebooks</a></li>
  <li><a href="#sec-m2-c24-s01" id="toc-sec-m2-c24-s01" class="nav-link" data-scroll-target="#sec-m2-c24-s01"><span class="header-section-number">24.1</span> Logistic regression and controlled optimizer comparisons</a></li>
  <li><a href="#sec-m2-c24-s02" id="toc-sec-m2-c24-s02" class="nav-link" data-scroll-target="#sec-m2-c24-s02"><span class="header-section-number">24.2</span> Tokenizer, embedding, and classifier comparisons</a></li>
  <li><a href="#sec-m2-c24-s03" id="toc-sec-m2-c24-s03" class="nav-link" data-scroll-target="#sec-m2-c24-s03"><span class="header-section-number">24.3</span> Attention under a controlled input change</a></li>
  <li><a href="#sec-m2-c24-s04" id="toc-sec-m2-c24-s04" class="nav-link" data-scroll-target="#sec-m2-c24-s04"><span class="header-section-number">24.4</span> Audience adaptation with two model families</a></li>
  <li><a href="#sec-m2-c24-s05" id="toc-sec-m2-c24-s05" class="nav-link" data-scroll-target="#sec-m2-c24-s05"><span class="header-section-number">24.5</span> Character names, shifted targets, and generation feedback</a></li>
  <li><a href="#sec-m2-c24-s06" id="toc-sec-m2-c24-s06" class="nav-link" data-scroll-target="#sec-m2-c24-s06"><span class="header-section-number">24.6</span> The NLTK count-model tutorial and its extensions</a></li>
  <li><a href="#sec-m2-c24-s07" id="toc-sec-m2-c24-s07" class="nav-link" data-scroll-target="#sec-m2-c24-s07"><span class="header-section-number">24.7</span> Captioning, visual questions, and retrieval evidence</a></li>
  <li><a href="#sec-m2-c24-s08" id="toc-sec-m2-c24-s08" class="nav-link" data-scroll-target="#sec-m2-c24-s08"><span class="header-section-number">24.8</span> A bounded synthesis of mechanism and evidence</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-m2-p06.html">Part VI: Implementation and Extensions</a></li><li class="breadcrumb-item"><a href="../chapters/ch-m2-c24.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Computational labs: Checks, experiments, and evidence</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-ch-m2-c24" class="quarto-section-identifier"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Computational labs: Checks, experiments, and evidence</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="publisher-purpose">
<p>Experiments need declared data, fitting procedures, and held-out evidence in addition to local arithmetic and interface checks.</p>
</div>
<p>A correct tensor shape does not establish correct gradients, useful predictions, or faster execution. Local calculations isolate those mechanics. A full experiment additionally needs its data, fitting procedure, and held-out results. Keeping those evidence types separate makes a failed comparison easier to diagnose.</p>
<p>A small tensor check can run without the complete dataset or training budget of a full experiment. The <a href="#sec-m2-c24-env">supporting notebooks</a> contain larger cases. The protocols below extract the decisions that determine whether their results can be interpreted: data boundaries, preprocessing, initialization, computation budget, metrics, and retained evidence.</p>
<div id="fig-m2-c24-f01" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Seven panels show classifiers, attention, adapters, recurrence, counts, and vision tasks. The count illustration mixes one-token and two-token histories.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m2-c24-f01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m2-c24-f01.png" class="img-fluid figure-img" style="width:5.9in" alt="Seven panels show classifiers, attention, adapters, recurrence, counts, and vision tasks. The count illustration mixes one-token and two-token histories.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m2-c24-f01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.1: Panels associate seven lab tasks with input and output sketches.
</figcaption>
</figure>
</div>
<section id="sec-m2-c24-env" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sec-m2-c24-env">Environment and supporting notebooks</h2>
<p>An experiment cannot be reproduced from a model name and final score alone. Its record needs the Python and package versions, operating system, device, driver and accelerator runtime when used, seeds, and numerical types. Retain model and tokenizer revisions, data version, split construction, preprocessing, training settings, and decoding choices. A seed does not guarantee identical results across different hardware or kernels.</p>
<div id="tbl-m2-c24-t01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m2-c24-t01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;24.1: Supporting notebooks and the calculations or experiments they extend.
</figcaption>
<div aria-describedby="tbl-m2-c24-t01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Supporting notebook</th>
<th>Teaching role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="../downloads/pytorch-basics.ipynb">PyTorch basics</a></td>
<td>Tensor creation, layout, indexing, and numerical practice</td>
</tr>
<tr class="even">
<td><a href="../downloads/gradients-logistic-regression.ipynb">Gradients and logistic regression</a></td>
<td>Manual derivatives and a training loop</td>
</tr>
<tr class="odd">
<td><a href="../downloads/word-embeddings.ipynb">Word embeddings</a></td>
<td>Corpus fitting, vector queries, and projection inspection</td>
</tr>
<tr class="even">
<td><a href="../downloads/logistic-assignment.ipynb">Logistic regression and optimizer comparison</a></td>
<td>SST-2 and optimizer comparisons, §24.1</td>
</tr>
<tr class="odd">
<td><a href="../downloads/text-and-recurrence-assignment.ipynb">Text classification and recurrence</a></td>
<td>AG News classification and Character LSTM labs, §§24.2 and 24.5</td>
</tr>
<tr class="even">
<td><a href="../downloads/attention-and-finetuning.ipynb">Attention and fine-tuning</a></td>
<td>Controlled heads and audience adaptation, §§24.3–24.4</td>
</tr>
<tr class="odd">
<td><a href="../downloads/ngram-tutorial.ipynb">N-gram language modeling</a></td>
<td>Counts, generation, and reload, §24.6</td>
</tr>
<tr class="even">
<td><a href="../downloads/multimodal-assignment.ipynb">Multimodal inference</a></td>
<td>Captioning and visual questions, §24.7</td>
</tr>
<tr class="odd">
<td><a href="../downloads/optional-pytorch-gpu.ipynb">PyTorch on GPU</a></td>
<td>Device and kernel experiments under their original environment</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The downloadable notebooks are unchanged snapshots of the supplied files. Their outputs are historical source results, not results of the code in this book. Open them in an existing compatible notebook environment and inspect dependencies before execution. A package installed for one notebook does not establish compatibility with every other model path.</p>
<p>The local tensor checks use <code>PyTorch</code> 2.12 with ordinary float32 CPU defaults, except where their code selects a type or device. They need no large model downloads. Full experiments may require datasets, pretrained weights, network access, or supported accelerator hardware. When unavailable, retain the failed step and its cause as unexecuted work rather than substituting a toy result.</p>
<p>Each experiment record should connect inputs, intermediate values, parameter changes, metrics, and errors. A <span class="definition-term" data-custom-style="Definition Term"><strong>trace</strong></span> is this ordered account of a computation’s values and state changes. Its <span class="definition-term" data-custom-style="Definition Term"><strong>implementation mapping</strong></span> relates mathematical objects to code objects, axes, dtype, and device. Retain the outputs, relevant plots, and explanations. Give each plot a title and label every curve or point group. Comparisons need common axis scales. An unavailable or unexecuted branch remains unexecuted evidence. These records make the conclusion traceable to the experiment that supports it.</p>
<p>The PyTorch basics notebook supplies tensor creation, seeds, indexing, and reshaping practice. Its recorded sequence uses seed 8436, Gaussian samples with mean zero and standard deviation two, uniform samples from negative two to two, and 500 Poisson draws with rate one. Reproducing a later random sample requires the preceding draws as well as the seed because each draw advances the generator state. Its <code>torch.Tensor(1000)</code> allocation is uninitialized and must be filled before its values are used. A ten-bin histogram over values from zero through ten displays only the draws in that range. The Poisson distribution can still produce larger values. These are array-generation checks, not measured neural initialization results.</p>
<p>The gradient source notebook connects hand calculations to logistic fitting. The word-embedding source notebook describes fitting CBOW vectors with <code>min_count=100</code>, <code>window=5</code>, and <code>vector_size=100</code> on roughly 25,000 computational-linguistics abstracts collected before mid-April 2021. Its <code>/content/arxiv.csv</code> corpus is not bundled, so reproducing the recorded neighbors requires that data or a declared replacement. Its inspection prompts compare <code>nmt</code> with <code>smt</code> and <code>ner</code>, retrieve neighbors of <code>bert</code>, query <code>transformer + lstm - bert</code>, and compare <code>tree</code> with <code>tree - syntax</code>. Record the corpus, preprocessing, vocabulary, Gensim version, settings, query, and seed with any result. The separate three-sentence check in §14.1 uses Gensim 4.4.0, Skip-gram, and supplied local text.</p>
<p>An accelerator comparison first needs to establish which device can run the calculation. In the <a href="../downloads/optional-pytorch-gpu.ipynb">optional GPU notebook</a>, check <code>torch.cuda.is_available()</code> and <code>torch.cuda.device_count()</code> before choosing a CUDA device. For a selected available device, record <code>get_device_name(device)</code>, <code>get_device_capability(device)</code>, and <code>memory_allocated(device)</code> from <code>torch.cuda</code>. These report the hardware name, compute-capability version, and bytes currently allocated to tensors. Compute capability identifies a CUDA hardware feature version used to check instruction and compiled-kernel compatibility. It is not a measured speed or a count of cores. They are separate from total device memory. If CUDA is unavailable, record that condition and use a declared CPU comparison or leave the accelerator run unexecuted.</p>
<p>The matrix-vector workload uses a float32 matrix with 100,000 rows and 100 columns, and a vector of width 100. The PyTorch and NumPy timing cells specify 100 loops and three repeats. The NumPy inputs are copied to the CPU before its timed <code>np.dot</code> call. The notebook reports historical ratios of about nine for an earlier comparison compiled with <code>Numba</code>, a Python compiler for numerical functions, and about 100 for PyTorch against NumPy. These ratios describe that hardware and measurement setup. A new result requires the synchronization, transfer boundary, and repeated-accumulation checks in §23.6. The notebook also contains kernel implementations for separate study. Kernel tuning is outside the scope of this book.</p>
</section>
<section id="sec-m2-c24-s01" class="level2" data-number="24.1">
<h2 data-number="24.1" class="anchored" data-anchor-id="sec-m2-c24-s01"><span class="header-section-number">24.1</span> Logistic regression and controlled optimizer comparisons</h2>
<p>A classifier experiment needs an update that matches its loss before optimizer settings can be compared. The local check isolates two feature rows. The <a href="../downloads/logistic-assignment.ipynb">logistic regression and optimizer lab</a> then extends that calculation to SST-2 sentiment data and controlled training comparisons.</p>
<p>For one binary logit per row, the shape contract is</p>
<p><span id="eq-m2-c24-e01"><span class="math display">\[
X\in\mathbb{R}^{B\times F},\quad w\in\mathbb{R}^{F},\quad z=Xw+b\in\mathbb{R}^{B}
\tag{24.1}\]</span></span></p>
<p>Here <span class="math inline">\(X\)</span> has <span class="math inline">\(B\)</span> example rows and <span class="math inline">\(F\)</span> features, <span class="math inline">\(w\)</span> has width <span class="math inline">\(F\)</span>, and scalar <span class="math inline">\(b\)</span> is shared. With <span class="math inline">\(B=2,F=5\)</span>, the product gives two logits. That shape example is separate from the two-feature code below.</p>
<p>For labels <span class="math inline">\(y_i\in\{0,1\}\)</span> and positive probabilities <span class="math inline">\(p_i=\sigma(z_i)\)</span>, the mean objective is</p>
<p><span id="eq-m2-c24-e02"><span class="math display">\[
L=-\frac{1}{B}\sum_{i=1}^{B}\left[y_i\log p_i+(1-y_i)\log(1-p_i)\right],\quad p_i=\sigma(z_i)
\tag{24.2}\]</span></span></p>
<p>The divisor requires <span class="math inline">\(B&gt;0\)</span>. Labels <span class="math inline">\((1,0)\)</span> and probabilities <span class="math inline">\((0.8,0.25)\)</span> give <span class="math inline">\([-\log0.8-\log0.75]/2\approx0.255413\)</span> nats, or 0.255. The second target uses the negative-class probability. The stable library call receives logits, not thresholded decisions.</p>
<p>The runnable local code computes logits, loss, and gradients without applying an optimizer step.</p>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: Logistic-regression forward, loss, and backward checks</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m2-c24-c01"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m2-c24-c01-1"><a href="#lst-m2-c24-c01-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="lst-m2-c24-c01-2"><a href="#lst-m2-c24-c01-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c01-3"><a href="#lst-m2-c24-c01-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Rows are examples; columns are features.</span></span>
<span id="lst-m2-c24-c01-4"><a href="#lst-m2-c24-c01-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> torch.tensor([[<span class="fl">1.0</span>, <span class="fl">0.0</span>], [<span class="fl">0.0</span>, <span class="fl">1.0</span>]])</span>
<span id="lst-m2-c24-c01-5"><a href="#lst-m2-c24-c01-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> torch.tensor([<span class="fl">1.0</span>, <span class="fl">0.0</span>])</span>
<span id="lst-m2-c24-c01-6"><a href="#lst-m2-c24-c01-6" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> torch.tensor([<span class="fl">0.2</span>, <span class="op">-</span><span class="fl">0.1</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m2-c24-c01-7"><a href="#lst-m2-c24-c01-7" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> torch.tensor(<span class="fl">0.0</span>, requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m2-c24-c01-8"><a href="#lst-m2-c24-c01-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c01-9"><a href="#lst-m2-c24-c01-9" aria-hidden="true" tabindex="-1"></a><span class="co"># The affine score is the logistic-regression logit.</span></span>
<span id="lst-m2-c24-c01-10"><a href="#lst-m2-c24-c01-10" aria-hidden="true" tabindex="-1"></a>logits <span class="op">=</span> X <span class="op">@</span> w <span class="op">+</span> b</span>
<span id="lst-m2-c24-c01-11"><a href="#lst-m2-c24-c01-11" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> torch.nn.functional.binary_cross_entropy_with_logits(logits, y)</span>
<span id="lst-m2-c24-c01-12"><a href="#lst-m2-c24-c01-12" aria-hidden="true" tabindex="-1"></a>loss.backward()</span>
<span id="lst-m2-c24-c01-13"><a href="#lst-m2-c24-c01-13" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> logits.shape <span class="op">==</span> (<span class="dv">2</span>,)</span>
<span id="lst-m2-c24-c01-14"><a href="#lst-m2-c24-c01-14" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> w.grad.shape <span class="op">==</span> w.shape</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Its logits are <span class="math inline">\((0.2,-0.1)\)</span>. Their probabilities are approximately <span class="math inline">\((0.549834,0.475021)\)</span>, and the mean loss is approximately 0.621268. The manual mean weight gradient is <span class="math inline">\((p-y)/2\approx(-0.225083,0.237510)\)</span> because <span class="math inline">\(X\)</span> is the identity. The bias gradient sums those entries, giving approximately 0.012427.</p>
<p>Compare these derivatives with <code>.grad</code> using an appropriate floating-point tolerance. A separate plain-SGD check at rate 0.1 would give weights approximately <span class="math inline">\((0.222508,-0.123751)\)</span> and bias <span class="math inline">\(-0.001243\)</span>. It needs an actual update and a new forward call. The existing assertions check shapes, not those values or an update.</p>
<p><strong>Conclusion:</strong> The supplied example makes gradient signs and the mean divisor inspectable. It cannot establish convergence or sentiment quality.</p>
<p>The <a href="../downloads/gradients-logistic-regression.ipynb">gradient notebook</a> supplies an intermediate experiment before the text classifier. It generates 1,000 two-dimensional examples around centers <code>[-3,-3]</code> and <code>[0,0]</code>, with <code>cluster_std=1.25</code>. Convert features to float32 and labels to a <code>[1000,1]</code> column. A <code>[2,1]</code> weight column and shared bias produce one probability per row. First compare the prediction surfaces for different weights and biases. Set both weight entries to 1 while retaining the current bias, then set the bias to 3. Compare equal weight entries of 0.33 with bias 1 against equal weight entries of 5 with bias 15. Retain each prediction surface beside the reference labels. Restore parameters that record gradients before fitting. Record the data-generation and parameter-initialization seeds.</p>
<p>Use up to 1,000 full-data updates at rate 0.1. Store the loss before each update, change weights and bias under <code>torch.no_grad()</code>, clear both gradient buffers, and record every twentieth loop index. With stopping threshold <code>1e-5</code>, first require finite losses and at least two recorded values. Stop only when the nonnegative improvement satisfies <span class="math inline">\(0\leq L_{t-1}-L_t&lt;10^{-5}\)</span>. Record an increase or nonfinite value as a separate diagnostic event. Calculate the stable loss from logits as in §8.1 rather than taking logs of rounded sigmoid probabilities.</p>
<p>Plot the loss history against the update index, then recalculate predictions from the final parameters before the classification report and accuracy calculation. Use one declared threshold convention throughout, including equality at 0.5. The quantity <code>exp(-mean log-loss)</code> is the geometric mean of the reference-class probabilities. Their arithmetic mean is at least as large, with equality when all those probabilities are equal. State which summary a reported value represents.</p>
<p>This experiment connects a checked gradient to a complete fitting loop and its final metrics. The sentiment experiment adds sparse text features, mini-batches, and validation comparisons. The following protocol defines the larger comparison.</p>
<p>The larger comparison uses the fixed <code>SetFit/sst2</code> revision and its training and validation splits. Apply one recorded cleaning rule to both splits, fit the vocabulary on training text only, and transform validation text with that saved vocabulary. The notebook’s rule lowercases text, replaces hyphens with spaces, retains ASCII letters, digits, whitespace, and <code>. , ! ?</code>, then collapses repeated whitespace. Because splitting occurs on whitespace, <code>good!</code> and <code>good</code> remain different tokens. Record split sizes and class proportions before fitting. A sparse bag-of-words representation can retain up to 10,000 frequent training tokens. Corpus frequency determines which entries enter the vocabulary, while each document stores its own counts. With vocabulary <code>[movie,good,bad]</code>, <code>good movie good</code> becomes <code>[1,2,0]</code>.</p>
<p>The one-output sigmoid formulation and the two-class softmax formulation should agree on their binary decisions when they use corresponding parameters and the same threshold convention. Compare both tensor calculations with stable library losses and derivatives. A decision rule such as <code>p &gt;= 0.5</code> affects reported classes, while the training objective still uses probabilities or logits. The comparison should expose where a naive logarithm or exponential fails and why subtracting the largest logit preserves the softmax probabilities.</p>
<p>Initialization and array orientation are separate experimental choices. Record whether weights begin at zero, from a small random distribution, or from a supplied tensor, together with their seed, type, and shape. A <code>[F,1]</code> weight column and an <code>[F]</code> weight vector return differently shaped logits, so outputs and targets must follow the chosen convention. Mini-batch fitting should shuffle training rows, keep the full feature matrix sparse, and convert only a selected batch when a dense tensor is required. Preserve independent parameter snapshots and per-epoch training and validation measures. Report prediction loss separately from an objective that includes a penalty.</p>
<p>A controlled search crosses learning rates <code>[0.01, 0.03, 0.1, 0.3, 1.0]</code> with batch sizes <code>[50, 100, 200]</code>. The resulting 15 runs need a common update budget, metric, and validation rule, with failures retained rather than removed. A matched table or heatmap can then show which settings converge, diverge, or remain unstable without implying that the best observed setting is universal.</p>
<p>The L1 comparison keeps rate and batch size fixed while varying penalty strength across <code>[0, 1e-4, 1e-3, 1e-2, 1e-1]</code>. Count coefficients under one declared tolerance and retain validation outcomes beside training measures. Ordinary subgradient SGD can cross zero without producing exact zeros, so coefficient sparsity must be measured rather than inferred from the presence of an L1 term. A separate proximal-L1 comparison uses the soft-thresholding rule from <a href="ch-m2-c10.html#sec-m2-c10-s06">§10.6</a> and answers a different question about exact zeros.</p>
<p>Optimizer behavior can be isolated on the bowl <span class="math inline">\(x^2+4y^2\)</span> and the six-hump camel function <span class="math inline">\(f(x,y)=(4-2.1x^2+x^4/3)x^2+xy+(-4+4y^2)y^2\)</span>. The second surface has two global minima near <span class="math inline">\((0.0898,-0.7126)\)</span> and <span class="math inline">\((-0.0898,0.7126)\)</span>, with value about <span class="math inline">\(-1.0316\)</span>, as well as other local minima. GD, Momentum, AdaGrad, and Adam should begin from the same declared point within a comparison and use matched budgets and display axes. Their parameter paths, objective histories, oscillation, and local-minimum behavior show why the observed results differ, without supporting a universal winner.</p>
<p>In float32, <span class="math inline">\(1-10^{-15}\)</span> rounds to one, so probability clamping at that epsilon still permits <span class="math inline">\(\log0\)</span>. Calculate binary loss from logits with a stable expression, such as <span class="math inline">\(\log(1+e^z)-yz\)</span> evaluated through a stable log-sum operation, and compare against §8.1. Keep the full count-feature matrix sparse. A mostly zero dense array still allocates its zero entries.</p>
<p>Match the coordinate-grid axes to the objective function’s indexing. The camel surface can fall below <span class="math inline">\(-1\)</span>, where <code>log1p</code> is undefined, so use raw contours or a display transformation defined over the whole plotted range. Pair each stored loss with the parameters that produced it. When recording post-update parameters, recompute their loss or label the stored loss as pre-update. Sample row indices from <span class="math inline">\(0\)</span> through <span class="math inline">\(n-1\)</span> with the upper bound <span class="math inline">\(n\)</span> excluded.</p>
<p>Use validation evidence to compare settings. Keep any final test separate from those decisions. The same gradient and evidence checks can now support a comparison of text representations.</p>
</section>
<section id="sec-m2-c24-s02" class="level2" data-number="24.2">
<h2 data-number="24.2" class="anchored" data-anchor-id="sec-m2-c24-s02"><span class="header-section-number">24.2</span> Tokenizer, embedding, and classifier comparisons</h2>
<p>A better nearest-neighbor display need not improve news classification. The <a href="../downloads/text-and-recurrence-assignment.ipynb">AG News classification lab</a> compares representations through a classifier while retaining the official test set for final evaluation. For this lab, use <code>fancyzhx/ag_news</code> and pass the revision in the dataset reference to <code>load_dataset</code>. This snapshot has 120,000 training records and 7,600 test records. Each record has a <code>text</code> string and a <code>label</code>: 0 for World, 1 for Sports, 2 for Business, or 3 for Sci/Tech.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>The runnable local check starts with two equal-length, already supplied token-vector sequences. It averages each sequence, then applies a random MLP to four class logits.</p>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: Pooled token vectors and four-class MLP logits</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m2-c24-c02"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m2-c24-c02-1"><a href="#lst-m2-c24-c02-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="lst-m2-c24-c02-2"><a href="#lst-m2-c24-c02-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="lst-m2-c24-c02-3"><a href="#lst-m2-c24-c02-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c02-4"><a href="#lst-m2-c24-c02-4" aria-hidden="true" tabindex="-1"></a><span class="co"># A real run obtains these token vectors from the trained Word2Vec model.</span></span>
<span id="lst-m2-c24-c02-5"><a href="#lst-m2-c24-c02-5" aria-hidden="true" tabindex="-1"></a>token_vectors <span class="op">=</span> torch.tensor([</span>
<span id="lst-m2-c24-c02-6"><a href="#lst-m2-c24-c02-6" aria-hidden="true" tabindex="-1"></a>    [[<span class="fl">1.0</span>, <span class="fl">0.0</span>, <span class="fl">0.5</span>], [<span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">0.0</span>]],</span>
<span id="lst-m2-c24-c02-7"><a href="#lst-m2-c24-c02-7" aria-hidden="true" tabindex="-1"></a>    [[<span class="fl">0.0</span>, <span class="fl">1.0</span>, <span class="fl">0.5</span>], [<span class="fl">1.0</span>, <span class="fl">0.5</span>, <span class="fl">0.0</span>]],</span>
<span id="lst-m2-c24-c02-8"><a href="#lst-m2-c24-c02-8" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="lst-m2-c24-c02-9"><a href="#lst-m2-c24-c02-9" aria-hidden="true" tabindex="-1"></a>article_vectors <span class="op">=</span> token_vectors.mean(dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="lst-m2-c24-c02-10"><a href="#lst-m2-c24-c02-10" aria-hidden="true" tabindex="-1"></a>classifier <span class="op">=</span> nn.Sequential(nn.Linear(<span class="dv">3</span>, <span class="dv">8</span>), nn.ReLU(), nn.Linear(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="lst-m2-c24-c02-11"><a href="#lst-m2-c24-c02-11" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> torch.tensor([<span class="dv">0</span>, <span class="dv">2</span>])</span>
<span id="lst-m2-c24-c02-12"><a href="#lst-m2-c24-c02-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c02-13"><a href="#lst-m2-c24-c02-13" aria-hidden="true" tabindex="-1"></a>logits <span class="op">=</span> classifier(article_vectors)</span>
<span id="lst-m2-c24-c02-14"><a href="#lst-m2-c24-c02-14" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> nn.CrossEntropyLoss()(logits, labels)</span>
<span id="lst-m2-c24-c02-15"><a href="#lst-m2-c24-c02-15" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> article_vectors.shape <span class="op">==</span> (<span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="lst-m2-c24-c02-16"><a href="#lst-m2-c24-c02-16" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> logits.shape <span class="op">==</span> (<span class="dv">2</span>, <span class="dv">4</span>)</span>
<span id="lst-m2-c24-c02-17"><a href="#lst-m2-c24-c02-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(loss.item())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The document vectors are <code>[[0.75,0.5,0.25],[0.5,0.75,0.25]]</code>, with shape <code>[2,3]</code>. The logits have shape <code>[2,4]</code>, and loss is scalar. Random head weights make its value variable. There is no padding here. Unequal sequences need <a href="ch-m2-c13.html#sec-m2-c13-s03">masked pooling</a> or another justified aggregation policy.</p>
<p><strong>Conclusion:</strong> The check joins a supplied representation to an MLP loss. It neither learns embeddings nor evaluates a news classifier. The full comparison preserves these requirements:</p>
<p>Keep AG News’s official test split untouched and form any validation subset from training data. Inspect the text and label fields and record split sizes before fitting. Preprocessing, tokenizers, and word vectors use training text only. The four reference categories remain World, Sports, Business, and Sci/Tech under the dataset’s recorded integer mapping.</p>
<p>BPE and WordPiece can use the same example vocabulary budget, such as 10,000 entries, while producing different segmentations and unknown-token behavior. Compare their token sequences and lengths on the same sentences, including unfamiliar words, before choosing one for the classifier. The fitted tokenizer and its preprocessing must be saved together so later comparisons use the same mapping.</p>
<p>Skip-gram and CBOW can then be compared at widths 50, 100, and 200 using the same tokenized training text. Record the actual learned vocabulary because a tokenizer entry may be excluded when its embedding-training frequency is below <code>min_count</code>. Neighbor queries such as <code>movie</code>, <code>sport</code>, and <code>market</code> can expose local vector behavior, including a query absent from the learned vocabulary. They do not establish which representation improves classification. When classification is the selection criterion, compare the candidate embeddings on development data under the same classifier and computation budget.</p>
<p>Mean, sum, max, or another declared pooling rule converts a variable-length token sequence into a fixed-width document vector. The rule must specify missing vectors and empty inputs. A multilayer classifier can consume the pooled vector, but the pooling discards some or all word-order information. Width, activation, optimizer, rate, batch size, and training duration therefore belong in the experiment record rather than being inferred from the representation alone.</p>
<p>After development choices are fixed, evaluate once on the official test split. Retain accuracy, a labeled confusion matrix, and error records containing the text, reference category, and prediction. An attribution method can support diagnosis if its scope is stated, but the prediction and held-out evidence remain valid even when no attribution method is added.</p>
<p>A batch loss is commonly already a mean. To report an epoch mean, multiply each batch mean by its included example count, sum those products, and divide by the total count. Averaging batch means equally gives a shorter final batch too much weight. Training-batch losses also come from changing parameter versions. To measure one checkpoint’s performance, evaluate that fixed checkpoint over the relevant split with gradients disabled and evaluation mode enabled.</p>
<p>An <span class="definition-term" data-custom-style="Definition Term"><strong>attribution</strong></span> assigns parts of an input a measured contribution under a specified comparison. One possible method keeps the classifier fixed, records its probability for a selected class, then removes one token and recomputes the representation and the same class probability. A drop from 0.80 to 0.55 gives a contribution of 0.25 under that removal. Repeat separately for each position. Removing a token also changes a mean-pooling denominator, so the comparison measures the whole removal operation. Interactions mean these contributions need not add to the original score, and they do not establish a real-world causal effect.</p>
<p>The <code>tokenizers</code> library supplies complete vocabulary trainers for the algorithm comparison. The following offline example uses version 0.22.2, a three-sentence corpus, <code>Whitespace</code> pre-tokenization, and a BPE vocabulary limit of 50. It adds a WordPiece trainer on the same text. These small settings demonstrate the API before the full AG News experiment.</p>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: Training BPE and WordPiece on the same small corpus</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m2-c24-c09"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m2-c24-c09-1"><a href="#lst-m2-c24-c09-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="lst-m2-c24-c09-2"><a href="#lst-m2-c24-c09-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tokenizers <span class="im">import</span> Tokenizer</span>
<span id="lst-m2-c24-c09-3"><a href="#lst-m2-c24-c09-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tokenizers.models <span class="im">import</span> BPE, WordPiece</span>
<span id="lst-m2-c24-c09-4"><a href="#lst-m2-c24-c09-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tokenizers.trainers <span class="im">import</span> BpeTrainer, WordPieceTrainer</span>
<span id="lst-m2-c24-c09-5"><a href="#lst-m2-c24-c09-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tokenizers.pre_tokenizers <span class="im">import</span> Whitespace</span>
<span id="lst-m2-c24-c09-6"><a href="#lst-m2-c24-c09-6" aria-hidden="true" tabindex="-1"></a>corpus <span class="op">=</span> [<span class="st">"I love natural language processing"</span>, <span class="st">"Tokenization is important"</span>, <span class="st">"BPE builds subword units"</span>]</span>
<span id="lst-m2-c24-c09-7"><a href="#lst-m2-c24-c09-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, model, trainer <span class="kw">in</span> [</span>
<span id="lst-m2-c24-c09-8"><a href="#lst-m2-c24-c09-8" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"BPE"</span>, BPE(unk_token<span class="op">=</span><span class="st">"[UNK]"</span>), BpeTrainer(vocab_size<span class="op">=</span><span class="dv">50</span>, special_tokens<span class="op">=</span>[<span class="st">"[UNK]"</span>], show_progress<span class="op">=</span><span class="va">False</span>)),</span>
<span id="lst-m2-c24-c09-9"><a href="#lst-m2-c24-c09-9" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"WordPiece"</span>, WordPiece(unk_token<span class="op">=</span><span class="st">"[UNK]"</span>), WordPieceTrainer(vocab_size<span class="op">=</span><span class="dv">50</span>, special_tokens<span class="op">=</span>[<span class="st">"[UNK]"</span>], show_progress<span class="op">=</span><span class="va">False</span>)),</span>
<span id="lst-m2-c24-c09-10"><a href="#lst-m2-c24-c09-10" aria-hidden="true" tabindex="-1"></a>]:</span>
<span id="lst-m2-c24-c09-11"><a href="#lst-m2-c24-c09-11" aria-hidden="true" tabindex="-1"></a>    tokenizer <span class="op">=</span> Tokenizer(model)</span>
<span id="lst-m2-c24-c09-12"><a href="#lst-m2-c24-c09-12" aria-hidden="true" tabindex="-1"></a>    tokenizer.pre_tokenizer <span class="op">=</span> Whitespace()</span>
<span id="lst-m2-c24-c09-13"><a href="#lst-m2-c24-c09-13" aria-hidden="true" tabindex="-1"></a>    tokenizer.train_from_iterator(corpus, trainer)</span>
<span id="lst-m2-c24-c09-14"><a href="#lst-m2-c24-c09-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(json.dumps({<span class="st">"model"</span>: name, <span class="st">"vocab_size"</span>: tokenizer.get_vocab_size(), <span class="st">"unk_id"</span>: tokenizer.token_to_id(<span class="st">"[UNK]"</span>), <span class="st">"unhappiness"</span>: tokenizer.encode(<span class="st">"unhappiness"</span>).tokens, <span class="st">"training_sentence"</span>: tokenizer.encode(corpus[<span class="dv">0</span>]).tokens}))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>Tokenizer</code> combines a model with preprocessing, and <code>train_from_iterator</code> fits its vocabulary from the supplied strings. Each trainer reserves <code>[UNK]</code>. The printed records identify the fitted vocabulary size, unknown-token ID, and encoded pieces. In this run both vocabularies contain 50 entries and assign ID 0 to <code>[UNK]</code>.</p>
<p>The test word <code>unhappiness</code> contains <code>h</code>, which is absent from this training corpus. BPE retains the known pieces around an unknown marker. WordPiece returns one <code>[UNK]</code> for the whole word under its policy. Repeated WordPiece fits on this tiny corpus produced different vocabularies, so an exact piece sequence must be tied to its fitted tokenizer. Use <code>tokenizer.save(path)</code> to retain the vocabulary, model rules, and preprocessing together before further comparisons.</p>
<p><strong>Conclusion:</strong> Both trainers produce reusable tokenizers from the same training text, but their unknown-word handling differs. A small vocabulary trace establishes how to run the comparison, while the full experiment measures whether the representation helps classification.</p>
<p>Retain training histories and the representation settings beside downstream results. Source-vector arithmetic and projection plots from Chapter 14 remain diagnostic evidence, not substitutes for classification evaluation.</p>
</section>
<section id="sec-m2-c24-s03" class="level2" data-number="24.3">
<h2 data-number="24.3" class="anchored" data-anchor-id="sec-m2-c24-s03"><span class="header-section-number">24.3</span> Attention under a controlled input change</h2>
<p>Changing a word while redrawing every input vector would confound a claimed word-specific effect. A controlled attention comparison uses the same representation mapping and projection matrices, then changes only the intended input.</p>
<p>The <a href="../downloads/attention-and-finetuning.ipynb">attention and fine-tuning notebook</a> uses <code>the cat sat on the mat</code> at width 16 for its example attention calculation, then replaces <code>cat</code> with <code>dog</code> to compare the outputs. These settings illustrate the experiment. The attention calculation must still work for other inputs and widths.</p>
<p>Use the one-head scaled-attention calculation from <a href="ch-m2-c16.html#sec-m2-c16-s01">§16.1</a>. Queries <span class="math inline">\(Q\)</span> index updated positions, keys <span class="math inline">\(K\)</span> index readable positions, and values <span class="math inline">\(V\)</span> supply the mixed content. Width <span class="math inline">\(d_k\)</span> scales dot products. The additive mask <span class="math inline">\(M^{\mathrm{attn}}\)</span> blocks disallowed pairs before softmax, and <span class="math inline">\(O\)</span> contains outputs. With coefficients <span class="math inline">\((0.25,0.75)\)</span> and scalar values <span class="math inline">\((2,6)\)</span>, the output is <span class="math inline">\(0.25(2)+0.75(6)=5\)</span>.</p>
<p>The runnable local code supplies projected arrays directly and applies a causal mask. It does not construct representations of actual words.</p>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: Scaled attention values and row-normalization checks</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m2-c24-c03"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m2-c24-c03-1"><a href="#lst-m2-c24-c03-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="lst-m2-c24-c03-2"><a href="#lst-m2-c24-c03-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c03-3"><a href="#lst-m2-c24-c03-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Two query positions, two key positions, and scalar values.</span></span>
<span id="lst-m2-c24-c03-4"><a href="#lst-m2-c24-c03-4" aria-hidden="true" tabindex="-1"></a>Q <span class="op">=</span> torch.tensor([[<span class="fl">1.0</span>, <span class="fl">0.0</span>], [<span class="fl">0.0</span>, <span class="fl">1.0</span>]])</span>
<span id="lst-m2-c24-c03-5"><a href="#lst-m2-c24-c03-5" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> torch.tensor([[<span class="fl">1.0</span>, <span class="fl">0.0</span>], [<span class="fl">0.0</span>, <span class="fl">1.0</span>]])</span>
<span id="lst-m2-c24-c03-6"><a href="#lst-m2-c24-c03-6" aria-hidden="true" tabindex="-1"></a>V <span class="op">=</span> torch.tensor([[<span class="fl">2.0</span>], [<span class="fl">6.0</span>]])</span>
<span id="lst-m2-c24-c03-7"><a href="#lst-m2-c24-c03-7" aria-hidden="true" tabindex="-1"></a>scale <span class="op">=</span> Q.shape[<span class="op">-</span><span class="dv">1</span>] <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="lst-m2-c24-c03-8"><a href="#lst-m2-c24-c03-8" aria-hidden="true" tabindex="-1"></a>scores <span class="op">=</span> Q <span class="op">@</span> K.T <span class="op">/</span> scale</span>
<span id="lst-m2-c24-c03-9"><a href="#lst-m2-c24-c03-9" aria-hidden="true" tabindex="-1"></a>causal_mask <span class="op">=</span> torch.triu(torch.full_like(scores, <span class="bu">float</span>(<span class="st">"-inf"</span>)), diagonal<span class="op">=</span><span class="dv">1</span>)</span>
<span id="lst-m2-c24-c03-10"><a href="#lst-m2-c24-c03-10" aria-hidden="true" tabindex="-1"></a>masked_scores <span class="op">=</span> scores <span class="op">+</span> causal_mask</span>
<span id="lst-m2-c24-c03-11"><a href="#lst-m2-c24-c03-11" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> torch.softmax(masked_scores, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="lst-m2-c24-c03-12"><a href="#lst-m2-c24-c03-12" aria-hidden="true" tabindex="-1"></a>output <span class="op">=</span> weights <span class="op">@</span> V</span>
<span id="lst-m2-c24-c03-13"><a href="#lst-m2-c24-c03-13" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> scores.shape <span class="op">==</span> (<span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="lst-m2-c24-c03-14"><a href="#lst-m2-c24-c03-14" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> output.shape <span class="op">==</span> (<span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="lst-m2-c24-c03-15"><a href="#lst-m2-c24-c03-15" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> weights[<span class="dv">0</span>, <span class="dv">1</span>].item() <span class="op">==</span> <span class="fl">0.0</span></span>
<span id="lst-m2-c24-c03-16"><a href="#lst-m2-c24-c03-16" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> torch.allclose(weights.<span class="bu">sum</span>(dim<span class="op">=-</span><span class="dv">1</span>), torch.ones(<span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The unmasked score matrix is diagonal with entries <span class="math inline">\(1/\sqrt2\approx0.707107\)</span>. Its masked first row has only the first key available, giving weights <span class="math inline">\((1,0)\)</span> and output 2. The second row gives weights approximately <span class="math inline">\((0.330238,0.669762)\)</span> and output 4.679046. These values complement the code’s shape, masked-zero, and row-sum checks.</p>
<p><strong>Conclusion:</strong> The first query excludes the future value, while the second mixes both. Row normalization applies only when at least one allowed finite score exists. A fully blocked row needs rejection, skipping, or a declared handling policy before normalization.</p>
<p>For the complete notebook task:</p>
<p>The trace retains the token representations and the query, key, and value projection matrices. It records unmasked scores, the mask, masked scores, normalized weights, and output vectors, with query rows and key columns aligned to token positions. Selected values should agree with an independent manual or trusted-library calculation before the heatmap is interpreted.</p>
<p>A controlled input change replaces one content word while keeping the representation rule and every projection fixed. Comparing the changed token’s projected vectors, the affected score row and column, and the downstream outputs identifies the numerical effect. A linguistic explanation remains a hypothesis unless another controlled comparison supports it.</p>
<p>Multiple heads require independently projected queries, keys, and values. Comparing at least two such heads under the same input change can show different weight patterns. Repeating one projection under two labels would only duplicate the same calculation. The recorded arrays can answer whether the word change affected the weights and whether the heads differ, but a heatmap alone does not prove why the model produced a prediction.</p>
<p>This task isolates representation changes. Adapter training additionally needs evidence of which parameters changed and whether held-out answers improved.</p>
</section>
<section id="sec-m2-c24-s04" class="level2" data-number="24.4">
<h2 data-number="24.4" class="anchored" data-anchor-id="sec-m2-c24-s04"><span class="header-section-number">24.4</span> Audience adaptation with two model families</h2>
<p>An adapter parameter count does not establish that an answer suits its intended audience. The <a href="../downloads/attention-and-finetuning.ipynb">fine-tuning notebook</a> requires response-level comparisons for both a causal model and an encoder-decoder model. Their target layouts and adapter targets differ.</p>
<p>The local runnable check counts the factor parameters and tests the first gradient. A separate assertion reconstructs an affine-quantized value. It does not load or train a model.</p>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: LoRA parameter count, usable initialization, and affine dequantization checks</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m2-c24-c04"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m2-c24-c04-1"><a href="#lst-m2-c24-c04-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="lst-m2-c24-c04-2"><a href="#lst-m2-c24-c04-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c04-3"><a href="#lst-m2-c24-c04-3" aria-hidden="true" tabindex="-1"></a><span class="co"># A frozen 4 by 4 weight receives a rank-1 update.</span></span>
<span id="lst-m2-c24-c04-4"><a href="#lst-m2-c24-c04-4" aria-hidden="true" tabindex="-1"></a>d_in, d_out, rank <span class="op">=</span> <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1</span></span>
<span id="lst-m2-c24-c04-5"><a href="#lst-m2-c24-c04-5" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> torch.tensor([[<span class="fl">1.0</span>, <span class="op">-</span><span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">0.5</span>]], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m2-c24-c04-6"><a href="#lst-m2-c24-c04-6" aria-hidden="true" tabindex="-1"></a>B <span class="op">=</span> torch.zeros(d_out, rank, requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m2-c24-c04-7"><a href="#lst-m2-c24-c04-7" aria-hidden="true" tabindex="-1"></a>trainable <span class="op">=</span> A.numel() <span class="op">+</span> B.numel()</span>
<span id="lst-m2-c24-c04-8"><a href="#lst-m2-c24-c04-8" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> trainable <span class="op">==</span> rank <span class="op">*</span> (d_in <span class="op">+</span> d_out)</span>
<span id="lst-m2-c24-c04-9"><a href="#lst-m2-c24-c04-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c04-10"><a href="#lst-m2-c24-c04-10" aria-hidden="true" tabindex="-1"></a><span class="co"># A nonzero first factor and zero second factor preserve the base output.</span></span>
<span id="lst-m2-c24-c04-11"><a href="#lst-m2-c24-c04-11" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.tensor([<span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">3.0</span>, <span class="fl">4.0</span>])</span>
<span id="lst-m2-c24-c04-12"><a href="#lst-m2-c24-c04-12" aria-hidden="true" tabindex="-1"></a>delta <span class="op">=</span> B <span class="op">@</span> (A <span class="op">@</span> x)</span>
<span id="lst-m2-c24-c04-13"><a href="#lst-m2-c24-c04-13" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> torch.allclose(delta, torch.zeros(d_out))</span>
<span id="lst-m2-c24-c04-14"><a href="#lst-m2-c24-c04-14" aria-hidden="true" tabindex="-1"></a>delta.<span class="bu">sum</span>().backward()</span>
<span id="lst-m2-c24-c04-15"><a href="#lst-m2-c24-c04-15" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> torch.count_nonzero(B.grad) <span class="op">&gt;</span> <span class="dv">0</span></span>
<span id="lst-m2-c24-c04-16"><a href="#lst-m2-c24-c04-16" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> torch.count_nonzero(A.grad) <span class="op">==</span> <span class="dv">0</span></span>
<span id="lst-m2-c24-c04-17"><a href="#lst-m2-c24-c04-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c04-18"><a href="#lst-m2-c24-c04-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Affine quantization reconstructs a value from an integer code.</span></span>
<span id="lst-m2-c24-c04-19"><a href="#lst-m2-c24-c04-19" aria-hidden="true" tabindex="-1"></a>scale, q, zero_point <span class="op">=</span> <span class="fl">0.1</span>, <span class="dv">13</span>, <span class="dv">3</span></span>
<span id="lst-m2-c24-c04-20"><a href="#lst-m2-c24-c04-20" aria-hidden="true" tabindex="-1"></a>x_hat <span class="op">=</span> scale <span class="op">*</span> (q <span class="op">-</span> zero_point)</span>
<span id="lst-m2-c24-c04-21"><a href="#lst-m2-c24-c04-21" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> x_hat <span class="op">==</span> <span class="fl">1.0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The four-by-four, width-one factors contain <span class="math inline">\(1(4)+4(1)=8\)</span> trainable values. The chosen nonzero <span class="math inline">\(A\)</span> and zero <span class="math inline">\(B\)</span> make the initial adapter output zero. For the supplied input, <span class="math inline">\(Ax=7\)</span>, so a summed-output gradient reaches <span class="math inline">\(B\)</span> while the gradient of <span class="math inline">\(A\)</span> is initially zero. After <span class="math inline">\(B\)</span> changes, a later update can also reach <span class="math inline">\(A\)</span>. <a href="ch-m2-c20.html#sec-m2-c20-s04">§20.4</a> explains this initialization rule in the full layer.</p>
<p>The separate reconstruction gives <span class="math inline">\(0.1(13-3)=1.0\)</span>. This is affine integer quantization, not an NF4 codebook calculation. Neither assertion measures memory allocated by a quantized model or a completed update.</p>
<p><strong>Conclusion:</strong> The snippet establishes eight trainable factor values and a viable first gradient. It also checks one reconstruction rule. The adaptation experiment needs these additional steps:</p>
<p>A Dolly 15K subset provides questions whose answers can be adapted for child, student, and expert audiences. Preserve the dataset revision and the rule used to select rows. The source notebook’s first-5,000-row selection and its keyword filter are examples of bounded sampling, not universal requirements. Inspect the resulting fields and row counts, including an empty selection, before generating training records.</p>
<p>Each selected question needs three answers that differ by audience rather than length alone. A child answer uses simple, intuitive language. A student answer adds moderate technical detail, while an expert answer is precise and specific to the subject. The source answer must be checked for correctness and suitability before it is rewritten. A separately reviewed held-out set should cover all three levels; the source notebook’s budget of 20 total cases is an inspection set, not a dependable population estimate.</p>
<p>Whatever storage format is used, validate the question, audience level, all answer fields, serialization, reload, and formatting on a small batch before fitting. Held-out questions stay outside training and development choices. A causal model can place question, audience level, and answer in one sequence with a response-target mask. An encoder-decoder model instead places the question and level in the source and the answer in the target. Padding and target alignment must follow the selected model interface.</p>
<p>The comparison uses <code>HuggingFaceTB/SmolLM2-360M-Instruct</code> and <code>google/flan-t5-small</code> as two model families. Four-bit loading and LoRA require separate hardware, numerical-format, adapter-target, and trainable-parameter checks for each architecture. A causal <code>q_proj</code>/<code>v_proj</code> fragment is not an encoder-decoder configuration. Unsupported paths remain unexecuted evidence rather than implied results.</p>
<p>Compare each base and adapted model on the same held-out questions and recorded generation settings. Keep the question, requested audience, reference answer, base output, adapted output, audience fit, clarity, relevance, and source faithfulness together. Apply the <a href="ch-m2-c09.html#sec-m2-c09-s04">hallucination and source-faithfulness criteria from §9.4</a>, separating unsupported or contradictory claims from formatting errors and incomplete answers. Interpret observed changes beside training cost, stored base and adapter payloads, peak memory, rank, and the distinction between prompting, LoRA, and QLoRA.</p>
<p>A limited training run may test an environment, but must be labeled with its actual budget. Report which model paths and held-out cases actually ran.</p>
</section>
<section id="sec-m2-c24-s05" class="level2" data-number="24.5">
<h2 data-number="24.5" class="anchored" data-anchor-id="sec-m2-c24-s05"><span class="header-section-number">24.5</span> Character names, shifted targets, and generation feedback</h2>
<p>A generated character must become the next recurrent input while the corresponding state is carried forward. The <a href="../downloads/text-and-recurrence-assignment.ipynb">Character LSTM lab</a> trains a dinosaur-name model and compares generation choices. It shares a supporting notebook with the AG News classification lab in §24.2. The small check below only calculates candidates from an untrained network.</p>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: Untrained character LSTM states and top-k candidate probabilities</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m2-c24-c05"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m2-c24-c05-1"><a href="#lst-m2-c24-c05-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="lst-m2-c24-c05-2"><a href="#lst-m2-c24-c05-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="lst-m2-c24-c05-3"><a href="#lst-m2-c24-c05-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c05-4"><a href="#lst-m2-c24-c05-4" aria-hidden="true" tabindex="-1"></a>vocab_size, hidden_width <span class="op">=</span> <span class="dv">6</span>, <span class="dv">8</span></span>
<span id="lst-m2-c24-c05-5"><a href="#lst-m2-c24-c05-5" aria-hidden="true" tabindex="-1"></a>inputs <span class="op">=</span> torch.nn.functional.one_hot(</span>
<span id="lst-m2-c24-c05-6"><a href="#lst-m2-c24-c05-6" aria-hidden="true" tabindex="-1"></a>    torch.tensor([[<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>]]),</span>
<span id="lst-m2-c24-c05-7"><a href="#lst-m2-c24-c05-7" aria-hidden="true" tabindex="-1"></a>    vocab_size,</span>
<span id="lst-m2-c24-c05-8"><a href="#lst-m2-c24-c05-8" aria-hidden="true" tabindex="-1"></a>).<span class="bu">float</span>()</span>
<span id="lst-m2-c24-c05-9"><a href="#lst-m2-c24-c05-9" aria-hidden="true" tabindex="-1"></a>lstm <span class="op">=</span> nn.LSTM(vocab_size, hidden_width, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="lst-m2-c24-c05-10"><a href="#lst-m2-c24-c05-10" aria-hidden="true" tabindex="-1"></a>output_head <span class="op">=</span> nn.Linear(hidden_width, vocab_size)</span>
<span id="lst-m2-c24-c05-11"><a href="#lst-m2-c24-c05-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c05-12"><a href="#lst-m2-c24-c05-12" aria-hidden="true" tabindex="-1"></a>states, recurrent_state <span class="op">=</span> lstm(inputs)</span>
<span id="lst-m2-c24-c05-13"><a href="#lst-m2-c24-c05-13" aria-hidden="true" tabindex="-1"></a>logits <span class="op">=</span> output_head(states[:, <span class="op">-</span><span class="dv">1</span>])</span>
<span id="lst-m2-c24-c05-14"><a href="#lst-m2-c24-c05-14" aria-hidden="true" tabindex="-1"></a>top_values, top_ids <span class="op">=</span> torch.topk(logits, k<span class="op">=</span><span class="dv">3</span>, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="lst-m2-c24-c05-15"><a href="#lst-m2-c24-c05-15" aria-hidden="true" tabindex="-1"></a>probabilities <span class="op">=</span> torch.softmax(top_values, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="lst-m2-c24-c05-16"><a href="#lst-m2-c24-c05-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c05-17"><a href="#lst-m2-c24-c05-17" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> states.shape <span class="op">==</span> (<span class="dv">1</span>, <span class="dv">3</span>, hidden_width)</span>
<span id="lst-m2-c24-c05-18"><a href="#lst-m2-c24-c05-18" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> top_ids.shape <span class="op">==</span> (<span class="dv">1</span>, <span class="dv">3</span>)</span>
<span id="lst-m2-c24-c05-19"><a href="#lst-m2-c24-c05-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(top_ids, probabilities)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>One-hot input has shape <code>[1,3,6]</code>, states have shape <code>[1,3,8]</code>, and the final output head produces six logits. <code>topk</code> retains three IDs and softmax normalizes their scores. The printed probabilities sum to one over those candidates. No draw, append, repeated model call, or parameter update occurs.</p>
<p><strong>Conclusion:</strong> The snippet checks a recurrent interface and a filtered candidate distribution. A complete name generator additionally needs learned parameters, token feedback, stopping, and state handling.</p>
<p>Add <code>&lt;</code> and <code>&gt;</code> boundary markers to each name. For example, <code>anna</code> becomes <code>&lt;anna&gt;</code>, so the width-four input <code>&lt;ann</code> has the one-position-shifted target <code>anna</code>. Split complete names or source groups before constructing overlapping windows. Related windows then remain in one split under §9.1’s leakage rule. Fit the character vocabulary on training names, reuse that mapping unchanged for validation, and state how unseen validation characters are handled. Replacing the mapping after IDs have been created would make those IDs inconsistent.</p>
<p>Each input window is paired with its one-character-offset targets. One-hot encoding appends a vocabulary axis to the input axes and must be converted to the dtype and device expected by the LSTM. A fixed batch should expose each layer’s actual dimensions before training. The source configuration uses hidden width 256, two LSTM layers, dropout 0.5, Adam rate 0.001, batch size 64, ten epochs, and gradient clipping at 5. These values define the recorded case rather than a general recommendation.</p>
<p>The LSTM applies dropout between its recurrent layers during training, while a separate dropout operation acts on the last layer’s sequence output before the vocabulary head. Both are disabled in evaluation mode. Training at every position reshapes states from <code>[B,T,256]</code> to <code>[B*T,256]</code>, produces logits <code>[B*T,V]</code>, and pairs them with targets flattened in the same order. The sequence length used in this reshape must match the chosen window width. Record the actual example and update counts rather than inferring them from an epoch setting.</p>
<p>For a two-layer model, both hidden and cell state have shape <code>[2,B,256]</code>, using the current batch size, dtype, and device. Reset them for independent names or windows. Carry them only across deliberate contiguous segments of one stream, with a declared detach policy during training. Carrying state across shuffled unrelated windows would mix their contexts.</p>
<p>Generation encodes a prefix, obtains its state, selects a character, appends it, and feeds that character into the next call with the carried state. It stops at <code>&gt;</code> or a declared length limit and resets before another independent request. Random sampling, top-k sampling, temperature changes, and a greedy baseline can then be compared with fixed prefixes and seeds. Retain the selected settings, generated names, loss histories, and observed repetition or dependency failures.</p>
<p>Assign the result of a device conversion, for example <code>inputs = inputs.to(device)</code>, so inputs and model share a device. Derive batch and sequence sizes from the current batch when reshaping targets and creating states. If a smaller final batch is dropped, record which examples that policy excludes.</p>
<p>For validation, switch to <code>net.eval()</code> and disable gradient recording, then restore training mode for the next training batch. In generation, test the stop marker and length limit after every selected character, including the first. Define the limit as the number of newly generated characters.</p>
<p>The name task has the same next-token alignment as a larger language model. A count predictor instead uses an explicit fixed history, without a learned recurrent state.</p>
</section>
<section id="sec-m2-c24-s06" class="level2" data-number="24.6">
<h2 data-number="24.6" class="anchored" data-anchor-id="sec-m2-c24-s06"><span class="header-section-number">24.6</span> The NLTK count-model tutorial and its extensions</h2>
<p>A count table can expose how one observed history produces probabilities before a neural model is fitted. The <a href="../downloads/ngram-tutorial.ipynb">NLTK notebook</a> demonstrates count-model fitting and generation. Its <code>nltk.lm.MLE</code> model uses the maximum-likelihood principle explained in <a href="ch-m2-c08.html#sec-m2-c08-s01">§8.1</a>, fitting continuation probabilities from their observed relative frequencies. It then generates tokens from that fitted model. Smoothing and held-out perplexity below are book extensions.</p>
<p>The runnable local check uses Python’s standard-library <code>Counter</code>, not <code>nltk</code>. It counts bigrams in two boundary-padded sentences.</p>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: Padded bigram counts and maximum-likelihood probability</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m2-c24-c06"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m2-c24-c06-1"><a href="#lst-m2-c24-c06-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> Counter</span>
<span id="lst-m2-c24-c06-2"><a href="#lst-m2-c24-c06-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c06-3"><a href="#lst-m2-c24-c06-3" aria-hidden="true" tabindex="-1"></a>sentences <span class="op">=</span> [[<span class="st">"&lt;s&gt;"</span>, <span class="st">"the"</span>, <span class="st">"cat"</span>, <span class="st">"&lt;/s&gt;"</span>], [<span class="st">"&lt;s&gt;"</span>, <span class="st">"the"</span>, <span class="st">"dog"</span>, <span class="st">"&lt;/s&gt;"</span>]]</span>
<span id="lst-m2-c24-c06-4"><a href="#lst-m2-c24-c06-4" aria-hidden="true" tabindex="-1"></a>bigrams <span class="op">=</span> Counter(</span>
<span id="lst-m2-c24-c06-5"><a href="#lst-m2-c24-c06-5" aria-hidden="true" tabindex="-1"></a>    (left, right)</span>
<span id="lst-m2-c24-c06-6"><a href="#lst-m2-c24-c06-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> sentence <span class="kw">in</span> sentences</span>
<span id="lst-m2-c24-c06-7"><a href="#lst-m2-c24-c06-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> left, right <span class="kw">in</span> <span class="bu">zip</span>(sentence, sentence[<span class="dv">1</span>:])</span>
<span id="lst-m2-c24-c06-8"><a href="#lst-m2-c24-c06-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="lst-m2-c24-c06-9"><a href="#lst-m2-c24-c06-9" aria-hidden="true" tabindex="-1"></a>contexts <span class="op">=</span> Counter(left <span class="cf">for</span> left, _ <span class="kw">in</span> bigrams.elements())</span>
<span id="lst-m2-c24-c06-10"><a href="#lst-m2-c24-c06-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c06-11"><a href="#lst-m2-c24-c06-11" aria-hidden="true" tabindex="-1"></a>probability <span class="op">=</span> bigrams[(<span class="st">"the"</span>, <span class="st">"cat"</span>)] <span class="op">/</span> contexts[<span class="st">"the"</span>]</span>
<span id="lst-m2-c24-c06-12"><a href="#lst-m2-c24-c06-12" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> probability <span class="op">==</span> <span class="fl">0.5</span></span>
<span id="lst-m2-c24-c06-13"><a href="#lst-m2-c24-c06-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(bigrams, probability)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The context <code>the</code> has two continuations, one <code>cat</code> and one <code>dog</code>, giving <span class="math inline">\(P(\mathrm{cat}\mid\mathrm{the})=1/2\)</span>. Its numerator and denominator refer to the same one-token history.</p>
<p><strong>Conclusion:</strong> The ratio is defined for this observed history. An unseen continuation has zero MLE probability, and an unseen history has a zero denominator in the direct count ratio. Library fallback behavior must be checked separately.</p>
<p>The NLTK interface adds vocabulary handling and a stored model to this count calculation. The next example uses <code>nltk</code> 3.9.2 and <code>dill</code> 0.4.1 on the same two short sentences, now with trigram histories. The code fits its counts from these local sentences without downloading a corpus or loading pretrained weights.</p>
<p><code>pad_both_ends</code> adds two <code>&lt;s&gt;</code> tokens and two <code>&lt;/s&gt;</code> tokens for order three. These boundary markers are modeled sentence content, unlike dense-batch placeholders excluded by a loss mask. <code>padded_everygram_pipeline</code> supplies one iterator over sentence n-grams of lengths one through three and another over vocabulary tokens. Both consume the original sentence collection, so the example keeps that collection as a reusable list. Inspecting and exhausting an iterator requires creating a fresh one before fitting.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>The tutorial first uses two unequal sentences, <code>['a','b','c']</code> and <code>['a','c','d','c','e','f']</code>. Inspect unpadded bigrams of the first sentence and trigrams of the second to expose the different history lengths before boundary markers are added. Inspect the first sentence with one marker at each end for bigrams and two for trigrams. Then inspect <code>everygrams</code> up to length two and flatten both bigram-padded sentences for the vocabulary stream. Finally, materialize each training sentence’s n-gram iterator and the vocabulary iterator from <code>padded_everygram_pipeline(2, text)</code>. Recreate both iterators before fitting. These inspections explain what is counted. They do not pad the unequal sentences into a dense tensor batch.</p>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: NLTK trigram counts, bit-based scores, and a saved-model round trip</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m2-c24-c08"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m2-c24-c08-1"><a href="#lst-m2-c24-c08-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> io <span class="im">import</span> BytesIO</span>
<span id="lst-m2-c24-c08-2"><a href="#lst-m2-c24-c08-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> dill</span>
<span id="lst-m2-c24-c08-3"><a href="#lst-m2-c24-c08-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nltk.lm <span class="im">import</span> MLE</span>
<span id="lst-m2-c24-c08-4"><a href="#lst-m2-c24-c08-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nltk.lm.preprocessing <span class="im">import</span> pad_both_ends, padded_everygram_pipeline</span>
<span id="lst-m2-c24-c08-5"><a href="#lst-m2-c24-c08-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c08-6"><a href="#lst-m2-c24-c08-6" aria-hidden="true" tabindex="-1"></a>sentences <span class="op">=</span> [[<span class="st">"the"</span>, <span class="st">"cat"</span>], [<span class="st">"the"</span>, <span class="st">"dog"</span>]]</span>
<span id="lst-m2-c24-c08-7"><a href="#lst-m2-c24-c08-7" aria-hidden="true" tabindex="-1"></a>order <span class="op">=</span> <span class="dv">3</span></span>
<span id="lst-m2-c24-c08-8"><a href="#lst-m2-c24-c08-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>([<span class="bu">list</span>(pad_both_ends(s, n<span class="op">=</span>order)) <span class="cf">for</span> s <span class="kw">in</span> sentences])</span>
<span id="lst-m2-c24-c08-9"><a href="#lst-m2-c24-c08-9" aria-hidden="true" tabindex="-1"></a>training, vocabulary <span class="op">=</span> padded_everygram_pipeline(order, sentences)</span>
<span id="lst-m2-c24-c08-10"><a href="#lst-m2-c24-c08-10" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> MLE(order)</span>
<span id="lst-m2-c24-c08-11"><a href="#lst-m2-c24-c08-11" aria-hidden="true" tabindex="-1"></a>model.fit(training, vocabulary)</span>
<span id="lst-m2-c24-c08-12"><a href="#lst-m2-c24-c08-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c08-13"><a href="#lst-m2-c24-c08-13" aria-hidden="true" tabindex="-1"></a>history <span class="op">=</span> (<span class="st">"&lt;s&gt;"</span>, <span class="st">"the"</span>)</span>
<span id="lst-m2-c24-c08-14"><a href="#lst-m2-c24-c08-14" aria-hidden="true" tabindex="-1"></a>count <span class="op">=</span> model.counts[history][<span class="st">"cat"</span>]</span>
<span id="lst-m2-c24-c08-15"><a href="#lst-m2-c24-c08-15" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> model.context_counts(history).N()</span>
<span id="lst-m2-c24-c08-16"><a href="#lst-m2-c24-c08-16" aria-hidden="true" tabindex="-1"></a>score <span class="op">=</span> model.score(<span class="st">"cat"</span>, history)</span>
<span id="lst-m2-c24-c08-17"><a href="#lst-m2-c24-c08-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(count, total, score)</span>
<span id="lst-m2-c24-c08-18"><a href="#lst-m2-c24-c08-18" aria-hidden="true" tabindex="-1"></a>targets <span class="op">=</span> [history <span class="op">+</span> (<span class="st">"cat"</span>,)]</span>
<span id="lst-m2-c24-c08-19"><a href="#lst-m2-c24-c08-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.logscore(<span class="st">"cat"</span>, history),</span>
<span id="lst-m2-c24-c08-20"><a href="#lst-m2-c24-c08-20" aria-hidden="true" tabindex="-1"></a>      model.entropy(targets), model.perplexity(targets))</span>
<span id="lst-m2-c24-c08-21"><a href="#lst-m2-c24-c08-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.vocab.lookup(<span class="st">"never_seen"</span>),</span>
<span id="lst-m2-c24-c08-22"><a href="#lst-m2-c24-c08-22" aria-hidden="true" tabindex="-1"></a>      model.score(<span class="st">"never_seen"</span>, history))</span>
<span id="lst-m2-c24-c08-23"><a href="#lst-m2-c24-c08-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c08-24"><a href="#lst-m2-c24-c08-24" aria-hidden="true" tabindex="-1"></a>saved <span class="op">=</span> BytesIO()</span>
<span id="lst-m2-c24-c08-25"><a href="#lst-m2-c24-c08-25" aria-hidden="true" tabindex="-1"></a>dill.dump(model, saved)</span>
<span id="lst-m2-c24-c08-26"><a href="#lst-m2-c24-c08-26" aria-hidden="true" tabindex="-1"></a>saved.seek(<span class="dv">0</span>)</span>
<span id="lst-m2-c24-c08-27"><a href="#lst-m2-c24-c08-27" aria-hidden="true" tabindex="-1"></a>restored <span class="op">=</span> dill.load(saved)</span>
<span id="lst-m2-c24-c08-28"><a href="#lst-m2-c24-c08-28" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> restored.counts[history][<span class="st">"cat"</span>] <span class="op">==</span> count</span>
<span id="lst-m2-c24-c08-29"><a href="#lst-m2-c24-c08-29" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> restored.score(<span class="st">"cat"</span>, history) <span class="op">==</span> score</span>
<span id="lst-m2-c24-c08-30"><a href="#lst-m2-c24-c08-30" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> (count, total, score) <span class="op">==</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="fl">0.5</span>)</span>
<span id="lst-m2-c24-c08-31"><a href="#lst-m2-c24-c08-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c08-32"><a href="#lst-m2-c24-c08-32" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nltk.tokenize.treebank <span class="im">import</span> TreebankWordDetokenizer</span>
<span id="lst-m2-c24-c08-33"><a href="#lst-m2-c24-c08-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c08-34"><a href="#lst-m2-c24-c08-34" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> sentence_text(tokens):</span>
<span id="lst-m2-c24-c08-35"><a href="#lst-m2-c24-c08-35" aria-hidden="true" tabindex="-1"></a>    words <span class="op">=</span> []</span>
<span id="lst-m2-c24-c08-36"><a href="#lst-m2-c24-c08-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> token <span class="kw">in</span> tokens:</span>
<span id="lst-m2-c24-c08-37"><a href="#lst-m2-c24-c08-37" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> token <span class="op">==</span> <span class="st">"&lt;s&gt;"</span>:</span>
<span id="lst-m2-c24-c08-38"><a href="#lst-m2-c24-c08-38" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="lst-m2-c24-c08-39"><a href="#lst-m2-c24-c08-39" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> token <span class="op">==</span> <span class="st">"&lt;/s&gt;"</span>:</span>
<span id="lst-m2-c24-c08-40"><a href="#lst-m2-c24-c08-40" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="lst-m2-c24-c08-41"><a href="#lst-m2-c24-c08-41" aria-hidden="true" tabindex="-1"></a>        words.append(token)</span>
<span id="lst-m2-c24-c08-42"><a href="#lst-m2-c24-c08-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> TreebankWordDetokenizer().detokenize(words)</span>
<span id="lst-m2-c24-c08-43"><a href="#lst-m2-c24-c08-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c08-44"><a href="#lst-m2-c24-c08-44" aria-hidden="true" tabindex="-1"></a>generated <span class="op">=</span> model.generate(<span class="dv">20</span>, text_seed<span class="op">=</span>[<span class="st">"&lt;s&gt;"</span>, <span class="st">"&lt;s&gt;"</span>], random_seed<span class="op">=</span><span class="dv">7</span>)</span>
<span id="lst-m2-c24-c08-45"><a href="#lst-m2-c24-c08-45" aria-hidden="true" tabindex="-1"></a>after_reload <span class="op">=</span> restored.generate(<span class="dv">20</span>, text_seed<span class="op">=</span>[<span class="st">"&lt;s&gt;"</span>, <span class="st">"&lt;s&gt;"</span>], random_seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="lst-m2-c24-c08-46"><a href="#lst-m2-c24-c08-46" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="bu">len</span>(generated) <span class="op">==</span> <span class="bu">len</span>(after_reload) <span class="op">==</span> <span class="dv">20</span></span>
<span id="lst-m2-c24-c08-47"><a href="#lst-m2-c24-c08-47" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> after_reload <span class="op">==</span> model.generate(<span class="dv">20</span>, text_seed<span class="op">=</span>[<span class="st">"&lt;s&gt;"</span>, <span class="st">"&lt;s&gt;"</span>], random_seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="lst-m2-c24-c08-48"><a href="#lst-m2-c24-c08-48" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(generated, sentence_text(generated))</span>
<span id="lst-m2-c24-c08-49"><a href="#lst-m2-c24-c08-49" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(after_reload, sentence_text(after_reload))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The padded sentences are <code>&lt;s&gt; &lt;s&gt; the cat &lt;/s&gt; &lt;/s&gt;</code> and <code>&lt;s&gt; &lt;s&gt; the dog &lt;/s&gt; &lt;/s&gt;</code>. For the two-token history <code>('&lt;s&gt;', 'the')</code>, <code>cat</code> occurs once among two continuations. The first numerical line is therefore <code>1 2 0.5</code>. The next is <code>-1.0 1.0 2.0</code>: log score, mean negative log score over the single supplied target, and perplexity. NLTK uses base-two logarithms here, so these log quantities are in bits. Chapter 8’s natural-log loss for probability 0.5 is about 0.693 nats. Either convention gives perplexity 2 when the matching exponential base is used.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>The default vocabulary cutoff is one. Inspect <code>model.vocab</code> and its length before and after fitting to distinguish an initialized model from one with corpus counts. <code>model.vocab.lookup</code> accepts either a token or a token sequence: known tokens retain their identities, while an unfamiliar token maps to <code>&lt;UNK&gt;</code>. Inspect the source corpus’s first tokenized sentence as the known example, and <code>language is never random lah .</code> split into words as the mixed known/unknown example. The vocabulary’s <code>unk_cutoff</code> sets the minimum occurrence count for a distinct token identity. Configure it before fitting. For example, supply <code>Vocabulary(unk_cutoff=2)</code> to a new <code>MLE</code> model, then call <code>fit</code> with fresh training and vocabulary iterators. Tokens occurring once map to <code>&lt;UNK&gt;</code>, and their n-gram counts are fitted under that identity. Changing the mapping later requires fitting the counts again under the new policy. With this example’s default cutoff, an unseen word maps to <code>&lt;UNK&gt;</code> but that lookup does not create an observed continuation or smoothing probability. The unknown-word line is <code>&lt;UNK&gt; 0.0</code>.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> The <code>dill</code> round trip writes the fitted vocabulary and counts to an in-memory stream and restores them. Its assertions compare the original and restored score and count. Loading a serialized model executes a reconstruction procedure, so use only a trusted saved file.</p>
<p>The example also generates 20 tokens with seed 7, then generates from the restored model with seed 42. <code>text_seed</code> supplies two start markers as the initial history. The conversion to readable text skips <code>&lt;s&gt;</code>, stops at the first <code>&lt;/s&gt;</code>, and uses <code>TreebankWordDetokenizer</code> to join the retained tokens. The 20-token budget limits model draws. The displayed sentence can be shorter because it stops at an end marker. A seed controls sampling for this fitted model, not the quality of the text.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a><a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p><strong>Conclusion:</strong> The fitted model preserves its count ratio through saving and loading, supports generation after reload, and distinguishes unknown-token mapping from smoothing. The token-to-text helper preserves the first sentence’s boundary. This tiny calculation checks those API operations, not the quality of a model fitted to a large corpus.</p>
<p>Inspect <code>model.counts</code> before querying individual entries. For the tutorial’s fitted prose model, <code>model.counts['language']</code> retrieves a unigram count. <code>model.counts[['language']]['is']</code> retrieves a continuation count after one word, and <code>model.counts[['language','is']]['never']</code> after two. Compare these raw counts with <code>model.score('language')</code>, <code>model.score('is', ['language'])</code>, and <code>model.score('never', ['language','is'])</code>: the scores divide by the total count for the relevant history. Check that the no-history scores for unseen <code>lah</code>, <code>leh</code>, and <code>lor</code> equal the score for <code>&lt;UNK&gt;</code>. The vocabulary performs that mapping before scoring. Equality does not imply a positive probability. These source-corpus inspections are separate from the two-sentence calculation above.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>The generation loop from §7.1 also applies to a count model. Each prediction uses at most the preceding <span class="math inline">\(n-1\)</span> tokens from §3.4, so text outside that history cannot influence its next-token distribution. Locally plausible continuations can therefore lose an earlier subject or constraint.</p>
<p>The downloadable tutorial fits its first trigram model to the prose file <code>language-never-random.txt</code>. It reads an existing UTF-8 cache or downloads and saves the <a href="https://gist.githubusercontent.com/alvations/53b01e4076573fea47c6057120bb017a/raw/b01ff96a5f76848450e648f35da6497ca9454e4a/language-never-random.txt">pinned text linked by the source</a>. Its tokenizer check first tries NLTK sentence and word tokenization. The fallback uses a regular-expression sentence splitter and <code>ToktokTokenizer</code>. It lowercases the prose tokens before fitting. Record which tokenizer path ran, inspect the first 500 raw characters beside the first tokenized sentence, and retain the resulting tokens. A fallback can change the counts even when the downloaded text is unchanged.</p>
<p>The second corpus comes from the <code>Tweet_Text</code> column of <code>Donald-Tweets!.csv</code>, obtained through the source’s <a href="https://www.kaggle.com/datasets/kingburrito666/better-donald-trump-tweets">tweet dataset archive</a>. Load the CSV with <code>pandas.read_csv</code> and inspect <code>df.head()</code> to check its table and text column before tokenization. This corpus uses the selected word tokenizer without the prose lowercasing step and fits a separate trigram model. Retain casing, tokens and vocabulary with each corpus. Historical notebook outputs are tied to those original data and preprocessing choices. A replacement corpus requires a separate record rather than an implied reproduction.</p>
<p>The tutorial’s generation calls omit <code>text_seed</code>, so they begin with an empty history and sample the first token from the fitted unigram counts. The local example above instead supplies two start markers. Its generated output is therefore a separate conditional experiment. The source helper <code>generate_sent(model, num_words, random_seed=42)</code> skips generated <code>&lt;s&gt;</code> markers, stops at the first <code>&lt;/s&gt;</code>, and detokenizes the retained tokens. The tutorial saves the prose model to <code>kilgariff_ngram_model.pkl</code> with <code>dill</code> and reloads that file before its repeat generation. This disk save/load path differs from the local example’s in-memory round trip. Preserve the tutorial’s prose <code>(token budget, random seed)</code> cases <code>(20,7)</code>, <code>(28,0)</code>, <code>(20,1)</code>, <code>(20,30)</code> and <code>(20,42)</code>, including <code>(20,42)</code> after saving and loading. Preserve its tweet cases <code>(40,42)</code>, <code>(10,0)</code>, <code>(50,10)</code> and <code>(100,52)</code>. The source pairs raw tokens and cleaned text for its prose <code>(20,7)</code> and <code>(28,0)</code> cases. For additional diagnosis, retain both forms for the other cases too. The token budget limits draws, while the text helper stops at the first end marker. That can produce an empty displayed string. Neither a fixed seed nor a larger budget guarantees a complete sentence.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p>A local check using Python 3.11.9 and NLTK 3.9.2 on the original artificial corpus makes this distinction visible. Fit an order-three MLE model with its default cutoff. With seed 1 and no <code>text_seed</code>, the first generated token is <code>&lt;/s&gt;</code>, so the tutorial’s text helper returns an empty string. The same seed with <code>text_seed=['&lt;s&gt;','&lt;s&gt;']</code> instead starts with <code>a</code>. Removing boundary markers after generation does not supply the missing initial context.</p>
<p>The tutorial lists <code>Lidstone</code>, <code>Laplace</code>, <code>InterpolatedLanguageModel</code> and <code>WittenBellInterpolated</code> as API alternatives, without implementing a smoothing comparison. The <a href="ch-m2-c03.html#sec-m2-c03-s04">add-alpha calculation</a> is a separate book extension. Treat the listed classes as starting points for a chosen extension, not as completed experiments.</p>
<p>For a separate evaluation extension, hold out text before fitting the vocabulary and counts. Declare tokenization, boundary inclusion, unknown handling, and the mean-loss denominator. Compute target log losses and perplexity as in §8.5. An observed event with zero MLE probability gives infinite loss. Smoothing reserves probability but does not lengthen the retained history.</p>
<p>Keeping vocabulary, counts, and evaluation policy fixed isolates the smoothing rule’s effect on held-out loss. Neither finite perplexity nor a plausible generated sample establishes general language understanding.</p>
</section>
<section id="sec-m2-c24-s07" class="level2" data-number="24.7">
<h2 data-number="24.7" class="anchored" data-anchor-id="sec-m2-c24-s07"><span class="header-section-number">24.7</span> Captioning, visual questions, and retrieval evidence</h2>
<p>A caption, an answer to a visual question, and a retrieved object label describe different outputs from an image. The <a href="../downloads/multimodal-assignment.ipynb">multimodal notebook</a> supports retaining the inputs and failures separately for each task.</p>
<p>The local runnable check turns a four-by-four grayscale image into four patches and projects each to width three. It contains no text prompt or generation model.</p>
<div class="publisher-code-caption" data-custom-style="Code Caption">
<p><strong>Code example: Patch tokens as inputs to a vision-language pipeline</strong></p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="lst-m2-c24-c07"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-m2-c24-c07-1"><a href="#lst-m2-c24-c07-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="lst-m2-c24-c07-2"><a href="#lst-m2-c24-c07-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c07-3"><a href="#lst-m2-c24-c07-3" aria-hidden="true" tabindex="-1"></a>image <span class="op">=</span> torch.arange(<span class="fl">16.0</span>).reshape(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">4</span>)</span>
<span id="lst-m2-c24-c07-4"><a href="#lst-m2-c24-c07-4" aria-hidden="true" tabindex="-1"></a>patches <span class="op">=</span> image.unfold(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>).unfold(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="lst-m2-c24-c07-5"><a href="#lst-m2-c24-c07-5" aria-hidden="true" tabindex="-1"></a>patches <span class="op">=</span> patches.contiguous().reshape(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">4</span>)</span>
<span id="lst-m2-c24-c07-6"><a href="#lst-m2-c24-c07-6" aria-hidden="true" tabindex="-1"></a>projection <span class="op">=</span> torch.ones(<span class="dv">4</span>, <span class="dv">3</span>)</span>
<span id="lst-m2-c24-c07-7"><a href="#lst-m2-c24-c07-7" aria-hidden="true" tabindex="-1"></a>patch_tokens <span class="op">=</span> patches <span class="op">@</span> projection</span>
<span id="lst-m2-c24-c07-8"><a href="#lst-m2-c24-c07-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-m2-c24-c07-9"><a href="#lst-m2-c24-c07-9" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> patches.shape <span class="op">==</span> (<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">4</span>)</span>
<span id="lst-m2-c24-c07-10"><a href="#lst-m2-c24-c07-10" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> patch_tokens.shape <span class="op">==</span> (<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">3</span>)</span>
<span id="lst-m2-c24-c07-11"><a href="#lst-m2-c24-c07-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(patch_tokens)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The patches are <code>[0,1,4,5]</code>, <code>[2,3,6,7]</code>, <code>[8,9,12,13]</code>, and <code>[10,11,14,15]</code>. Multiplication by the all-ones <code>[4,3]</code> projection repeats each sum three times. The output rows are <code>(10,10,10)</code>, <code>(18,18,18)</code>, <code>(42,42,42)</code>, and <code>(50,50,50)</code>.</p>
<p><strong>Conclusion:</strong> The output has shape <code>[1,4,3]</code> and preserves the declared patch order. It verifies input conversion, not captioning, VQA, or retrieval accuracy.</p>
<p>For a full model, record the image processor, encoder, projection or fusion, text component, and selection settings. Preserve the original image, processed dimensions, prompt, output IDs, decoded text, and model revision. Resizing and cropping can remove evidence needed by a question.</p>
<p>The captioning protocol permits <code>Salesforce/blip-image-captioning-base</code>, <code>Salesforce/blip-image-captioning-large</code>, <code>microsoft/git-base</code>, or another suitable image-captioning model. Choose one and record its resolved revision.</p>
<p>The <code>transformers</code> library provides task-specific model classes. BLIP captioning pairs <code>BlipProcessor</code>, which prepares image and text inputs, with <code>BlipForConditionalGeneration</code>. BLIP visual question answering pairs that processor with <code>BlipForQuestionAnswering</code>. Load the processor and model for the same selected checkpoint through their <code>from_pretrained</code> methods. The captioning class generates text from the image and any supplied prompt, while the question-answering class also receives the question.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
<p>For GIT captioning, <code>GitProcessor</code> prepares the inputs and <code>GitForCausalLM</code> supplies the image-conditioned text generator.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> Check the processor/model pairing, input dimensions, device, numerical types and decoded output on one image before the full protocol. A successful class import does not establish that checkpoint files loaded or that inference succeeded.</p>
<p>The source notebook uses an inspection set of at least five images spanning people, animals, indoor and outdoor scenes, and multiple objects. Retain each image with its generated caption and inspect contrasting successes and failures. A visible omission or false attribute is an observed error. An explanation of its cause remains a hypothesis until a controlled comparison supports it. This small inspection set can expose failure types but cannot provide a stable quality estimate.</p>
<p>For VQA, the source permits <code>Salesforce/blip-vqa-base</code>, <code>Salesforce/blip-vqa-capfilt-large</code>, or another suitable question-answering model. Match the processor and model to that checkpoint, and pass both the image and question. Its inspection set uses at least three images and asks object-recognition, counting, and color or attribute questions. Retain every image, question, model output, and reference answer, and inspect failures by question type. The same image can support a correct object answer and an incorrect count, so those results need separate judgments. A benchmark claim requires a larger evaluation sample selected independently of the observed failures.</p>
<p>This book uses objects or landmarks for retrieval so the mechanism can be tested without collecting or labeling people’s identities. Use four categories and six images per category, split into four references and two held-out queries. Include different viewpoints and backgrounds. These counts define the evaluation sample used for this comparison.</p>
<p>For the retrieval comparison, use one fixed pretrained encoder and its matched preprocessing, following the separate-encoder comparison in <a href="ch-m2-c22.html#sec-m2-c22-s02">§22.2</a>. Record the encoder identifier and resolved model revision, matched processor identifier and preprocessing configuration, and inference library versions. Retain that record with the stored reference vectors. Normalize nonzero image vectors, compare query vectors with stored references by cosine similarity, and aggregate reference scores using a declared rule. Report held-out top-one accuracy, a labeled confusion matrix, and two failures where available. Keep query images and near-duplicates out of the reference set.</p>
<p>Retrieval returns a category label from the candidate collection. It does not generate a description of attributes or actions. Captioning and VQA supply those separate outputs. A successful retrieval result therefore cannot substitute for the required generated-output analyses.</p>
<p>For each VQA failure, propose a possible cause grounded in the retained image, question and answer. Treat that cause as a hypothesis unless a controlled comparison supports it. Retain both successes and failures from the required samples. If the required number of failures does not occur in the initial set, inspect additional examples for diagnosis and report how they were selected. Keep those extra cases separate from the original evaluation sample and its accuracy denominator.</p>
</section>
<section id="sec-m2-c24-s08" class="level2" data-number="24.8">
<h2 data-number="24.8" class="anchored" data-anchor-id="sec-m2-c24-s08"><span class="header-section-number">24.8</span> A bounded synthesis of mechanism and evidence</h2>
<p>An evidence record must distinguish a verified calculation from a claimed task improvement. One bounded task is enough to connect input preparation, model behavior, and held-out evidence without repeating every experiment.</p>
<p>For a classification, sequence-generation, adaptation, or multimodal task, define the input, required output, reference criterion, and one change compared with a baseline. Keep unrelated settings fixed and state which objects change: input representation, parameters, decoding, storage, or scheduling.</p>
<p>The diagram depicts reverse differentiation, which is relevant when the selected task includes training.</p>
<div id="fig-m2-c24-f02" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The diagram repeats the scalar forward and backward flow from Chapter 11. It contains no lab values or separate parameter and target inputs.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-m2-c24-f02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/fig-m2-c24-f02.png" class="img-fluid figure-img" style="width:5.9in" alt="The diagram repeats the scalar forward and backward flow from Chapter 11. It contains no lab values or separate parameter and target inputs.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m2-c24-f02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.2: Forward and reverse paths connect a classifier calculation to derivatives.
</figcaption>
</figure>
</div>
<p>Its forward/reverse path repeats the mechanism in <a href="ch-m2-c11.html#sec-m2-c11-s06">§11.6</a>. It supplies no task-specific inputs, targets, values, or completed lab result. An inference-only synthesis instead tracks fixed parameters and changing input or request state.</p>
<p>The resulting evidence should contain five connected elements:</p>
<ol type="1">
<li>An environment and data record, including the held-out boundary and actual computation budget.</li>
<li>One small input traced through intermediate arrays to an independently checkable numerical result, with the relevant shapes, masks, dtype, reduction, and expected values. A training trace includes a derivative or parameter update. An inference trace includes selection and changing state.</li>
<li>A baseline and one change executed under the same evaluation protocol. Actual training or inference results remain separate from local assertions. An unavailable run stays unexecuted, with its missing dependency identified.</li>
<li>Contrasting outcomes or errors that show what the results support and which proposed causes remain uncertain. A performance claim additionally needs the timing boundary and hardware record from §23.6.</li>
<li>A configuration choice justified by the task criterion and resource cost, together with missing evidence that could change the choice and enough input-output records for another reader to inspect the conclusion.</li>
</ol>
<p>The report connects a mathematical mechanism to an observed comparison while preserving its limits. The <a href="../appendices/ch-m2-dictionary.html">Glossary</a>, <a href="../frontmatter/ch-m2-notation.html">Notation</a>, and <a href="../appendices/ch-m2-references.html">References</a> support revisiting those calculations and sources.</p>
<div class="publisher-clarification-note" data-custom-style="Clarification Note">
<p><strong>Chapter checkpoint</strong></p>
<p>A patch-shape assertion passes, a LoRA factor count is correct, and a CPU device check succeeds. Which of caption quality, successful adapter training, and GPU speed has been established?</p>
<p><strong>Answer:</strong> None of those broader results follows. The checks establish representation shape, factor count, and CPU placement under their inputs. The experiments still need generated-output judgments, actual updates and held-out comparisons, or a valid GPU measurement.</p>
<p>Why must the name split precede overlapping windows, and why is NLTK smoothing labeled a book extension?</p>
<p><strong>Answer:</strong> Related windows can otherwise expose the same name across fitting and evaluation. The original tutorial implements MLE and only lists smoothing alternatives. A smoothing experiment needs its own fitted model and matched evaluation policy.</p>
</div>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>fancyzhx. (n.d.). <em><a href="https://huggingface.co/datasets/fancyzhx/ag_news/blob/eb185aade064a813bc0b7f42de02595523103ca4/README.md">AG News dataset card</a></em>. Repository <code>fancyzhx/ag_news</code>, revision <code>eb185aade064a813bc0b7f42de02595523103ca4</code>. Pass this revision to <code>load_dataset</code> through its <code>revision</code> argument.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>NLTK Project. (2025). <em><a href="https://www.nltk.org/_modules/nltk/lm/preprocessing.html">Language-model preprocessing</a></em>. NLTK 3.9.2 source, <code>padded_everygram_pipeline</code>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>NLTK Project. (2025). <em><a href="https://www.nltk.org/_modules/nltk/lm/api.html">Language-model API</a></em>. NLTK 3.9.2 source, <code>logscore</code>, <code>entropy</code>, <code>perplexity</code>, and <code>generate</code>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>NLTK Project. (2025). <em><a href="https://www.nltk.org/_modules/nltk/lm/vocabulary.html">Language-model vocabulary</a></em>. NLTK 3.9.2 source, <code>Vocabulary</code> and <code>unk_cutoff</code>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>NLTK Project. (2025). <em><a href="https://www.nltk.org/_modules/nltk/lm/api.html">Language-model API</a></em>. NLTK 3.9.2 source, <code>logscore</code>, <code>entropy</code>, <code>perplexity</code>, and <code>generate</code>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>NLTK Project. (2025). <em><a href="https://www.nltk.org/_modules/nltk/tokenize/treebank.html">Treebank tokenization and detokenization</a></em>. NLTK 3.9.2 source, <code>TreebankWordDetokenizer</code>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>NLTK Project. (2025). <em><a href="https://www.nltk.org/_modules/nltk/lm/api.html">Language-model API</a></em>. NLTK 3.9.2 source, <code>logscore</code>, <code>entropy</code>, <code>perplexity</code>, and <code>generate</code>.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>NLTK Project. (2025). <em><a href="https://www.nltk.org/_modules/nltk/lm/api.html">Language-model API</a></em>. NLTK 3.9.2 source, <code>logscore</code>, <code>entropy</code>, <code>perplexity</code>, and <code>generate</code>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Hugging Face. (n.d.). <em><a href="https://github.com/huggingface/transformers/blob/v5.10.2/docs/source/en/model_doc/blip.md">BLIP</a></em>. Transformers 5.10.2 documentation. The captioning and visual question-answering classes have different input roles.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Hugging Face. (n.d.). <em><a href="https://github.com/huggingface/transformers/blob/v5.10.2/docs/source/en/model_doc/git.md">GIT</a></em>. Transformers 5.10.2 documentation. The model conditions text generation on image inputs.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch-m2-c23.html" class="pagination-link" aria-label="Tensor storage: Shapes, views, devices, and lifetime">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Tensor storage: Shapes, views, devices, and lifetime</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../appendices/ch-m2-dictionary.html" class="pagination-link" aria-label="Glossary">
        <span class="nav-page-text">Glossary</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>